// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials202673.model.assetManagement.breakdownOfTheNumeratorOfTheKpiCapexBased

import jakarta.validation.Valid
import org.dataland.datalandbackend.openApiClient.model.ExtendedDataPointBigDecimal
import org.dataland.datalandqaservice.model.reports.QaReportDataPoint

/**
 * The QA-model for the BreakdownOfTheNumeratorOfTheKpiCapexBased section
 */
@Suppress("MaxLineLength")
data class EutaxonomyFinancials202673AssetmanagementBreakdownOfTheNumeratorOfTheKpiCapexBased(
    @field:Valid()
    val shareOfCapexBasedKpiInPercentEligible: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val shareOfCapexBasedKpiExposedTowardsNuclearActivitiesInPercentEligible: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val shareOfCapexBasedKpiExposedTowardsFossilGasActivitiesInPercentEligible: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val shareOfCapexBasedKpiInPercentAligned: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val shareOfCapexBasedKpiExposedTowardsNuclearActivitiesInPercentAligned: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val shareOfCapexBasedKpiExposedTowardsFossilGasActivitiesInPercentAligned: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val shareOfCapexBasedKpiInPercentOfWhichTransitional: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val shareOfCapexBasedKpiInPercentOfWhichEnabling: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val capexBasedNonAssessedExposures: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val capexBasedNonAssessedExposuresOfWhichExposuresFinancingNonAssessedNonMaterialActivitiesOfCounterparties:
        QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val capexBasedNonAssessedExposuresOfWhichNonAssessedExposuresConsideredNonMaterialByTheReportingEntity:
        QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val capexBasedNonAssessedExposuresOfWhichExposuresToCounterpartiesReportingNoTaxonomyEligibleActivities:
        QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
)
