// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.pcaf.model.environmental

import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.pcaf.model.environmental.greenhouseGasEmissions
    .PcafEnvironmentalGreenhouseGasEmissions

/**
 * The data-model for the Environmental section
 */
@Suppress("MaxLineLength")
data class PcafEnvironmental(
    @field:Valid()
    val greenhouseGasEmissions: PcafEnvironmentalGreenhouseGasEmissions? = null,
)
