// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgquestionnaire.model.allgemein.esgBerichte

import io.swagger.v3.oas.annotations.media.Schema

/**
 * Enum class for the single-select-field frequenzDerBerichterstattung
 */
@Schema(
    enumAsRef = true,
)
enum class EsgQuestionnaireAllgemeinEsgberichteFrequenzDerBerichterstattungOptions {
    Jaehrlich,
    Halbjaehrlich,
    Vierteljaehrlich,
    Monatlich,
}
