// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgquestionnaire.model.allgemein.esgBerichte

import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.BaseDataPoint

/**
 * The data-model for the EsgBerichte section
 */
data class EsgQuestionnaireAllgemeinEsgBerichte(
    @field:Valid()
    val aktuelleBerichte: List<BaseDataPoint<String>>? = null,

)
