// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.allgemein.taxonomieKpisUndBestimmteAktivitaeten

import org.dataland.datalandbackend.model.enums.commons.YesNo
import org.dataland.datalandbackend.validator.MinimumValue
import java.math.BigDecimal

/**
 * The data-model for the TaxonomieKpisUndBestimmteAktivitaeten section
 */
data class EsgDatenkatalogAllgemeinTaxonomieKpisUndBestimmteAktivitaeten(
    val wirtschaftszweige: List<String>? = null,
    @field:MinimumValue(minimumValue = 0)
    val gesamtumsatz: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    val taxonomiefaehigerUmsatz: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    val taxonomiekonformerUmsatz: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    val gesamtCapex: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    val taxonomiefaehigeCapex: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    val taxonomiekonformeCapex: BigDecimal? = null,
    val taxonomiebezogeneCapexPlanung: YesNo? = null,
    val geplanteTaxonomiefaehigeCapexIn5Jahren: BigDecimal? = null,
    val geplanteTaxonomiekonformeCapexIn5Jahren: BigDecimal? = null,
    val aktivitaetImSektorFossileBrennstoffe: YesNo? = null,
    val aktuellerProzentualerUmsatzanteilImSektorFossileBrennstoffe: BigDecimal? = null,
    val geplanterProzentualerUmsatzanteilImSektorFossileBrennstoffeIn2030: BigDecimal? = null,
    val geplanterProzentualerUmsatzanteilImSektorFossileBrennstoffeIn2040: BigDecimal? = null,
    val aktivitaetImSektorHerstellungVonChemikalien: YesNo? = null,
    val aktuellerProzentualerUmsatzanteilImSektorHerstellungVonChemikalien: BigDecimal? = null,
    val geplanterProzentualerUmsatzanteilImSektorHerstellungVonChemikalienIn2030: BigDecimal? = null,
    val geplanterProzentualerUmsatzanteilImSektorHerstellungVonChemikalienIn2040: BigDecimal? = null,
    val aktivitaetImSektorUmstritteneWaffen: YesNo? = null,
    val aktuellerProzentualerUmsatzanteilImSektorUmstritteneWaffen: BigDecimal? = null,
    val geplanterProzentualerUmsatzanteilImSektorUmstritteneWaffenIn2030: BigDecimal? = null,
    val geplanterProzentualerUmsatzanteilImSektorUmstritteneWaffenIn2040: BigDecimal? = null,
    val aktivitaetImSektorTabakanbauUndVerarbeitung: YesNo? = null,
    val aktuellerProzentualerUmsatzanteilImSektorTabakanbauUndVerarbeitung: BigDecimal? = null,
    val geplanterProzentualerUmsatzanteilImSektorTabakanbauUndVerarbeitungIn2030: BigDecimal? = null,
    val geplanterProzentualerUmsatzanteilImSektorTabakanbauUndVerarbeitungIn2040: BigDecimal? = null,
)
