[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/main", "src/main/infrastructure"]

[project]
name = "dataland-automated-qa-service"
version = "1"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src/main"

[tool.coverage.run]
relative_files = true

[tool.coverage.paths]
source = ["./src/main"]


#[tool.ruff]
#select = ["F", "I"]
#line-length = 120
