// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.heimathafen.model.governance.kontroverseGeschaeftsfelder

import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the KontroverseGeschaeftsfelder section
 */
data class HeimathafenGovernanceKontroverseGeschaeftsfelder(
    val kontroversenImBereichDerBestechungUndKorruption: YesNo? = null,
    val wennNeinBitteBegruendenKontroverseGeschaeftsfelder: String? = null,
    val verwendeteMetrikenUndMethodik: String? = null,
    val verwendeteQuellenKontroverseGeschaeftsfelder: String? = null,
    val dieAktualitaetDerKontroversenImBereichBestechungUndKorruption: String? = null,
)
