// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandqaservice.frameworks.nuclearandgas.model

import jakarta.validation.Valid
import org.dataland.datalandqaservice.frameworks.nuclearandgas.model.nuclearAndGas.NuclearAndGasNuclearAndGas

/**
 * The root QA data-model for the Nuclear-and-gas Framework
 */
data class NuclearAndGasData(
    @field:Valid()
    val nuclearAndGas: NuclearAndGasNuclearAndGas? = null,

)
