// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type BaseFrameworkDefinition } from "@/frameworks/FrameworkDefinition";
import { type Configuration, type SmeData } from "@clients/backend";
import { type AxiosInstance } from "axios";
import { type FrameworkDataApi } from "@/utils/api/UnifiedFrameworkDataApi";
import { SmeApiClient } from "@/frameworks/sme/ApiClient";

export class BaseSmeFrameworkDefinition implements BaseFrameworkDefinition<SmeData> {
  readonly identifier = "sme";
  readonly explanation = "Small and medium-sized enterprises questionnaire";
  readonly label = "SME";
  getFrameworkApiClient(configuration?: Configuration, axiosInstance?: AxiosInstance): FrameworkDataApi<SmeData> {
    return new SmeApiClient(configuration, axiosInstance);
  }
}

export default new BaseSmeFrameworkDefinition();
