// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandqaservice.frameworks.sfdr.model.financial.unlistedCompany

import jakarta.validation.Valid
import org.dataland.datalandbackend.openApiClient.model.ExtendedDataPointBigDecimal
import org.dataland.datalandqaservice.model.reports.QaReportDataPoint

/**
 * The QA-model for the UnlistedCompany section
 */
data class SfdrFinancialUnlistedCompany(
    @field:Valid()
    val totalEquityInEUR: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
    @field:Valid()
    val totalEquityAndDebtInEUR: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,
)
