#!/usr/bin/env bash
set -euxo pipefail

kt_files="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"

if [ -z "$kt_files" ]; then
  echo "No Kotlin staged files."
else
  echo "Running ktlint over these files:"
  echo "$kt_files"

  ./gradlew ktlintFormat -PinternalKtlintGitFilter="$kt_files"

  echo "Completed ktlint run."

  echo "Starting detekt run"
  ./gradlew detekt
  echo "Completed detekt run"

  echo "$kt_files" | while read -r file; do
    if [ -f $file ]; then
      git add $file
    fi
  done

fi

echo "Starting eslint hook"
cd dataland-frontend && npx --prefix ./dataland-frontend lint-staged
