// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomyfinancials202673.model.investmentFirms.otherServicesCapexBased

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.CurrencyDataPoint
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import org.dataland.datalandbackend.validator.MinimumValue
import java.math.BigDecimal

/**
 * The data-model for the OtherServicesCapexBased section
 */
@Suppress("MaxLineLength")
data class EutaxonomyFinancials202673InvestmentfirmsOtherServicesCapexBased(
    @field:MinimumValue(minimumValue = 0)
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Total assets invested under investment firms' activities Other Services (as per Section A of Annex I to Directive 2014/65/EU)""",
        example = """{
      "value" : 100.5,
      "currency" : "USD",
      "quality" : "Reported",
      "comment" : "The value is reported by the company.",
      "dataSource" : {
      "page" : "5-7",
      "tagName" : "monetaryAmount",
      "fileName" : "AnnualReport2020.pdf",
      "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
    } """,
    )
    val capexBasedTotalRevenueFromInvestmentsAndServicesAndActivitiesOtherThanDealingOnOwnAccount: CurrencyDataPoint? = null,
    @field:MinimumValue(minimumValue = 0)
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Total Revenue (i.e. fees, commissions and other monetary benefits) from investment and services and activities other than dealing on own account (as per Section A of Annex I to Directive 2014/65/EU) of which covered by the CapEx""",
        example = """{
      "value" : 100.5,
      "currency" : "USD",
      "quality" : "Reported",
      "comment" : "The value is reported by the company.",
      "dataSource" : {
      "page" : "5-7",
      "tagName" : "monetaryAmount",
      "fileName" : "AnnualReport2020.pdf",
      "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
    } """,
    )
    val capexBasedTotalRevenueFromInvestmentsAndServicesAndActivitiesOtherThanDealingOnOwnAccountOfWhichCoveredByTheCapex:
        CurrencyDataPoint? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to Climate Change Mitigation""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToClimateChangeMitigationAligned: ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to Climate Change Adaptation""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToClimateChangeAdaptationAligned: ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to Sustainable Use and Protection of Water and Marine Resources""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToSustainableUseAndProtectionOfWaterAndMarineResourcesAligned:
        ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to Circular Economy""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToCircularEconomyAligned: ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to Pollution Prevention and Control""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToPollutionPreventionAndControlAligned:
        ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to Protection and Restoration of Biodiversity and Ecosystems""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToProtectionAndRestorationOfBiodiversityAndEcosystemsAligned:
        ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to any of the six Environmental Objectives""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToAnyOfTheSixEnvironmentalObjectivesEligible:
        ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to any of the six Environmental Objectives""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToAnyOfTheSixEnvironmentalObjectivesAligned:
        ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned and transitional CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to any of the six Environmental Objectives""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToAnyOfTheSixEnvironmentalObjectivesOfWhichTransitional:
        ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned and enabling CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities substantially contributing to any of the six Environmental Objectives""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueSubstantiallyContributingToAnyOfTheSixEnvironmentalObjectivesOfWhichEnabling:
        ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """CapEx-based Proportion of Revenue (Fees, Commissions and other Monetary Services) from Investments and Services and Activities of which Non-Assessed Exposures""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedNonAssessedExposures: ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-eligible CapEx-based Proportion of Revenue from Operation of an OTF which are exposed towards Nuclear Activities""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueFromOperationOfAnOtfOfWhichNuclearActivitiesEligible: ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-eligible CapEx-based Proportion of Revenue from Operation of an OTF which are exposed towards Fossil Gas Activities""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueFromOperationOfAnOtfOfWhichFossilGasActivitiesEligible: ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue from Operation of an OTF which are exposed towards Nuclear Activities""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueFromOperationOfAnOtfOfWhichNuclearActivitiesAligned: ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Taxonomy-aligned CapEx-based Proportion of Revenue from Operation of an OTF which are exposed towards Fossil Gas Activities""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val capexBasedProportionOfRevenueFromOperationOfAnOtfOfWhichFossilGasActivitiesAligned: ExtendedDataPoint<BigDecimal?>? = null,
)
