// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.lksg.model.governance.generalViolations

import org.dataland.datalandbackend.model.enums.commons.YesNo
import java.util.EnumSet

/**
 * The data-model for the GeneralViolations section
 */
data class LksgGovernanceGeneralViolations(
    val responsibilitiesForFairWorkingConditions: YesNo? = null,

    val responsibilitiesForTheEnvironment: YesNo? = null,

    val responsibilitiesForOccupationalSafety: YesNo? = null,

    val legalProceedings: YesNo? = null,

    val humanRightsOrEnvironmentalViolations: YesNo? = null,

    val humanRightsOrEnvironmentalViolationsDefinition:
    EnumSet<HumanRightsOrEnvironmentalViolationsDefinitionOptions>? = null,

    val humanRightsOrEnvironmentalViolationsMeasures: YesNo? = null,

    val humanRightsOrEnvironmentalViolationsMeasuresDefinition: String? = null,

    val highRiskCountriesRawMaterials: YesNo? = null,

    val highRiskCountriesRawMaterialsLocation: EnumSet<HighRiskCountriesRawMaterialsLocationOptions>? = null,

    val highRiskCountriesActivity: YesNo? = null,

    val highRiskCountries: EnumSet<HighRiskCountriesOptions>? = null,

    val highRiskCountriesProcurement: YesNo? = null,

    val highRiskCountriesProcurementName: EnumSet<HighRiskCountriesProcurementNameOptions>? = null,

)
