// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.validator

import jakarta.validation.Constraint
import jakarta.validation.ConstraintValidator
import jakarta.validation.ConstraintValidatorContext
import jakarta.validation.Payload
import org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.EutaxonomyNonFinancialsData
import org.dataland.datalandbackend.model.documents.CompanyReport
import kotlin.reflect.KClass

/**
* Annotation for the validation of referenced reports list for eutaxonomy-non-financials
*/

@Constraint(validatedBy = [ReferencedReportsListConstraintValidator::class])
@Target(AnnotationTarget.FIELD, AnnotationTarget.CLASS)
annotation class ReferencedReportsListValidator(
    val message: String = "The list of referenced reports is not complete. Please ensure that any file used as a " +
        "data source in the dataset is included in the list of referenced reports.",
    val groups: Array<KClass<*>> = [],
    val payload: Array<KClass<out Payload>> = [],
)

/**
* Class holding the validation logic for referenced reports list. It checks if the referenced reports list is complete
*/
class ReferencedReportsListConstraintValidator :
    ConstraintValidator<ReferencedReportsListValidator, EutaxonomyNonFinancialsData> {

    override fun isValid(dataset: EutaxonomyNonFinancialsData?, context: ConstraintValidatorContext?): Boolean {
        if (dataset == null) {
            return false
        }
        val referencedReportsMap = dataset.general?.referencedReports
        val referencedReportsFileReference = getFileReferencesFromReports(referencedReportsMap)

        val extendedDocumentsFileReferences = getExtendedDocumentReferences(dataset).filterNotNull()
        return extendedDocumentsFileReferences.all {
            referencedReportsFileReference.contains(it)
        }
    }

    private fun getFileReferencesFromReports(map: Map<String, CompanyReport>?): List<String> {
        if (map == null) return emptyList()
        val referencedReportsList = mutableListOf<String>()
        for (entry in map.entries) {
            referencedReportsList.add(entry.value.fileReference)
        }
        return referencedReportsList
    }

    @Suppress("MaxLineLength", "LongMethod")
    private fun getExtendedDocumentReferences(dataset: EutaxonomyNonFinancialsData): List<String?> {
        return listOf(
            dataset.general?.fiscalYearDeviation?.dataSource?.fileReference,
            dataset.general?.fiscalYearEnd?.dataSource?.fileReference,
            dataset.general?.scopeOfEntities?.dataSource?.fileReference,
            dataset.general?.nfrdMandatory?.dataSource?.fileReference,
            dataset.general?.euTaxonomyActivityLevelReporting?.dataSource?.fileReference,
            dataset.general?.assurance?.dataSource?.fileReference,
            dataset.general?.numberOfEmployees?.dataSource?.fileReference,
            dataset.revenue?.totalAmount?.dataSource?.fileReference,
            dataset.revenue?.nonEligibleShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.revenue?.nonEligibleShare?.absoluteShare?.dataSource?.fileReference,
            dataset.revenue?.eligibleShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.revenue?.eligibleShare?.absoluteShare?.dataSource?.fileReference,
            dataset.revenue?.nonAlignedShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.revenue?.nonAlignedShare?.absoluteShare?.dataSource?.fileReference,
            dataset.revenue?.alignedShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.revenue?.alignedShare?.absoluteShare?.dataSource?.fileReference,
            dataset.revenue?.substantialContributionToClimateChangeMitigationInPercent?.dataSource?.fileReference,
            dataset.revenue?.substantialContributionToClimateChangeAdaptationInPercent?.dataSource?.fileReference,
            dataset.revenue?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercent?.dataSource?.fileReference,
            dataset.revenue?.substantialContributionToTransitionToACircularEconomyInPercent?.dataSource?.fileReference,
            dataset.revenue?.substantialContributionToPollutionPreventionAndControlInPercent?.dataSource?.fileReference,
            dataset.revenue?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercent?.dataSource?.fileReference,
            dataset.revenue?.enablingShareInPercent?.dataSource?.fileReference,
            dataset.revenue?.transitionalShareInPercent?.dataSource?.fileReference,
            dataset.capex?.totalAmount?.dataSource?.fileReference,
            dataset.capex?.nonEligibleShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.capex?.nonEligibleShare?.absoluteShare?.dataSource?.fileReference,
            dataset.capex?.eligibleShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.capex?.eligibleShare?.absoluteShare?.dataSource?.fileReference,
            dataset.capex?.nonAlignedShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.capex?.nonAlignedShare?.absoluteShare?.dataSource?.fileReference,
            dataset.capex?.alignedShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.capex?.alignedShare?.absoluteShare?.dataSource?.fileReference,
            dataset.capex?.substantialContributionToClimateChangeMitigationInPercent?.dataSource?.fileReference,
            dataset.capex?.substantialContributionToClimateChangeAdaptationInPercent?.dataSource?.fileReference,
            dataset.capex?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercent?.dataSource?.fileReference,
            dataset.capex?.substantialContributionToTransitionToACircularEconomyInPercent?.dataSource?.fileReference,
            dataset.capex?.substantialContributionToPollutionPreventionAndControlInPercent?.dataSource?.fileReference,
            dataset.capex?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercent?.dataSource?.fileReference,
            dataset.capex?.enablingShareInPercent?.dataSource?.fileReference,
            dataset.capex?.transitionalShareInPercent?.dataSource?.fileReference,
            dataset.opex?.totalAmount?.dataSource?.fileReference,
            dataset.opex?.nonEligibleShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.opex?.nonEligibleShare?.absoluteShare?.dataSource?.fileReference,
            dataset.opex?.eligibleShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.opex?.eligibleShare?.absoluteShare?.dataSource?.fileReference,
            dataset.opex?.nonAlignedShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.opex?.nonAlignedShare?.absoluteShare?.dataSource?.fileReference,
            dataset.opex?.alignedShare?.relativeShareInPercent?.dataSource?.fileReference,
            dataset.opex?.alignedShare?.absoluteShare?.dataSource?.fileReference,
            dataset.opex?.substantialContributionToClimateChangeMitigationInPercent?.dataSource?.fileReference,
            dataset.opex?.substantialContributionToClimateChangeAdaptationInPercent?.dataSource?.fileReference,
            dataset.opex?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercent?.dataSource?.fileReference,
            dataset.opex?.substantialContributionToTransitionToACircularEconomyInPercent?.dataSource?.fileReference,
            dataset.opex?.substantialContributionToPollutionPreventionAndControlInPercent?.dataSource?.fileReference,
            dataset.opex?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercent?.dataSource?.fileReference,
            dataset.opex?.enablingShareInPercent?.dataSource?.fileReference,
            dataset.opex?.transitionalShareInPercent?.dataSource?.fileReference,
        )
    }
}
