// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.integrationTesting.model.section

import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.integrationTesting.model.section.subsection
    .IntegrationtestingSectionSubsection

/**
 * The data-model for the Section section
 */
data class IntegrationtestingSection(
    @field:Valid()
    val subsection: IntegrationtestingSectionSubsection,
    val noSubsection: String? = null,
)
