#!/usr/bin/env bash
set -euo pipefail
expected_vars=( \
  GITHUB_TOKEN \
  GITHUB_USER \
  MAILJET_API_ID \
  MAILJET_API_SECRET \
  BACKEND_DB_PASSWORD \
  API_KEY_MANAGER_DB_PASSWORD \
  INTERNAL_STORAGE_DB_PASSWORD \
  DOCUMENT_MANAGER_DB_PASSWORD \
  QA_SERVICE_DB_PASSWORD \
  EMAIL_SERVICE_DB_PASSWORD \
  COMMUNITY_MANAGER_DB_PASSWORD\
  PGADMIN_PASSWORD \
  GRAFANA_PASSWORD \
  ELECTRON_EXTRA_LAUNCH_ARGS \
  INITIALIZE_KEYCLOAK \
  KEYCLOAK_ADMIN \
  KEYCLOAK_ADMIN_PASSWORD \
  KEYCLOAK_DB_PASSWORD \
  KEYCLOAK_FRONTEND_URL \
  KEYCLOAK_READER_PASSWORD \
  KEYCLOAK_READER_SALT \
  KEYCLOAK_READER_VALUE \
  KEYCLOAK_UPLOADER_PASSWORD \
  KEYCLOAK_UPLOADER_SALT \
  KEYCLOAK_UPLOADER_VALUE \
  KEYCLOAK_REVIEWER_PASSWORD \
  KEYCLOAK_REVIEWER_SALT \
  KEYCLOAK_REVIEWER_VALUE \
  KEYCLOAK_PREMIUM_USER_PASSWORD \
  KEYCLOAK_PREMIUM_USER_VALUE \
  KEYCLOAK_PREMIUM_USER_SALT \
  KEYCLOAK_DATALAND_ADMIN_PASSWORD \
  KEYCLOAK_DATALAND_ADMIN_SALT \
  KEYCLOAK_DATALAND_ADMIN_VALUE \
  EXPECT_STACKTRACE \
  SONAR_TOKEN \
  SSH_PRIVATE_KEY \
  TARGETSERVER_HOST_KEYS \
  TARGETSERVER_URL \
  KEYCLOAK_GOOGLE_ID \
  KEYCLOAK_GOOGLE_SECRET \
  KEYCLOAK_LINKEDIN_ID \
  KEYCLOAK_LINKEDIN_SECRET \
  PROXY_PRIMARY_URL \
  PROXY_LETSENCRYPT_PATH \
  RABBITMQ_USER \
  RABBITMQ_PASS \
  RABBITMQ_PASS_HASH \
  INTERNAL_BACKEND_URL \
  NOTIFICATION_INTERNAL_RECEIVERS \
  NOTIFICATION_INTERNAL_CC \
  DATALAND_COMMUNITY_MANAGER_CLIENT_SECRET \
  DATALAND_DOCUMENT_MANAGER_CLIENT_SECRET \
  DATALAND_BACKEND_CLIENT_SECRET \
)

for var in "${expected_vars[@]}"
do
  value=${!var:+isSet}
  if [[ $value != "isSet" ]]; then echo Warning - $var is not set; fi
done