// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.sme.model.basic.workforceHealthAndSafety

import java.math.BigDecimal
import java.math.BigInteger

/**
 * The data-model for the WorkforceHealthAndSafety section
 */
data class SmeBasicWorkforceHealthAndSafety(
    val totalHours: BigDecimal? = null,

    val numberOfAccidents: BigInteger? = null,

    val accidentLevel: BigDecimal? = null,

    val numberFatalitiesTotalFullTime: BigInteger? = null,

    val numberFatalitiesTotalHead: BigInteger? = null,

    val numberFatalitiesAccidentFullTime: BigInteger? = null,

    val numberFatalitiesAccidentHead: BigInteger? = null,

    val numberFatalitiesHealthFullTime: BigInteger? = null,

    val numberFatalitiesHealthHead: BigInteger? = null,

)
