// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.lksg.model.social

import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.lksg.model.social.childLabor.LksgSocialChildLabor
import org.dataland.datalandbackend.frameworks.lksg.model.social
    .contaminationOfSoilWaterAirNoiseEmissionsExcessiveWaterConsumption
    .LksgSocialContaminationOfSoilWaterAirNoiseEmissionsExcessiveWaterConsumption
import org.dataland.datalandbackend.frameworks.lksg.model.social.disregardForFreedomOfAssociation
    .LksgSocialDisregardForFreedomOfAssociation
import org.dataland.datalandbackend.frameworks.lksg.model.social.disregardForOccupationalHealthSafety
    .LksgSocialDisregardForOccupationalHealthSafety
import org.dataland.datalandbackend.frameworks.lksg.model.social.forcedLaborSlavery.LksgSocialForcedLaborSlavery
import org.dataland.datalandbackend.frameworks.lksg.model.social.unequalTreatmentOfEmployment
    .LksgSocialUnequalTreatmentOfEmployment
import org.dataland.datalandbackend.frameworks.lksg.model.social.unlawfulEvictionDeprivationOfLandForestAndWater
    .LksgSocialUnlawfulEvictionDeprivationOfLandForestAndWater
import org.dataland.datalandbackend.frameworks.lksg.model.social
    .useOfPrivatePublicSecurityForcesWithDisregardForHumanRights
    .LksgSocialUseOfPrivatePublicSecurityForcesWithDisregardForHumanRights
import org.dataland.datalandbackend.frameworks.lksg.model.social.withholdingAdequateWages
    .LksgSocialWithholdingAdequateWages

/**
 * The data-model for the Social section
 */
data class LksgSocial(
    @field:Valid()
    val childLabor: LksgSocialChildLabor? = null,

    @field:Valid()
    val forcedLaborSlavery: LksgSocialForcedLaborSlavery? = null,

    @field:Valid()
    val withholdingAdequateWages: LksgSocialWithholdingAdequateWages? = null,

    @field:Valid()
    val disregardForOccupationalHealthSafety: LksgSocialDisregardForOccupationalHealthSafety? = null,

    @field:Valid()
    val disregardForFreedomOfAssociation: LksgSocialDisregardForFreedomOfAssociation? = null,

    @field:Valid()
    val unequalTreatmentOfEmployment: LksgSocialUnequalTreatmentOfEmployment? = null,

    @field:Valid()
    val contaminationOfSoilWaterAirNoiseEmissionsExcessiveWaterConsumption:
    LksgSocialContaminationOfSoilWaterAirNoiseEmissionsExcessiveWaterConsumption? = null,

    @field:Valid()
    val unlawfulEvictionDeprivationOfLandForestAndWater:
    LksgSocialUnlawfulEvictionDeprivationOfLandForestAndWater? = null,

    @field:Valid()
    val useOfPrivatePublicSecurityForcesWithDisregardForHumanRights:
    LksgSocialUseOfPrivatePublicSecurityForcesWithDisregardForHumanRights? = null,

)
