interface ImportMeta {
  env: {
    VITE_DATA_REQUEST_UPLOAD_MAX_FILE_SIZE_IN_MEGABYTES: number;
    VITE_DOCUMENT_UPLOAD_MAX_FILE_SIZE_IN_MEGABYTES: number;
    VITE_MAX_NUMBER_OF_DAYS_SELECTABLE_FOR_API_KEY_VALIDITY: number;
  };
}
