// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type BasePublicFrameworkDefinition } from '@/frameworks/BasePublicFrameworkDefinition';
import { type Configuration, type EutaxonomyNonFinancialsData } from '@clients/backend';
import { type AxiosInstance } from 'axios';
import { type PublicFrameworkDataApi } from '@/utils/api/UnifiedFrameworkDataApi';
import { EutaxonomyNonFinancialsApiClient } from '@/frameworks/eutaxonomy-non-financials/ApiClient';

export class BaseEutaxonomyNonFinancialsFrameworkDefinition
  implements BasePublicFrameworkDefinition<EutaxonomyNonFinancialsData>
{
  readonly identifier = 'eutaxonomy-non-financials';
  readonly explanation = 'The EU-Taxonomy framework for non-financial companies';
  readonly label = 'EU Taxonomy Non-Financials';
  getPublicFrameworkApiClient(
    configuration?: Configuration,
    axiosInstance?: AxiosInstance
  ): PublicFrameworkDataApi<EutaxonomyNonFinancialsData> {
    return new EutaxonomyNonFinancialsApiClient(configuration, axiosInstance);
  }
}

export default new BaseEutaxonomyNonFinancialsFrameworkDefinition();
