// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.umwelt.risikenUndMassnahmenKlima

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.umwelt.risikenUndMassnahmenKlima
    .PhysischeKlimaUndUmweltrisikenOptions
import org.dataland.datalandbackend.model.datapoints.BaseDataPoint
import org.dataland.datalandbackend.model.enums.commons.YesNo
import org.dataland.datalandbackend.model.enums.commons.YesNoNa
import java.math.BigDecimal
import java.util.EnumSet

/**
 * The data-model for the RisikenUndMassnahmenKlima section
 */
@Suppress("MaxLineLength")
data class EsgDatenkatalogUmweltRisikenUndMassnahmenKlima(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welchen wesentlichen transitorischen Klima- und Umweltrisiken ist das Unternehmen ausgesetzt? Transitorische Risiken sind Übergangsrisiken, die sich aus einer unzureichenden Anpassung des Unternehmens an Maßnahmen zum Schutz, zur Wiederherstellung und/oder zur Verringerung negativer Auswirkungen auf die Natur ergeben. Diese Risiken können z. B. durch Änderungen in der Gesetzgebung und Politik, Präzedenzfälle, Technologien, die Stimmung der Investoren und Verbraucherpräferenzen, Haftungsrisiken oder Reputationsrisiken ausgelöst werden. Sie können auch aus Aktivitäten entstehen, die auf die Wiederherstellung der Natur abzielen, aber beispielsweise nicht mehr mit der geänderten Politik übereinstimmen.""",
        example = """ "This is some free text"  """,
    )
    val transitorischeKlimaUndUmweltrisiken: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welchen physischen Klima- und Umweltrisiken ist das Unternehmen ausgesetzt?""",
        example = """ ["Option 1","Option 2"]  """,
    )
    val physischeKlimaUndUmweltrisiken: EnumSet<PhysischeKlimaUndUmweltrisikenOptions>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte geben Sie zu jedem relevanten Klima-/Umweltrisiko jene Standorte des Unternehmens an, welche dem jeweiligen Risiko ausgesetzt sind.""",
        example = """ "This is some free text"  """,
    )
    val vonPhysischenKlimaUndUmweltrisikenBetroffeneStandorte: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Misst, steuert und überwacht das Unternehmen diese Klima- und Umweltrisiken?""",
        example = """ "Yes"  """,
    )
    val messungSteuerungUndUeberwachungDerKlimaUndUmweltrisiken: YesNoNa? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte beschreiben Sie das Vorgehen, mit dem Klima- und Umweltrisiken gemessen, gesteuert und überwacht werden.""",
        example = """ "This is some free text"  """,
    )
    val beschreibungDerMessungSteuerungUndUeberwachungDerKlimaUndUmweltrisiken: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Werden bei der Messung, Steuerung und Überwachung der Klima- und Umweltrisiken Szenarioanalysen genutzt?""",
        example = """ "Yes"  """,
    )
    val nutzungVonSzenarioanalysen: YesNoNa? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte beschreiben Sie auf welcher Art und Weise Szenarioanalysen genutzt werden, um Klima- und Umweltirisken zu messen, zu steuern und zu überwachen.""",
        example = """ "This is some free text"  """,
    )
    val beschreibungDerNutzungVonSzenarioanalysen: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Werden Klima- und Umweltrisiken in der Geschäftsstrategie und/oder im Geschäftsmodell des Unternehmens thematisiert?""",
        example = """ "Yes"  """,
    )
    val beruecksichtigungVonKlimaUndUmweltrisiken: YesNo? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Stellen Sie die genutzten Zeithorizonte dar, welche bei der Berücksichtigung von Klima- und Umweltrisiken in der Geschäftsstrategie und/oder im Geschäftsmodell des Unternehmens betrachtet werden.""",
        example = """ "This is some free text"  """,
    )
    val zeithorizontDerBeruecksichtigungVonKlimaUndUmweltrisikenImGeschaeftsmodell: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Verfügt das Unternehmen über einen Transitionsplan?""",
        example = """ "Yes"  """,
    )
    @field:Valid()
    val transitionsplan: BaseDataPoint<YesNo>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Maßnahmen hat das Unternehmen zur Reduzierung transitorischer Risiken getroffen bzw. geplant? Bitte zudem darstellen, ob das Unternehmen über interne Richtlinien verfügt, die einen ökologischen Mindeststandard im Produktionsprozess sicherstellen.""",
        example = """ "This is some free text"  """,
    )
    val transitorischeRisiken: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Maßnahmen hat das Unternehmen zur Reduzierung physischer Risiken getroffen bzw. geplant? Bitte zudem darstellen, ob das Unternehmen über interne Richtlinien verfügt, die einen ökologischen Mindeststandard im Produktionsprozess sicherstellen.""",
        example = """ "This is some free text"  """,
    )
    val physischeRisiken: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Entwickelt, produziert oder vertreibt das Unternehmen Produkte, die die Umweltbelastung verringern? """,
        example = """ "Yes"  """,
    )
    val produkteZurReduzierungDerUmweltbelastung: YesNoNa? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte kurz skizzieren wie die Produkte die Umweltbelastung verringern.""",
        example = """ "This is some free text"  """,
    )
    val skizzierungDerProdukteZurReduzierungDerUmweltbelastung: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Zielsetzung verfolgt das Unternehmen bei der Reduzierung seiner Treibhausgasemissionen für 2030?""",
        example = """13.52 """,
    )
    val zielReduzierungTreibhausgasemissionen2030: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Zielsetzung verfolgt das Unternehmen bei der Reduzierung seiner Treibhausgasemissionen für 2040? Optionale Angabe.""",
        example = """13.52 """,
    )
    val zielReduzierungTreibhausgasemissionen2040: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Zielsetzung verfolgt das Unternehmen bei der Reduzierung seiner Treibhausgasemissionen für 2050? Optionale Angabe.""",
        example = """13.52 """,
    )
    val zielReduzierungTreibhausgasemissionen2050: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte die Zielsetzung konkretisieren, inkl. Zielwerte, Zwischenziele und zugrundeliegendem Scope der Treibhausgas-Emissionen. Soweit eine dezidierte Planung Planung zu Scope 1, 2, 3 besteht, bitte diese kurz darstellen. Bitte zudem kurze Darstellung, ob Reduktion konstant erfolgt oder von Einzelmaßnahmen abhängt sowie ob Pläne mit den Zielen des Pariser Klimaabkommens kompatibel sind.""",
        example = """ "This is some free text"  """,
    )
    val zielReduzierungTreibhausgasemissionenErlaeuterungen: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Nutzt das Unternehmen Kompensationsinstrumente in Bezug auf Treibhausgasemissionen?""",
        example = """ "Yes"  """,
    )
    val kompensationsinstrumenteTreibhausgasemissionen: YesNo? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte benennen Sie die der Kompensation für Treibhasgasemissionen zugrundeliegenden Zertifizierungen.""",
        example = """ "This is some free text"  """,
    )
    val zertifizierungenBezueglichKompensationinstrumenten: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Zielsetzung verfolgt das Unternehmen bzgl. des Anteils erneuerbarer Energien am gesamten Energieverbrauch für 2030?""",
        example = """13.52 """,
    )
    val zielAnteilErneuerbarerEnergien2030: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Zielsetzung verfolgt das Unternehmen bzgl. des Anteils erneuerbarer Energien am gesamten Energieverbrauch für 2040?  Optionale Angabe.""",
        example = """13.52 """,
    )
    val zielAnteilErneuerbarerEnergien2040: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Zielsetzung verfolgt das Unternehmen bzgl. des Anteils erneuerbarer Energien am gesamten Energieverbrauch für 2050? Optionale Angabe.""",
        example = """13.52 """,
    )
    val zielAnteilErneuerbarerEnergien2050: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte erläutern sie Ihren Plan für den Anteil erneuerbarer Energien, falls erforderlich.""",
        example = """ "This is some free text"  """,
    )
    val zielAnteilErneuerbarerEnergienErlaeuterungen: String? = null,
)
