// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.investmentFirms

import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.investmentFirms.capexBasedKpi
    .EutaxonomyFinancialsInvestmentfirmsCapexBasedKpi
import org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.investmentFirms.turnoverBasedKpi
    .EutaxonomyFinancialsInvestmentfirmsTurnoverBasedKpi

/**
 * The data-model for the InvestmentFirms section
 */
data class EutaxonomyFinancialsInvestmentFirms(
    @field:Valid()
    val turnoverBasedKpi: EutaxonomyFinancialsInvestmentfirmsTurnoverBasedKpi? = null,

    @field:Valid()
    val capexBasedKpi: EutaxonomyFinancialsInvestmentfirmsCapexBasedKpi? = null,

)
