// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials.model.assetManagement

import jakarta.validation.Valid
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials.model.assetManagement
    .averageValueOfTaxonomyAlignedUndertakings
    .EutaxonomyFinancialsAssetmanagementAverageValueOfTaxonomyAlignedUndertakings
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials.model.assetManagement
    .breakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveCapexBased
    .EutaxonomyFinancialsAssetmanagementBreakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveCapexBased
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials.model.assetManagement
    .breakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveTurnoverBased
    .EutaxonomyFinancialsAssetmanagementBreakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveTurnoverBased

/**
 * The QA-model for the AssetManagement section
 */
data class EutaxonomyFinancialsAssetManagement(
    @field:Valid()
    val averageValueOfTaxonomyAlignedUndertakings:
    EutaxonomyFinancialsAssetmanagementAverageValueOfTaxonomyAlignedUndertakings? = null,

    @field:Valid()
    val breakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveTurnoverBased:
    EutaxonomyFinancialsAssetmanagementBreakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveTurnoverBased? = null,

    @field:Valid()
    val breakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveCapexBased:
    EutaxonomyFinancialsAssetmanagementBreakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveCapexBased? = null,

)
