// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import fs from "fs";
import { generateEutaxonomynonfinancialsFixtures } from "@e2e/fixtures/frameworks/euTaxonomyNonFinancials/EutaxonomynonfinancialsDataFixtures";
import { generateEutaxonomynonfinancialsPreparedFixtures } from "@e2e/fixtures/frameworks/euTaxonomyNonFinancials/EutaxonomynonfinancialsPreparedFixtures";
import { FAKE_FIXTURES_PER_FRAMEWORK } from "@e2e/fixtures/GenerateFakeFixtures";

/**
 * Generates and exports fake fixtures for the euTaxonomyNonFinancials framework
 */
function exportFixturesEutaxonomynonfinancials(): void {
  const companyInformationWithEutaxonomynonfinancialsData =
    generateEutaxonomynonfinancialsFixtures(FAKE_FIXTURES_PER_FRAMEWORK);
  fs.writeFileSync(
    "../testing/data/CompanyInformationWithEutaxonomynonfinancialsData.json",
    JSON.stringify(companyInformationWithEutaxonomynonfinancialsData, null, "\t"),
  );
  const preparedFixtureEutaxonomynonfinancialsDataForFinancials = generateEutaxonomynonfinancialsPreparedFixtures();
  fs.writeFileSync(
    "../testing/data/CompanyInformationWithEutaxonomynonfinancialsPreparedFixtures.json",
    JSON.stringify(preparedFixtureEutaxonomynonfinancialsDataForFinancials, null, "\t"),
  );
}

export default exportFixturesEutaxonomynonfinancials;
