package org.dataland.datalandbackend.model.enums.eutaxonomy.nonfinancials

import io.swagger.v3.oas.annotations.media.Schema

/**
 * An enum that holds the different activities related to EU taxonomy for non-financial companies
 */
@Schema(
    enumAsRef = true,
)
enum class Activity(
    val value: String,
) {
    AcquisitionAndOwnershipOfBuildings("Acquisition and ownership of buildings"),
    Afforestation("Afforestation"),
    AirTransportGroundHandlingOperations("Air transport ground handling operations"),
    AirportInfrastructure("Airport infrastructure"),
    AnaerobicDigestionOfBioWaste("Anaerobic digestion of bio-waste"),
    AnaerobicDigestionOfSewageSludge("Anaerobic digestion of sewage sludge"),
    CloseToMarketResearchDevelopmentAndInnovation("Close to market research, development and innovation"),
    CogenerationOfHeatCoolAndPowerFromBioenergy("Cogeneration of heat/cool and power from bioenergy"),
    CogenerationOfHeatCoolAndPowerFromGeothermalEnergy("Cogeneration of heat/cool and power from geothermal energy"),
    CogenerationOfHeatCoolAndPowerFromRenewableNonFossilGaseousAndLiquidFuels("Cogeneration of heat/cool and power from renewable non-fossil gaseous and liquid fuels"),
    CogenerationOfHeatCoolAndPowerFromSolarEnergy("Cogeneration of heat/cool and power from solar energy"),
    CollectionAndTransportOfHazardousWaste("Collection and transport of hazardous waste"),
    CollectionAndTransportOfNonHazardousAndHazardousWaste("Collection and transport of non-hazardous and hazardous waste"),
    CollectionAndTransportOfNonHazardousWasteInSourceSegregatedFractions("Collection and transport of non-hazardous waste in source segregated fractions"),
    CompostingOfBioWaste("Composting of bio-waste"),
    ComputerProgrammingConsultancyAndRelatedActivities("Computer programming, consultancy and related activities"),
    ConservationForestry("Conservation forestry"),
    ConservationIncludingRestorationOfHabitatsEcosystemsAndSpecies("Conservation, including restoration, of habitats, ecosystems and species"),
    ConstructionAndSafeOperationOfNewNuclearPowerPlantsForTheGenerationOfElectricityAndOrHeatIncludingForHydrogenProductionUsingBestAvailableTechnologies("Construction and safe operation of new nuclear power plants, for the generation of electricity and/or heat, including for hydrogen production, using best-available technologies"),
    ConstructionExtensionAndOperationOfWasteWaterCollectionAndTreatment("Construction, extension and operation of waste water collection and treatment"),
    ConstructionExtensionAndOperationOfWaterCollectionTreatmentAndSupplySystems("Construction, extension and operation of water collection, treatment and supply systems"),
    ConstructionOfNewBuildings("Construction of new buildings"),
    ConsultancyForPhysicalClimateRiskManagementAndAdaptation("Consultancy for physical climate risk management and adaptation"),
    CreativeArtsAndEntertainmentActivities("Creative, arts and entertainment activities"),
    DataDrivenSolutionsForGhgEmissionsReductions("Data-driven solutions for GHG emissions reductions"),
    DataProcessingHostingAndRelatedActivities("Data processing, hosting and related activities"),
    DemolitionAndWreckingOfBuildingsAndOtherStructures("Demolition and wrecking of buildings and other structures"),
    DepollutionAndDismantlingOfEndOfLifeProducts("Depollution and dismantling of end-of-life products"),
    Desalination("Desalination"),
    DistrictHeatingCoolingDistribution("District heating/cooling distribution"),
    Education("Education"),
    ElectricityGenerationFromBioenergy("Electricity generation from bioenergy"),
    ElectricityGenerationFromFossilGaseousFuels("Electricity generation from fossil gaseous fuels"),
    ElectricityGenerationFromGeothermalEnergy("Electricity generation from geothermal energy"),
    ElectricityGenerationFromHydropower("Electricity generation from hydropower"),
    ElectricityGenerationFromNuclearEnergyInExistingInstallations("Electricity generation from nuclear energy in existing installations"),
    ElectricityGenerationFromOceanEnergyTechnologies("Electricity generation from ocean energy technologies"),
    ElectricityGenerationFromRenewableNonFossilGaseousAndLiquidFuels("Electricity generation from renewable non-fossil gaseous and liquid fuels"),
    ElectricityGenerationFromWindPower("Electricity generation from wind power"),
    ElectricityGenerationUsingConcentratedSolarPowerCspTechnology("Electricity generation using concentrated solar power (CSP) technology"),
    ElectricityGenerationUsingSolarPhotovoltaicTechnology("Electricity generation using solar photovoltaic technology"),
    EmergencyServices("Emergency Services"),
    EngineeringActivitiesAndRelatedTechnicalConsultancyDedicatedToAdaptationToClimateChange("Engineering activities and related technical consultancy dedicated to adaptation to climate change"),
    FloodRiskPreventionAndProtectionInfrastructure("Flood risk prevention and protection infrastructure"),
    ForestManagement("Forest management"),
    FreightRailTransport("Freight rail transport"),
    FreightTransportServicesByRoad("Freight transport services by road"),
    HighEfficiencyCoGenerationOfHeatCoolAndPowerFromFossilGaseousFuels("High-efficiency co-generation of heat/cool and power from fossil gaseous fuels"),
    HotelsHolidayCampingGroundsAndSimilarAccommodation("Hotels, holiday, camping grounds and similar accommodation"),
    InfrastructureEnablingLowCarbonRoadTransportAndPublicTransport("Infrastructure enabling low-carbon road transport and public transport"),
    InfrastructureEnablingLowCarbonWaterTransport("Infrastructure enabling low carbon water transport"),
    InfrastructureEnablingRoadTransportAndPublicTransport("Infrastructure enabling road transport and public transport"),
    InfrastructureForPersonalMobilityCycleLogistics("Infrastructure for personal mobility, cycle logistics"),
    InfrastructureForRailTransport("Infrastructure for rail transport"),
    InfrastructureForWaterTransport("Infrastructure for water transport"),
    InlandFreightWaterTransport("Inland freight water transport"),
    InlandPassengerWaterTransport("Inland passenger water transport"),
    InstallationAndOperationOfElectricHeatPumps("Installation and operation of electric heat pumps"),
    InstallationMaintenanceAndRepairOfChargingStationsForElectricVehiclesInBuildingsAndParkingSpacesAttachedToBuildings("Installation, maintenance and repair of charging stations for electric vehicles in buildings (and parking spaces attached to buildings)"),
    InstallationMaintenanceAndRepairOfEnergyEfficiencyEquipment("Installation, maintenance and repair of energy efficiency equipment"),
    InstallationMaintenanceAndRepairOfInstrumentsAndDevicesForMeasuringRegulationAndControllingEnergyPerformanceOfBuildings("Installation, maintenance and repair of instruments and devices for measuring, regulation and controlling energy performance of buildings"),
    InstallationMaintenanceAndRepairOfRenewableEnergyTechnologies("Installation, maintenance and repair of renewable energy technologies"),
    LandfillGasCaptureAndUtilisation("Landfill gas capture and utilisation"),
    LeasingOfAircraft("Leasing of aircraft"),
    LibrariesArchivesMuseumsAndCulturalActivities("Libraries, archives, museums and cultural activities"),
    LowCarbonAirportInfrastructure("Low carbon airport infrastructure"),
    MaintenanceOfRoadsAndMotorways("Maintenance of roads and motorways"),
    ManufactureInstallationAndAssociatedServicesForLeakageControlTechnologiesEnablingLeakageReductionAndPreventionInWaterSupplySystems("Manufacture, installation and associated services for leakage control technologies enabling leakage reduction and prevention in water supply systems"),
    ManufactureInstallationAndServicingOfHighMediumAndLowVoltageElectricalEquipmentForElectricalTransmissionAndDistributionThatResultInOrEnableASubstantialContributionToClimateChangeMitigation("Manufacture, installation, and servicing of high, medium and low voltage electrical equipment for electrical transmission and distribution that result in or enable a substantial contribution to climate change mitigation"),
    ManufactureOfActivePharmaceuticalIngredientsApiOrActiveSubstances("Manufacture of active pharmaceutical ingredients (API) or active substances"),
    ManufactureOfAluminium("Manufacture of aluminium"),
    ManufactureOfAnhydrousAmmonia("Manufacture of anhydrous ammonia"),
    ManufactureOfAutomotiveAndMobilityComponents("Manufacture of automotive and mobility components"),
    ManufactureOfBatteries("Manufacture of batteries"),
    ManufactureOfBiogasAndBiofuelsForUseInTransportAndOfBioliquids("Manufacture of biogas and biofuels for use in transport and of bioliquids"),
    ManufactureOfCarbonBlack("Manufacture of carbon black"),
    ManufactureOfCement("Manufacture of cement"),
    ManufactureOfChlorine("Manufacture of chlorine"),
    ManufactureOfElectricalAndElectronicEquipment("Manufacture of electrical and electronic equipment"),
    ManufactureOfEnergyEfficiencyEquipmentForBuildings("Manufacture of energy efficiency equipment for buildings"),
    ManufactureOfEquipmentForTheProductionAndUseOfHydrogen("Manufacture of equipment for the production and use of hydrogen"),
    ManufactureOfHydrogen("Manufacture of hydrogen"),
    ManufactureOfIronAndSteel("Manufacture of iron and steel"),
    ManufactureOfLowCarbonTechnologiesForTransport("Manufacture of low carbon technologies for transport"),
    ManufactureOfMedicinalProducts("Manufacture of medicinal products"),
    ManufactureOfNitricAcid("Manufacture of nitric acid"),
    ManufactureOfOrganicBasicChemicals("Manufacture of organic basic chemicals"),
    ManufactureOfOtherLowCarbonTechnologies("Manufacture of other low carbon technologies"),
    ManufactureOfPlasticPackagingGoods("Manufacture of plastic packaging goods"),
    ManufactureOfPlasticsInPrimaryForm("Manufacture of plastics in primary form"),
    ManufactureOfRailRollingStockConstituents("Manufacture of rail rolling stock constituents"),
    ManufactureOfRenewableEnergyTechnologies("Manufacture of renewable energy technologies"),
    ManufactureOfSodaAsh("Manufacture of soda ash"),
    ManufacturingOfAircraft("Manufacturing of aircraft"),
    MarketplaceForTheTradeOfSecondHandGoodsForReuse("Marketplace for the trade of second-hand goods for reuse"),
    MaterialRecoveryFromNonHazardousWaste("Material recovery from non-hazardous waste"),
    MotionPictureVideoAndTelevisionProgrammeProductionSoundRecordingAndMusicPublishingActivities("Motion picture, video and television programme production, sound recording and music publishing activities"),
    NatureBasedSolutionsForFloodAndDroughtRiskPreventionAndProtection("Nature-based solutions for flood and drought risk prevention and protection"),
    NonLifeInsuranceUnderwritingOfClimateRelatedPerils("Non-life insurance: underwriting of climate-related perils"),
    OperationOfPersonalMobilityDevicesCycleLogistics("Operation of personal mobility devices, cycle logistics"),
    PassengerAndFreightAirTransport("Passenger and freight air transport"),
    PassengerInterurbanRailTransport("Passenger interurban rail transport"),
    PhosphorusRecoveryFromWasteWater("Phosphorus recovery from waste water"),
    PreCommercialStagesOfAdvancedTechnologiesToProduceEnergyFromNuclearProcessesWithMinimalWasteFromTheFuelCycle("Pre-commercial stages of advanced technologies to produce energy from nuclear processes with minimal waste from the fuel cycle"),
    PreparationForReUseOfEndOfLifeProductsAndProductComponents("Preparation for re-use of end-of-life products and product components"),
    ProductAsAServiceAndOtherCircularUseAndResultOrientedServiceModels("Product-as-a-service and other circular use- and result-oriented service models"),
    ProductionOfAlternativeWaterResourcesForPurposesOtherThanHumanConsumption("Production of alternative water resources for purposes other than human consumption"),
    ProductionOfHeatCoolFromBioenergy("Production of heat/cool from bioenergy"),
    ProductionOfHeatCoolFromFossilGaseousFuelsInAnEfficientDistrictHeatingAndCoolingSystem("Production of heat/cool from fossil gaseous fuels in an efficient district heating and cooling system"),
    ProductionOfHeatCoolFromGeothermalEnergy("Production of heat/cool from geothermal energy"),
    ProductionOfHeatCoolFromRenewableNonFossilGaseousAndLiquidFuels("Production of heat/cool from renewable non-fossil gaseous and liquid fuels"),
    ProductionOfHeatCoolFromSolarThermalHeating("Production of heat/cool from solar thermal heating"),
    ProductionOfHeatCoolUsingWasteHeat("Production of heat/cool using waste heat"),
    ProfessionalServicesRelatedToEnergyPerformanceOfBuildings("Professional services related to energy performance of buildings"),
    ProgrammingAndBroadcastingActivities("Programming and broadcasting activities"),
    ProvisionOfItOtDataDrivenSolutions("Provision of IT/OT data-driven solutions"),
    ProvisionOfItOtDataDrivenSolutionsForLeakageReduction("Provision of IT/OT data-driven solutions for leakage reduction"),
    RecoveryOfBioWasteByAnaerobicDigestionOrComposting("Recovery of bio-waste by anaerobic digestion or composting"),
    RehabilitationAndRestorationOfForestsIncludingReforestationAndNaturalForestRegenerationAfterAnExtremeEvent("Rehabilitation and restoration of forests, including reforestation and natural forest regeneration after an extreme event"),
    Reinsurance("Reinsurance"),
    RemediationOfContaminatedSitesAndAreas("Remediation of contaminated sites and areas"),
    RemediationOfLegallyNonConformingLandfillsAndAbandonedOrIllegalWasteDumps("Remediation of legally non-conforming landfills and abandoned or illegal waste dumps"),
    RenewalOfWasteWaterCollectionAndTreatment("Renewal of waste water collection and treatment"),
    RenewalOfWaterCollectionTreatmentAndSupplySystems("Renewal of water collection, treatment and supply systems"),
    RenovationOfExistingBuildings("Renovation of existing buildings"),
    RepairRefurbishmentAndRemanufacturing("Repair, refurbishment and remanufacturing"),
    ResearchDevelopmentAndInnovationForDirectAirCaptureOfCo2("Research, development and innovation for direct air capture of CO2"),
    ResidentialCareActivities("Residential care activities"),
    RestorationOfWetlands("Restoration of wetlands"),
    RetrofittingOfInlandWaterPassengerAndFreightTransport("Retrofitting of inland water passenger and freight transport"),
    RetrofittingOfSeaAndCoastalFreightAndPassengerWaterTransport("Retrofitting of sea and coastal freight and passenger water transport"),
    SaleOfSecondHandGoods("Sale of second-hand goods"),
    SaleOfSpareParts("Sale of spare parts"),
    SeaAndCoastalFreightWaterTransportVesselsForPortOperationsAndAuxiliaryActivities("Sea and coastal freight water transport, vessels for port operations and auxiliary activities"),
    SeaAndCoastalPassengerWaterTransport("Sea and coastal passenger water transport"),
    SoftwareEnablingPhysicalClimateRiskManagementAndAdaptation("Software enabling physical climate risk management and adaptation"),
    SortingAndMaterialRecoveryOfNonHazardousWaste("Sorting and material recovery of non-hazardous waste"),
    StorageOfElectricity("Storage of electricity"),
    StorageOfHydrogen("Storage of hydrogen"),
    StorageOfThermalEnergy("Storage of thermal energy"),
    SustainableUrbanDrainageSystemsSuds("Sustainable urban drainage systems (SUDS)"),
    TransmissionAndDistributionNetworksForRenewableAndLowCarbonGases("Transmission and distribution networks for renewable and low-carbon gases"),
    TransmissionAndDistributionOfElectricity("Transmission and distribution of electricity"),
    TransportByMotorbikesPassengerCarsAndLightCommercialVehicles("Transport by motorbikes, passenger cars and light commercial vehicles"),
    TransportOfCo2("Transport of CO2"),
    TreatmentOfHazardousWaste("Treatment of hazardous waste"),
    UndergroundPermanentGeologicalStorageOfCo2("Underground permanent geological storage of CO2"),
    UrbanAndSuburbanTransportRoadPassengerTransport("Urban and suburban transport, road passenger transport"),
    UrbanWasteWaterTreatment("Urban Waste Water Treatment"),
    UseOfConcreteInCivilEngineering("Use of concrete in civil engineering"),
    WaterSupply("Water supply"),
}
