package org.dataland.datalandbackend.model.enums.eutaxonomy.nonfinancials

import io.swagger.v3.oas.annotations.media.Schema

/**
 * An enum that holds the different activities related to EU taxonomy for non-financial companies
 */
@Schema(
    enumAsRef = true,
)
enum class Activity(val value: String) {
    Afforestation("Afforestation"),
    RehabilitationAndRestorationOfForestsIncludingReforestationAndNaturalForestRegenerationAfterAnExtremeEvent("Rehabilitation and restoration of forests, including reforestation and natural forest regeneration after an extreme event"),
    ForestManagement("Forest management"),
    ConservationForestry("Conservation forestry"),
    RestorationOfWetlands("Restoration of wetlands"),
    ManufactureOfRenewableEnergyTechnologies("Manufacture of renewable energy technologies"),
    ManufactureOfEquipmentForTheProductionAndUseOfHydrogen("Manufacture of equipment for the production and use of hydrogen"),
    ManufactureOfLowCarbonTechnologiesForTransport("Manufacture of low carbon technologies for transport"),
    ManufactureOfBatteries("Manufacture of batteries"),
    ManufactureOfEnergyEfficiencyEquipmentForBuildings("Manufacture of energy efficiency equipment for buildings"),
    ManufactureOfOtherLowCarbonTechnologies("Manufacture of other low carbon technologies"),
    ManufactureOfCement("Manufacture of cement"),
    ManufactureOfAluminium("Manufacture of aluminium"),
    ManufactureOfIronAndSteel("Manufacture of iron and steel"),
    ManufactureOfHydrogen("Manufacture of hydrogen"),
    ManufactureOfCarbonBlack("Manufacture of carbon black"),
    ManufactureOfSodaAsh("Manufacture of soda ash"),
    ManufactureOfChlorine("Manufacture of chlorine"),
    ManufactureOfOrganicBasicChemicals("Manufacture of organic basic chemicals"),
    ManufactureOfAnhydrousAmmonia("Manufacture of anhydrous ammonia"),
    ManufactureOfNitricAcid("Manufacture of nitric acid"),
    ManufactureOfPlasticsInPrimaryForm("Manufacture of plastics in primary form"),
    ManufactureOfAutomotiveAndMobilityComponents("Manufacture of automotive and mobility components"),
    ManufactureOfRailRollingStockConstituents("Manufacture of rail rolling stock constituents"),
    ManufactureInstallationAndServicingOfHighMediumAndLowVoltageElectricalEquipmentForElectricalTransmissionAndDistributionThatResultInOrEnableASubstantialContributionToClimateChangeMitigation("Manufacture, installation, and servicing of high, medium and low voltage electrical equipment for electrical transmission and distribution that result in or enable a substantial contribution to climate change mitigation"),
    ManufacturingOfAircraft("Manufacturing of aircraft"),
    ElectricityGenerationUsingSolarPhotovoltaicTechnology("Electricity generation using solar photovoltaic technology"),
    ElectricityGenerationUsingConcentratedSolarPowerCspTechnology("Electricity generation using concentrated solar power (CSP) technology"),
    ElectricityGenerationFromWindPower("Electricity generation from wind power"),
    ElectricityGenerationFromOceanEnergyTechnologies("Electricity generation from ocean energy technologies"),
    ElectricityGenerationFromHydropower("Electricity generation from hydropower"),
    ElectricityGenerationFromGeothermalEnergy("Electricity generation from geothermal energy"),
    ElectricityGenerationFromRenewableNonFossilGaseousAndLiquidFuels("Electricity generation from renewable non-fossil gaseous and liquid fuels"),
    ElectricityGenerationFromBioenergy("Electricity generation from bioenergy"),
    TransmissionAndDistributionOfElectricity("Transmission and distribution of electricity"),
    StorageOfElectricity("Storage of electricity"),
    StorageOfThermalEnergy("Storage of thermal energy"),
    StorageOfHydrogen("Storage of hydrogen"),
    ManufactureOfBiogasAndBiofuelsForUseInTransportAndOfBioliquids("Manufacture of biogas and biofuels for use in transport and of bioliquids"),
    TransmissionAndDistributionNetworksForRenewableAndLowCarbonGases("Transmission and distribution networks for renewable and low-carbon gases"),
    DistrictHeatingCoolingDistribution("District heating/cooling distribution"),
    InstallationAndOperationOfElectricHeatPumps("Installation and operation of electric heat pumps"),
    CogenerationOfHeatCoolAndPowerFromSolarEnergy("Cogeneration of heat/cool and power from solar energy"),
    CogenerationOfHeatCoolAndPowerFromGeothermalEnergy("Cogeneration of heat/cool and power from geothermal energy"),
    CogenerationOfHeatCoolAndPowerFromRenewableNonFossilGaseousAndLiquidFuels("Cogeneration of heat/cool and power from renewable non-fossil gaseous and liquid fuels"),
    CogenerationOfHeatCoolAndPowerFromBioenergy("Cogeneration of heat/cool and power from bioenergy"),
    ProductionOfHeatCoolFromSolarThermalHeating("Production of heat/cool from solar thermal heating"),
    ProductionOfHeatCoolFromGeothermalEnergy("Production of heat/cool from geothermal energy"),
    ProductionOfHeatCoolFromRenewableNonFossilGaseousAndLiquidFuels("Production of heat/cool from renewable non-fossil gaseous and liquid fuels"),
    ProductionOfHeatCoolFromBioenergy("Production of heat/cool from bioenergy"),
    ProductionOfHeatCoolUsingWasteHeat("Production of heat/cool using waste heat"),
    PreCommercialStagesOfAdvancedTechnologiesToProduceEnergyFromNuclearProcessesWithMinimalWasteFromTheFuelCycle("Pre-commercial stages of advanced technologies to produce energy from nuclear processes with minimal waste from the fuel cycle"),
    ConstructionAndSafeOperationOfNewNuclearPowerPlantsForTheGenerationOfElectricityAndOrHeatIncludingForHydrogenProductionUsingBestAvailableTechnologies("Construction and safe operation of new nuclear power plants, for the generation of electricity and/or heat, including for hydrogen production, using best-available technologies"),
    ElectricityGenerationFromNuclearEnergyInExistingInstallations("Electricity generation from nuclear energy in existing installations"),
    ElectricityGenerationFromFossilGaseousFuels("Electricity generation from fossil gaseous fuels"),
    HighEfficiencyCoGenerationOfHeatCoolAndPowerFromFossilGaseousFuels("High-efficiency co-generation of heat/cool and power from fossil gaseous fuels"),
    ProductionOfHeatCoolFromFossilGaseousFuelsInAnEfficientDistrictHeatingAndCoolingSystem("Production of heat/cool from fossil gaseous fuels in an efficient district heating and cooling system"),
    ConstructionExtensionAndOperationOfWaterCollectionTreatmentAndSupplySystems("Construction, extension and operation of water collection, treatment and supply systems"),
    RenewalOfWaterCollectionTreatmentAndSupplySystems("Renewal of water collection, treatment and supply systems"),
    ConstructionExtensionAndOperationOfWasteWaterCollectionAndTreatment("Construction, extension and operation of waste water collection and treatment"),
    RenewalOfWasteWaterCollectionAndTreatment("Renewal of waste water collection and treatment"),
    CollectionAndTransportOfNonHazardousWasteInSourceSegregatedFractions("Collection and transport of non-hazardous waste in source segregated fractions"),
    AnaerobicDigestionOfSewageSludge("Anaerobic digestion of sewage sludge"),
    AnaerobicDigestionOfBioWaste("Anaerobic digestion of bio-waste"),
    CompostingOfBioWaste("Composting of bio-waste"),
    MaterialRecoveryFromNonHazardousWaste("Material recovery from non-hazardous waste"),
    LandfillGasCaptureAndUtilisation("Landfill gas capture and utilisation"),
    TransportOfCo2("Transport of CO2"),
    UndergroundPermanentGeologicalStorageOfCo2("Underground permanent geological storage of CO2"),
    PassengerInterurbanRailTransport("Passenger interurban rail transport"),
    FreightRailTransport("Freight rail transport"),
    UrbanAndSuburbanTransportRoadPassengerTransport("Urban and suburban transport, road passenger transport"),
    OperationOfPersonalMobilityDevicesCycleLogistics("Operation of personal mobility devices, cycle logistics"),
    TransportByMotorbikesPassengerCarsAndLightCommercialVehicles("Transport by motorbikes, passenger cars and light commercial vehicles"),
    FreightTransportServicesByRoad("Freight transport services by road"),
    InlandPassengerWaterTransport("Inland passenger water transport"),
    InlandFreightWaterTransport("Inland freight water transport"),
    RetrofittingOfInlandWaterPassengerAndFreightTransport("Retrofitting of inland water passenger and freight transport"),
    SeaAndCoastalFreightWaterTransportVesselsForPortOperationsAndAuxiliaryActivities("Sea and coastal freight water transport, vessels for port operations and auxiliary activities"),
    SeaAndCoastalPassengerWaterTransport("Sea and coastal passenger water transport"),
    RetrofittingOfSeaAndCoastalFreightAndPassengerWaterTransport("Retrofitting of sea and coastal freight and passenger water transport"),
    InfrastructureForPersonalMobilityCycleLogistics("Infrastructure for personal mobility, cycle logistics"),
    InfrastructureForRailTransport("Infrastructure for rail transport"),
    InfrastructureEnablingLowCarbonRoadTransportAndPublicTransport("Infrastructure enabling low-carbon road transport and public transport"),
    InfrastructureEnablingLowCarbonWaterTransport("Infrastructure enabling low carbon water transport"),
    LowCarbonAirportInfrastructure("Low carbon airport infrastructure"),
    LeasingOfAircraft("Leasing of aircraft"),
    PassengerAndFreightAirTransport("Passenger and freight air transport"),
    AirTransportGroundHandlingOperations("Air transport ground handling operations"),
    ConstructionOfNewBuildings("Construction of new buildings"),
    RenovationOfExistingBuildings("Renovation of existing buildings"),
    InstallationMaintenanceAndRepairOfEnergyEfficiencyEquipment("Installation, maintenance and repair of energy efficiency equipment"),
    InstallationMaintenanceAndRepairOfChargingStationsForElectricVehiclesInBuildingsAndParkingSpacesAttachedToBuildings("Installation, maintenance and repair of charging stations for electric vehicles in buildings (and parking spaces attached to buildings)"),
    InstallationMaintenanceAndRepairOfInstrumentsAndDevicesForMeasuringRegulationAndControllingEnergyPerformanceOfBuildings("Installation, maintenance and repair of instruments and devices for measuring, regulation and controlling energy performance of buildings"),
    InstallationMaintenanceAndRepairOfRenewableEnergyTechnologies("Installation, maintenance and repair of renewable energy technologies"),
    AcquisitionAndOwnershipOfBuildings("Acquisition and ownership of buildings"),
    DataProcessingHostingAndRelatedActivities("Data processing, hosting and related activities"),
    DataDrivenSolutionsForGhgEmissionsReductions("Data-driven solutions for GHG emissions reductions"),
    CloseToMarketResearchDevelopmentAndInnovation("Close to market research, development and innovation"),
    ResearchDevelopmentAndInnovationForDirectAirCaptureOfCo2("Research, development and innovation for direct air capture of CO2"),
    ProfessionalServicesRelatedToEnergyPerformanceOfBuildings("Professional services related to energy performance of buildings"),
    Desalination("Desalination"),
    InfrastructureEnablingRoadTransportAndPublicTransport("Infrastructure enabling road transport and public transport"),
    InfrastructureForWaterTransport("Infrastructure for water transport"),
    AirportInfrastructure("Airport infrastructure"),
    ComputerProgrammingConsultancyAndRelatedActivities("Computer programming, consultancy and related activities"),
    ProgrammingAndBroadcastingActivities("Programming and broadcasting activities"),
    SoftwareEnablingPhysicalClimateRiskManagementAndAdaptation("Software enabling physical climate risk management and adaptation"),
    EngineeringActivitiesAndRelatedTechnicalConsultancyDedicatedToAdaptationToClimateChange("Engineering activities and related technical consultancy dedicated to adaptation to climate change"),
    ConsultancyForPhysicalClimateRiskManagementAndAdaptation("Consultancy for physical climate risk management and adaptation"),
    NonLifeInsuranceUnderwritingOfClimateRelatedPerils("Non-life insurance: underwriting of climate-related perils"),
    Reinsurance("Reinsurance"),
    Education("Education"),
    ResidentialCareActivities("Residential care activities"),
    CreativeArtsAndEntertainmentActivities("Creative, arts and entertainment activities"),
    LibrariesArchivesMuseumsAndCulturalActivities("Libraries, archives, museums and cultural activities"),
    MotionPictureVideoAndTelevisionProgrammeProductionSoundRecordingAndMusicPublishingActivities("Motion picture, video and television programme production, sound recording and music publishing activities"),
    EmergencyServices("Emergency Services"),
    FloodRiskPreventionAndProtectionInfrastructure("Flood risk prevention and protection infrastructure"),
    ManufactureInstallationAndAssociatedServicesForLeakageControlTechnologiesEnablingLeakageReductionAndPreventionInWaterSupplySystems("Manufacture, installation and associated services for leakage control technologies enabling leakage reduction and prevention in water supply systems"),
    WaterSupply("Water supply"),
    UrbanWasteWaterTreatment("Urban Waste Water Treatment"),
    SustainableUrbanDrainageSystemsSuds("Sustainable urban drainage systems (SUDS)"),
    NatureBasedSolutionsForFloodAndDroughtRiskPreventionAndProtection("Nature-based solutions for flood and drought risk prevention and protection"),
    ProvisionOfItOtDataDrivenSolutionsForLeakageReduction("Provision of IT/OT data-driven solutions for leakage reduction"),
    ManufactureOfPlasticPackagingGoods("Manufacture of plastic packaging goods"),
    ManufactureOfElectricalAndElectronicEquipment("Manufacture of electrical and electronic equipment"),
    PhosphorusRecoveryFromWasteWater("Phosphorus recovery from waste water"),
    ProductionOfAlternativeWaterResourcesForPurposesOtherThanHumanConsumption("Production of alternative water resources for purposes other than human consumption"),
    CollectionAndTransportOfNonHazardousAndHazardousWaste("Collection and transport of non-hazardous and hazardous waste"),
    TreatmentOfHazardousWaste("Treatment of hazardous waste"),
    RecoveryOfBioWasteByAnaerobicDigestionOrComposting("Recovery of bio-waste by anaerobic digestion or composting"),
    DepollutionAndDismantlingOfEndOfLifeProducts("Depollution and dismantling of end-of-life products"),
    SortingAndMaterialRecoveryOfNonHazardousWaste("Sorting and material recovery of non-hazardous waste"),
    DemolitionAndWreckingOfBuildingsAndOtherStructures("Demolition and wrecking of buildings and other structures"),
    MaintenanceOfRoadsAndMotorways("Maintenance of roads and motorways"),
    UseOfConcreteInCivilEngineering("Use of concrete in civil engineering"),
    ProvisionOfItOtDataDrivenSolutions("Provision of IT/OT data-driven solutions"),
    RepairRefurbishmentAndRemanufacturing("Repair, refurbishment and remanufacturing"),
    SaleOfSpareParts("Sale of spare parts"),
    PreparationForReUseOfEndOfLifeProductsAndProductComponents("Preparation for re-use of end-of-life products and product components"),
    SaleOfSecondHandGoods("Sale of second-hand goods"),
    ProductAsAServiceAndOtherCircularUseAndResultOrientedServiceModels("Product-as-a-service and other circular use- and result-oriented service models"),
    MarketplaceForTheTradeOfSecondHandGoodsForReuse("Marketplace for the trade of second-hand goods for reuse"),
    ManufactureOfActivePharmaceuticalIngredientsApiOrActiveSubstances("Manufacture of active pharmaceutical ingredients (API) or active substances"),
    ManufactureOfMedicinalProducts("Manufacture of medicinal products"),
    CollectionAndTransportOfHazardousWaste("Collection and transport of hazardous waste"),
    RemediationOfLegallyNonConformingLandfillsAndAbandonedOrIllegalWasteDumps("Remediation of legally non-conforming landfills and abandoned or illegal waste dumps"),
    RemediationOfContaminatedSitesAndAreas("Remediation of contaminated sites and areas"),
    ConservationIncludingRestorationOfHabitats_1_Ecosystems_2_AndSpecies("Conservation, including restoration, of habitats[1], ecosystems[2] and species"),
    HotelsHolidayCampingGroundsAndSimilarAccommodation("Hotels, holiday, camping grounds and similar accommodation"),
}
