// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.creditInstitution.general

import java.math.BigDecimal

/**
 * The data-model for the General section
 */
data class EuTaxonomyFinancialsCreditinstitutionGeneral(
    val tradingPortfolio: BigDecimal? = null,

    val onDemandInterbankLoans: BigDecimal? = null,

    val tradingPortfolioAndOnDemandInterbankLoans: BigDecimal? = null,

)
