import { type Field } from "@/utils/GenericFrameworkTypes";
import { type ExtendedDataPointBigDecimal } from "@clients/backend";
import { dataPointValueGetterFactory } from "@/components/resources/dataTable/conversion/DataPointValueGetterFactory";
import {
  MLDTDisplayObjectForEmptyString,
  MLDTDisplayComponentName,
  type MLDTDisplayObject,
} from "@/components/resources/dataTable/MultiLayerDataTableCellDisplayer";
import {uploadDocuments} from "../../../../../sharedUtils/components/UploadDocuments";
import {TEST_PDF_FILE_NAME} from "../../../../../sharedUtils/ConstantsForPdfs";
describe("Unit test for the DataPointValueGetterFactory", () => {
  // TODO rewrite test based on the new DataPointValueGetterFactory
  describe("Tests when the unit is pre-determined in the data model", () => {
    const field: Field = {
      name: "emissionsToWater",
      label: "Emissions To Water",
      description: "Tonnes of Emissions To Water generated by the company.",
      unit: "Tonnes",
      component: "DataPointFormField",
      evidenceDesired: true,
      required: false,
      showIf: (): boolean => true,
    };

    it("An empty string should be displayed if the data point is undefined", () => {
      const dataset = { data: undefined };
      const value = dataPointValueGetterFactory("data", field)(dataset);
      expect(value).to.deep.equal(MLDTDisplayObjectForEmptyString);
    });

    it("An empty string should be displayed if the data points value is undefined or null", () => {
      const datapoint: ExtendedDataPointBigDecimal = {
        value: undefined,
        quality: "NA",
      };
      const dataset = { data: datapoint };
      const value = dataPointValueGetterFactory("data", field)(dataset);
      expect(value).to.deep.equal(MLDTDisplayObjectForEmptyString);
    });

    it("The value should be displayed with a static unit suffix if set", () => {
      const datapoint: ExtendedDataPointBigDecimal = {
        value: 123,
        quality: "NA",
      };
      const dataset = { data: datapoint };
      const value = dataPointValueGetterFactory("data", field)(dataset);
      expect(value).to.deep.equal(<MLDTDisplayObject<MLDTDisplayComponentName.StringDisplayComponent>>{
        displayComponentName: MLDTDisplayComponentName.StringDisplayComponent,
        displayValue: "123 Tonnes",
      });
    });
  });

  describe("Tests when the unit is (not?) pre-determined in the data model", () => {
    const field: Field = {
      name: "emissionsToWater",
      label: "Emissions To Water",
      description: "Tonnes of Emissions To Water generated by the company.",
      component: "DataPointFormField",
      options: [
        {
          label: "Unit-A",
          value: "A",
        },
        {
          label: "Unit-B",
          value: "B",
        },
      ],
      evidenceDesired: true,
      required: false,
      showIf: (): boolean => true,
    };

    it("The value should be displayed with no unit suffix if no unit is provided", () => {
      const datapoint: ExtendedDataPointBigDecimal = {
        value: 123,
        quality: "NA",
      };
      const dataset = { data: datapoint };
      const value = dataPointValueGetterFactory("data", field)(dataset);
      expect(value).to.deep.equal(<MLDTDisplayObject<MLDTDisplayComponentName.StringDisplayComponent>>{
        displayComponentName: MLDTDisplayComponentName.StringDisplayComponent,
        displayValue: "123",
      });
    });
  });

  describe("Tests when dealing with currency", () => {
    // TODO write test
  });

  describe("Tests when dealing with document references", () => {
    const field: Field = {
      name: "emissionsToWater",
      label: "Emissions To Water",
      description: "Tonnes of Emissions To Water generated by the company.",
      unit: "Tonnes",
      component: "DataPointFormField",
      evidenceDesired: true,
      required: false,
      showIf: (): boolean => true,
    };

    it.only("error message shown when selected document name doesn't exist", () => {
      const datapoint: ExtendedDataPointBigDecimal = {
        value: 123,
        quality: "NA",
        dataSource: {
          page: 62,
          fileName: null,
          fileReference: "50a36c418baffd520bb92d84664f06f9732a21f4e2e5ecee6d9136f16e7e0b63",
          tagName: "relationships",
        },
      };
      const dataset = { data: datapoint };
      try {
        dataPointValueGetterFactory("data", field)(dataset);
        expect.fail("Expected an error to be thrown.");
      } catch (error) {
        expect(error.message).to.equal("There is no document with name NOT PROVIDED referenced in this dataset");
      }
    });

    //can be integrated into other tests
    it("error message shown when selected document name doesn't exist", () => {
      const datapoint: ExtendedDataPointBigDecimal = {
        value: 123,
        quality: "NA",
        dataSource: {
          page: 6,
          fileName: TEST_PDF_FILE_NAME,
          fileReference: "50a36c418baffd520bb92d84664f06f9732a21f4e2e5ecee6d9136f16e7e0b63",
          tagName: "relationships",
        },
      };
      // TODO mount environment where documents can be uploaded
      uploadDocuments.selectFile(TEST_PDF_FILE_NAME);
      const dataset = { data: datapoint };
      const value = dataPointValueGetterFactory("data", field)(dataset);
      expect(value).to.deep.equal(<MLDTDisplayObject<MLDTDisplayComponentName.DataPointDisplayComponent>>{
        displayComponentName: MLDTDisplayComponentName.DataPointDisplayComponent,
        displayValue: {
          value: 123,
          dataSource: {
            page: 6,
            fileName: TEST_PDF_FILE_NAME,
            fileReference: "50a36c418baffd520bb92d84664f06f9732a21f4e2e5ecee6d9136f16e7e0b63",
            tagName: "relationships",
          },
        },
      });
    });
  });
});
