// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.gdv.model.soziales

import org.dataland.datalandbackend.frameworks.gdv.model.soziales.audit.GdvSozialesAudit
import org.dataland.datalandbackend.frameworks.gdv.model.soziales.einkommensgleichheit.GdvSozialesEinkommensgleichheit
import org.dataland.datalandbackend.frameworks.gdv.model.soziales.geschlechterdiversitaet.GdvSozialesGeschlechterdiversitaet
import org.dataland.datalandbackend.frameworks.gdv.model.soziales.sicherheitUndWeiterbildung.GdvSozialesSicherheitUndWeiterbildung
import org.dataland.datalandbackend.frameworks.gdv.model.soziales.unternehmensstrukturaenderungen.GdvSozialesUnternehmensstrukturaenderungen

/**
 * The data-model for the Soziales section
 */
data class GdvSoziales(
    val unternehmensstrukturaenderungen: GdvSozialesUnternehmensstrukturaenderungen?,
    val sicherheitUndWeiterbildung: GdvSozialesSicherheitUndWeiterbildung?,
    val einkommensgleichheit: GdvSozialesEinkommensgleichheit?,
    val geschlechterdiversitaet: GdvSozialesGeschlechterdiversitaet?,
    val audit: GdvSozialesAudit?,
)
