// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.allgemein.generelleEsgStrategie

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.BaseDataPoint
import org.dataland.datalandbackend.model.enums.commons.YesNo
import org.dataland.datalandbackend.validator.MinimumValue
import java.math.BigDecimal

/**
 * The data-model for the GenerelleEsgStrategie section
 */
@Suppress("MaxLineLength")
data class EsgDatenkatalogAllgemeinGenerelleEsgStrategie(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Verfügt das Unternehmen über eine Nachhaltigkeitsstrategie?""",
        example = """ "Yes"  """,
    )
    val nachhaltigkeitsstrategieVorhanden: YesNo? = null,
    @field:Valid()
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte hängen Sie Ihre Nachhaltigkeitsstrategie an. Nachhaltigkeit in diesem Sinne umfasst die Themen Umwelt (E), Soziales (S) und Unternehmensführung (G). Sie können mehrere Dokumente anhängen und pro Dokument eine Beschreibung angeben.""",
        example = """[
						{
							"value": "lifetime value",
							"dataSource": {
								"fileName": "Certification",
								"fileReference": "1902e40099c913ecf3715388cb2d9f7f84e6f02a19563db6930adb7b6cf22868"
							}
						},
						{
							"value": "technologies",
							"dataSource": {
								"fileName": "Policy",
								"fileReference": "04c4e6cd07eeae270635dd909f58b09b2104ea5e92ec22a80b6e7ba1d0b75dd0"
							}
						}
					] """,
    )
    val dokumenteZurNachhaltigkeitsstrategie: List<BaseDataPoint<String>>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Werden spezielle Ziele/Maßnahmen ergriffen, um das 1,5 °C Ziel zu erreichen?""",
        example = """ "Yes"  """,
    )
    val massnahmenZurErreichungDes15GradCelsiusZiels: YesNo? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Skizzieren Sie spezielle Ziele / Maßnahmen, um das 1,5 °C Ziel zu erreichen.""",
        example = """ "This is some free text"  """,
    )
    val skizzierungVonMassnahmenZurErreichungDes15GradCelsiusZiels: String? = null,
    @field:MinimumValue(minimumValue = 0)
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bezüglich der angegebenen Maßnahmen: Bitte die zugewiesenen Budgets bis zum Jahr 2030 angeben.""",
        example = """100.5 """,
    )
    val zugewieseneBudgetsBis2030: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bezüglich der angegebenen Maßnahmen: Bitte die zugewiesenen Budgets ab dem Jahr 2031 angeben.""",
        example = """100.5 """,
    )
    val zugewieseneBudgetsAb2031: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bezüglich der angegebenen Maßnahmen: Bitte den erwarteten Finanzierungsbedarf bis zum Jahr 2030 angeben.""",
        example = """100.5 """,
    )
    val erwarteterFinanzierungsbedarfBis2030: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bezüglich der angegebenen Maßnahmen: Bitte den erwarteten Finanzierungsbedarf ab dem Jahr 2031 angeben.""",
        example = """100.5 """,
    )
    val erwarteterFinanzierungsbedarfAb2031: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bezüglich der angegebenen Maßnahmen: Bitte die geplanten Vollzeitäquivalente bis zum Jahr 2030 angeben.""",
        example = """100.5 """,
    )
    val geplanteVollzeitaequivalenteBis2023: BigDecimal? = null,
    @field:MinimumValue(minimumValue = 0)
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bezüglich der angegebenen Maßnahmen: Bitte die geplanten Vollzeitäquivalente ab dem Jahr 2031 angeben.""",
        example = """100.5 """,
    )
    val geplanteVollzeitaequivalenteAb2031: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche grundsätzlichen Chancen oder Hindernisse bestehen für das Unternehmen bei der Berücksichtigung von ESG-Belangen?""",
        example = """ "This is some free text"  """,
    )
    val chancenOderHindernisse: String? = null,
)
