// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials202673.model.assetManagement

import jakarta.validation.Valid
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials202673.model.assetManagement.assetUnderManagement
    .EutaxonomyFinancials202673AssetmanagementAssetUnderManagement
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials202673.model.assetManagement
    .breakdownOfTheNumeratorOfTheKpiCapexBased
    .EutaxonomyFinancials202673AssetmanagementBreakdownOfTheNumeratorOfTheKpiCapexBased
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials202673.model.assetManagement
    .breakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveCapexBased
    .EutaxonomyFinancials202673AssetmanagementBreakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveCapexBased
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials202673.model.assetManagement
    .breakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveTurnoverBased
    .EutaxonomyFinancials202673AssetmanagementBreakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveTurnoverBased
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials202673.model.assetManagement
    .breakdownOfTheNumeratorOfTheKpiTurnoverBased
    .EutaxonomyFinancials202673AssetmanagementBreakdownOfTheNumeratorOfTheKpiTurnoverBased

/**
 * The QA-model for the AssetManagement section
 */
@Suppress("MaxLineLength")
data class EutaxonomyFinancials202673AssetManagement(
    @field:Valid()
    val assetUnderManagement: EutaxonomyFinancials202673AssetmanagementAssetUnderManagement? = null,
    @field:Valid()
    val breakdownOfTheNumeratorOfTheKpiTurnoverBased:
        EutaxonomyFinancials202673AssetmanagementBreakdownOfTheNumeratorOfTheKpiTurnoverBased? = null,
    @field:Valid()
    val breakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveTurnoverBased:
        EutaxonomyFinancials202673AssetmanagementBreakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveTurnoverBased? = null,
    @field:Valid()
    val breakdownOfTheNumeratorOfTheKpiCapexBased:
        EutaxonomyFinancials202673AssetmanagementBreakdownOfTheNumeratorOfTheKpiCapexBased? = null,
    @field:Valid()
    val breakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveCapexBased:
        EutaxonomyFinancials202673AssetmanagementBreakdownOfTheNumeratorOfTheKpiPerEnvironmentalObjectiveCapexBased? = null,
)
