// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.umwelt.risikenUndMassnahmenKreislaufwirtschaft

import io.swagger.v3.oas.annotations.media.Schema
import org.dataland.datalandbackend.model.enums.commons.YesNoNa
import java.math.BigDecimal

/**
 * The data-model for the RisikenUndMassnahmenKreislaufwirtschaft section
 */
data class EsgDatenkatalogUmweltRisikenUndMassnahmenKreislaufwirtschaft(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Verfügt das Unternehmen über ein Abfallmanagementsystem?""",
        example = """ "Yes"  """,
    )
    val abfallmanagementsystem: YesNoNa? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte skizzieren sie kurz das vorhandene System, insbesondere zur Produktion von und Umgang mit gefährlichen Abfällen.""",
        example = """ "This is some free text"  """,
    )
    val skizzierungAbfallmanagementsystem: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Wie hoch ist der Anteil von wiederverwendeten oder recycelten sekundären Komponenten, Produkten und Materialien, der im Produktionsprozess des Unternehmens verwendet wird? Methodik analog ESRS E5-4. Angabe als Anteil der verwendeten Ressourcen angeben (in %). Soweit das Unternehmen plant, den Anteil zu erhöhen, bitte hier kurz erörternde Ausführungen. Bei Bedarf können hier zudem weitere Details zur Verwendung von Recyclaten aufgeführt werden.""",
        example = """13.52 """,
    )
    val anteilWiederverwendeterOderRecycelterKomponentenProdukteUndMaterialienImProduktionsprozess: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Plant das Unternehmen den Anteil von Recyclaten im Produktionsprozess zu erhöhen?""",
        example = """ "Yes"  """,
    )
    val geplanteErhoehungDesAnteilsVonRecyclaten: YesNoNa? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Bitte Basisjahr / Basiswert und entsprechende Planwerte angeben.""",
        example = """ "This is some free text"  """,
    )
    val angabenZurGeplantenErhoehungDesAnteilsVonRecyclaten: String? = null,
)
