// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.capex.nonEligibleShare

import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.CurrencyDataPoint
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import java.math.BigDecimal

/**
 * The data-model for the NonEligibleShare section
 */
data class EutaxonomyNonFinancialsCapexNonEligibleShare(
    @field:Valid()
    val relativeShareInPercent: ExtendedDataPoint<BigDecimal?>? = null,
    @field:Valid()
    val absoluteShare: CurrencyDataPoint? = null,
)
