#!/usr/bin/env bash

# Database passwords
export BACKEND_DB_PASSWORD=password
export EMAIL_SERVICE_DB_PASSWORD=password
export API_KEY_MANAGER_DB_PASSWORD=password
export DATA_SOURCING_SERVICE_DB_PASSWORD=password
export INTERNAL_STORAGE_DB_PASSWORD=password
export DOCUMENT_MANAGER_DB_PASSWORD=password
export QA_SERVICE_DB_PASSWORD=password
export COMMUNITY_MANAGER_DB_PASSWORD=password
export USER_SERVICE_DB_PASSWORD=password
export PGADMIN_PASSWORD=password
export ACCOUNTING_SERVICE_DB_PASSWORD=password

# Service client secrets
export DATALAND_EMAIL_SERVICE_CLIENT_SECRET=password
export DATALAND_API_KEY_MANAGER_CLIENT_SECRET=password
export DATALAND_DATA_SOURCING_SERVICE_CLIENT_SECRET=password
export DATALAND_BATCH_MANAGER_CLIENT_SECRET=password
export DATALAND_COMMUNITY_MANAGER_CLIENT_SECRET=password
export DATALAND_QA_SERVICE_CLIENT_SECRET=password
export DATALAND_DOCUMENT_MANAGER_CLIENT_SECRET=password
export DATALAND_BACKEND_CLIENT_SECRET=password
export DATALAND_USER_SERVICE_CLIENT_SECRET=password
export DATALAND_DATA_EXPORTER_CLIENT_SECRET=password

# Electron configuration
export ELECTRON_EXTRA_LAUNCH_ARGS=--ignore-connections-limit=local-dev.dataland.com

# Keycloak configuration
export INITIALIZE_KEYCLOAK=false
export KC_BOOTSTRAP_ADMIN_USERNAME=admin
export KC_BOOTSTRAP_ADMIN_PASSWORD=password
export KEYCLOAK_DB_PASSWORD=password
export KEYCLOAK_FRONTEND_URL=https://local-dev.dataland.com/keycloak

# Keycloak user credentials
export KEYCLOAK_READER_PASSWORD=password
export KEYCLOAK_READER_SALT=K9nzg086pCNjq8dxl84GZg==
export KEYCLOAK_READER_VALUE=Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA==
export KEYCLOAK_UPLOADER_PASSWORD=password
export KEYCLOAK_UPLOADER_SALT=K9nzg086pCNjq8dxl84GZg==
export KEYCLOAK_UPLOADER_VALUE=Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA==
export KEYCLOAK_REVIEWER_PASSWORD=password
export KEYCLOAK_REVIEWER_SALT=K9nzg086pCNjq8dxl84GZg==
export KEYCLOAK_REVIEWER_VALUE=Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA==
export KEYCLOAK_JUDGE_PASSWORD=password
export KEYCLOAK_JUDGE_SALT=z7iDkOaNQfeUQEV3IBpEFQ==
export KEYCLOAK_JUDGE_VALUE=a+lk/Ddwa5wWL9T6BTZMhdNGEBiX6dzngWr5ic4Yt44=
export KEYCLOAK_PREMIUM_USER_PASSWORD=password
export KEYCLOAK_PREMIUM_USER_SALT=K9nzg086pCNjq8dxl84GZg==
export KEYCLOAK_PREMIUM_USER_VALUE=Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA==
export KEYCLOAK_DATALAND_ADMIN_PASSWORD=password
export KEYCLOAK_DATALAND_ADMIN_SALT=K9nzg086pCNjq8dxl84GZg==
export KEYCLOAK_DATALAND_ADMIN_VALUE=Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA==

# Application configuration
export EXPECT_STACKTRACE=true
export NOTIFICATION_INTERNAL_RECEIVERS=dummy.mail@example.com
export NOTIFICATION_INTERNAL_CC=dummy.mail2@example.com

# Proxy configuration
export PROXY_PRIMARY_URL=local-dev.dataland.com
export PROXY_LETSENCRYPT_PATH=/etc/letsencrypt/local-dev.dataland.com
export DISABLE_HSTS=true

# RabbitMQ configuration
export RABBITMQ_USER=admin
export RABBITMQ_PASS=password
export RABBITMQ_PASS_HASH=0YAFHtIJtDTGbDqq7hsedvOYJEXBXgFr0Nzs1q9AnyDL1NVr

# Backend URLs
export INTERNAL_BACKEND_URL=http://host.docker.internal:8080/api
export BACKEND_URL=http://host.docker.internal:8080/api/

# Location configuration
export FRONTEND_LOCATION_CONFIG=Test
export BACKEND_LOCATION_CONFIG=Dev

# Data Exporter
export DATA_EXPORTER_OUTPUT_DIRECTORY=./dataland-data-exporter

# EuroDaT credentials - look up in internal wiki if needed
export EURODAT_BASE_URL=https://app.int.eurodat.org

# Logging configuration
export LOGGING_OPTIONS_MAX_SIZE=100M
export LOGGING_OPTIONS_MAX_FILE=1

# Grafana and Loki
export GRAFANA_ADMIN=admin
export GRAFANA_PASSWORD=password
export LOKI_VOLUME=./dataland-loki/data

# Slack alerts
export SLACK_ALERT_URL=no_alerts_from_local_dev
export SLACK_CRITICAL_ALERT_URL=no_alerts_from_local_dev
