// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgQuestionnaire.model.unternehmensfuehrungGovernance.aufsichtsrat

import java.math.BigInteger

/**
 * The data-model for the Aufsichtsrat section
 */
data class EsgQuestionnaireUnternehmensfuehrunggovernanceAufsichtsrat(
    val anzahlDerMitgliederImAufsichtsrat: BigInteger? = null,
    val anzahlUnabhaengigerMitgliederImAufsichtsrat: BigInteger? = null,
    val anzahlVonFrauenImAufsichtsrat: BigInteger? = null,
)
