// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.lksg.model.general.productionSpecificOwnOperations

import org.dataland.datalandbackend.frameworks.lksg.custom.LksgProduct

/**
 * The data-model for the ProductionSpecificOwnOperations section
 */
data class LksgGeneralProductionSpecificOwnOperations(
    val mostImportantProducts: MutableList<LksgProduct?, LksgProduct?>? = null,

)
