// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgquestionnaire.model.allgemein.unSgds

/**
 * The data-model for the UnSgds section
 */
data class EsgQuestionnaireAllgemeinUnSgds(
    val ausrichtungNachDenUnSdgsUndAktivesVerfolgen: String? = null,

)
