// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.gdv.model.soziales.unternehmensstrukturaenderungen

import org.dataland.datalandbackend.model.enums.commons.YesNo
import java.math.BigDecimal

/**
 * The data-model for the Unternehmensstrukturaenderungen section
 */
data class GdvSozialesUnternehmensstrukturaenderungen(
    val vorhandenseinKuerzlicherAenderungenDerUnternehmensstruktur: YesNo?,
    val anzahlUnbefristeterVertraegeInDeutschland: BigDecimal?,
    val anzahlDerVonEinemVerkaufBetroffenenUnbefristetenVertraegeInDeutschland: BigDecimal?,
    val anzahlDerVonEinerAkquisitionBetroffenenUnbefristetenVertraegeInDeutschland: BigDecimal?,
    val anzahlUnbefristeterVertraegeInDerGesamtgruppe: BigDecimal?,
    val anzahlDerVonEinemVerkaufBetroffenenUnbefristetenVertraegeInDerGesamtgruppe: BigDecimal?,
    val anzahlDerVonEinerAkquisitionBetroffenenUnbefristetenVertraegeInDerGesamtgruppe: BigDecimal?,
)
