package org.dataland.datalandbackend.utils

object NuclearAndGasMapping {
    val aliasMap =
        mapOf(
            "taxonomyAlignedShareNumeratorNAndG426" to "ALIGNED_ACTIVITIES_4_26",
            "taxonomyAlignedShareNumeratorNAndG427" to "ALIGNED_ACTIVITIES_4_27",
            "taxonomyAlignedShareNumeratorNAndG428" to "ALIGNED_ACTIVITIES_4_28",
            "taxonomyAlignedShareNumeratorNAndG429" to "ALIGNED_ACTIVITIES_4_29",
            "taxonomyAlignedShareNumeratorNAndG430" to "ALIGNED_ACTIVITIES_4_30",
            "taxonomyAlignedShareNumeratorNAndG431" to "ALIGNED_ACTIVITIES_4_31",
            "taxonomyAlignedShareNumeratorOtherActivities" to "OTHER_ACTIVITIES",
            "taxonomyAlignedShareNumerator" to "TOTAL_PROPORTION",
            "taxonomyAlignedShareDenominatorNAndG426" to "ALIGNED_ACTIVITIES_4_26",
            "taxonomyAlignedShareDenominatorNAndG427" to "ALIGNED_ACTIVITIES_4_27",
            "taxonomyAlignedShareDenominatorNAndG428" to "ALIGNED_ACTIVITIES_4_28",
            "taxonomyAlignedShareDenominatorNAndG429" to "ALIGNED_ACTIVITIES_4_29",
            "taxonomyAlignedShareDenominatorNAndG430" to "ALIGNED_ACTIVITIES_4_30",
            "taxonomyAlignedShareDenominatorNAndG431" to "ALIGNED_ACTIVITIES_4_31",
            "taxonomyAlignedShareDenominatorOtherActivities" to "OTHER_ACTIVITIES",
            "mitigation" to "CCM",
            "adaptation" to "CCA",
            "mitigationAndAdaptation" to "CCM_AND_CCA",
            "taxonomyAlignedShareDenominator" to "TOTAL_PROPORTION",
            "taxonomyNonEligibleShareNAndG426" to "ALIGNED_ACTIVITIES_4_26",
            "taxonomyNonEligibleShareNAndG427" to "ALIGNED_ACTIVITIES_4_27",
            "taxonomyNonEligibleShareNAndG428" to "ALIGNED_ACTIVITIES_4_28",
            "taxonomyNonEligibleShareNAndG429" to "ALIGNED_ACTIVITIES_4_29",
            "taxonomyNonEligibleShareNAndG430" to "ALIGNED_ACTIVITIES_4_30",
            "taxonomyNonEligibleShareNAndG431" to "ALIGNED_ACTIVITIES_4_31",
            "taxonomyNonEligibleShareOtherActivities" to "OTHER_ACTIVITIES",
            "taxonomyNonEligibleShare" to "TOTAL_PROPORTION",
            "taxonomyEligibleButNotAlignedShareNAndG426" to "ALIGNED_ACTIVITIES_4_26",
            "taxonomyEligibleButNotAlignedShareNAndG427" to "ALIGNED_ACTIVITIES_4_27",
            "taxonomyEligibleButNotAlignedShareNAndG428" to "ALIGNED_ACTIVITIES_4_28",
            "taxonomyEligibleButNotAlignedShareNAndG429" to "ALIGNED_ACTIVITIES_4_29",
            "taxonomyEligibleButNotAlignedShareNAndG430" to "ALIGNED_ACTIVITIES_4_30",
            "taxonomyEligibleButNotAlignedShareNAndG431" to "ALIGNED_ACTIVITIES_4_31",
            "taxonomyEligibleButNotAlignedShareOtherActivities" to "OTHER_ACTIVITIES",
            "taxonomyEligibleButNotAlignedShare" to "TOTAL_PROPORTION",
        )
}
