// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import {
  type FrontendFrameworkDefinition,
  type FrameworkViewConfiguration,
} from '@/frameworks/BaseFrameworkDefinition';
import { pcafViewConfiguration } from '@/frameworks/pcaf/ViewConfig';
import { BasePcafFrameworkDefinition } from '@/frameworks/pcaf/BaseFrameworkDefinition';
import { type PcafData } from '@clients/backend';

export class FrontendPcafFrameworkDefinition
  extends BasePcafFrameworkDefinition
  implements FrontendFrameworkDefinition<PcafData>
{
  getFrameworkViewConfiguration(): FrameworkViewConfiguration<PcafData> {
    return {
      type: 'MultiLayerDataTable',
      configuration: pcafViewConfiguration,
    };
  }
}

export default new FrontendPcafFrameworkDefinition();
