// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgquestionnaire.model.allgemein.esgZiele

import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the EsgZiele section
 */
data class EsgQuestionnaireAllgemeinEsgZiele(
    val existenzVonEsgZielen: YesNo? = null,
    val beschreibungDerEsgZiele: String? = null,
    val investitionenInZielerreichung: String? = null,
)
