// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials202673.model.general

import io.swagger.v3.oas.annotations.media.Schema

/**
 * Enum class for the single-select-field fiscalYearDeviation
 */
@Schema(
    enumAsRef = true,
)
enum class EutaxonomyNonFinancials202673GeneralFiscalYearDeviationOptions {
    Deviation,
    NoDeviation,
}
