// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.gdv.model.general.masterData

import org.dataland.datalandbackend.model.enums.commons.YesNo
import java.time.LocalDate

/**
 * The data-model for the MasterData section
 */
data class GdvGeneralMasterData(
    val berichtsPflicht: YesNo,
    val gueltigkeitsDatum: LocalDate? = null,
)
