// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type AxiosPromise, type AxiosRequestConfig, type AxiosInstance } from 'axios';
import { type CompanyAssociatedData } from '@/api-models/CompanyAssociatedData';
import {
  type Configuration,
  type DataMetaInformation,
  type EsgQuestionnaireData,
  EsgQuestionnaireDataControllerApi,
} from '@clients/backend';
import { type PublicFrameworkDataApi } from '@/utils/api/UnifiedFrameworkDataApi';
import { type DataAndMetaInformation } from '@/api-models/DataAndMetaInformation';

export class EsgQuestionnaireApiClient implements PublicFrameworkDataApi<EsgQuestionnaireData> {
  private readonly openApiDataController: EsgQuestionnaireDataControllerApi;

  constructor(configuration: Configuration | undefined, axiosInstance: AxiosInstance | undefined) {
    this.openApiDataController = new EsgQuestionnaireDataControllerApi(configuration, undefined, axiosInstance);
  }

  getAllCompanyData(
    companyId: string,
    showOnlyActive?: boolean,
    reportingPeriod?: string,
    options?: AxiosRequestConfig
  ): AxiosPromise<DataAndMetaInformation<EsgQuestionnaireData>[]> {
    return this.openApiDataController.getAllCompanyEsgQuestionnaireData(
      companyId,
      showOnlyActive,
      reportingPeriod,
      options
    );
  }

  getFrameworkData(
    dataId: string,
    options?: AxiosRequestConfig
  ): AxiosPromise<CompanyAssociatedData<EsgQuestionnaireData>> {
    return this.openApiDataController.getCompanyAssociatedEsgQuestionnaireData(dataId, options);
  }

  postFrameworkData(
    data: CompanyAssociatedData<EsgQuestionnaireData>,
    bypassQa?: boolean,
    options?: AxiosRequestConfig
  ): AxiosPromise<DataMetaInformation> {
    return this.openApiDataController.postCompanyAssociatedEsgQuestionnaireData(data, bypassQa, options);
  }
}
