// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type Category } from '@/utils/GenericFrameworkTypes';
import { type EsgQuestionnaireData } from '@clients/backend';
import { getActivityNamesAsDropdownOptions } from '@/components/resources/frameworkDataSearch/EuTaxonomyActivityNames';

export const esgQuestionnaireDataModel = [
  {
    name: 'general',
    label: 'General',
    color: '',
    showIf: (): boolean => true,
    subcategories: [
      {
        name: 'masterData',
        label: 'Master Data',
        fields: [
          {
            name: 'berichtspflichtUndEinwilligungZurVeroeffentlichung',
            label: 'Berichtspflicht und Einwilligung zur Veröffentlichung',
            description:
              'Ist das Unternehmen berichtspflichtig im Rahmen der CSRD-Richtlinie bzw. ist es gemäß den Offenlegungspflichten der Artikel 19a und 29a der Richtilinie 2023/34/EU zur Nachhaltigkeitsberichtserstattung verpflichtet? Ist das Unternehmen außerdem mit einer Veröffentlichung des Datensatzes auf Dataland einverstanden? Anderenfalls ist eine Dateneineingabe nicht möglich.',

            component: 'YesNoFormField',
            required: true,
            showIf: (): boolean => true,
            validation: 'required|is:Yes',
          },
          {
            name: 'gueltigkeitsDatum',
            label: '(Gültigkeits) Datum',
            description: 'Datum bis wann die Information gültig ist',

            component: 'DateFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
  {
    name: 'allgemein',
    label: 'Allgemein',
    color: '',
    showIf: (): boolean => true,
    subcategories: [
      {
        name: 'generelleEsgStrategie',
        label: 'Generelle ESG-Strategie',
        fields: [
          {
            name: 'nachhaltigkeitsstrategieVorhanden',
            label: 'Nachhaltigkeitsstrategie vorhanden',
            description: 'Verfügt das Unternehmen über eine Nachhaltigkeitsstrategie?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'dokumenteZurNachhaltigkeitsstrategie',
            label: 'Dokumente zur Nachhaltigkeitsstrategie',
            description:
              'Bitte hängen Sie Ihre Nachhaltigkeitsstrategie an. Nachhaltigkeit in diesem Sinne umfasst die Themen Umwelt (E), Soziales (S) und Unternehmensführung (G). Sie können mehrere Dokumente anhängen und pro Dokument eine Beschreibung angeben.',

            component: 'ListOfBaseDataPointsFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.nachhaltigkeitsstrategieVorhanden == 'Yes',
          },
          {
            name: 'massnahmenBezueglich15GradCelsiusZielVorhanden',
            label: 'Maßnahmen bezüglich 1,5 Grad Celsius Ziel vorhanden',
            description: 'Werden spezielle Ziele / Maßnahmen ergriffen, um das 1,5 °C Ziel zu erreichen?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.nachhaltigkeitsstrategieVorhanden == 'Yes',
          },
          {
            name: 'beschreibungMassnahmenBezueglich15GradCelsiusZiel',
            label: 'Beschreibung Maßnahmen bezüglich 1,5 Grad Celsius Ziel',
            description: 'Beschreiben Sie spezielle Ziele / Maßnahmen, um das 1,5°C Ziel zu erreichen.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.massnahmenBezueglich15GradCelsiusZielVorhanden == 'Yes',
          },
          {
            name: 'zugewieseneBudgetsBis2030',
            label: 'Zugewiesene Budgets bis 2030',
            description:
              'Bezüglich der angegebenen Maßnahmen: Bitte die zugewiesenen Budgets bis zum Jahr 2030 angeben.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.massnahmenBezueglich15GradCelsiusZielVorhanden == 'Yes',
          },
          {
            name: 'zugewieseneBudgetsAb2031',
            label: 'Zugewiesene Budgets ab 2031',
            description:
              'Bezüglich der angegebenen Maßnahmen: Bitte die zugewiesenen Budgets ab dem Jahr 2031 angeben.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.massnahmenBezueglich15GradCelsiusZielVorhanden == 'Yes',
          },
          {
            name: 'erwarteterFinanzierungsbedarfBis2030',
            label: 'Erwarteter Finanzierungsbedarf bis 2030',
            description:
              'Bezüglich der angegebenen Maßnahmen: Bitte den erwarteten Finanzierungsbedarf bis zum Jahr 2030 angeben.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.massnahmenBezueglich15GradCelsiusZielVorhanden == 'Yes',
          },
          {
            name: 'erwarteterFinanzierungsbedarfAb2031',
            label: 'Erwarteter Finanzierungsbedarf ab 2031',
            description:
              'Bezüglich der angegebenen Maßnahmen: Bitte den erwarteten Finanzierungsbedarf ab dem Jahr 2031 angeben.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.massnahmenBezueglich15GradCelsiusZielVorhanden == 'Yes',
          },
          {
            name: 'geplanteVollzeitaequivalenteBis2023',
            label: 'Geplante Vollzeitäquivalente bis 2023',
            description:
              'Bezüglich der angegebenen Maßnahmen: Bitte die geplanten Vollzeitäquivalente bis zum Jahr 2030 angeben.',

            unit: 'FTEs',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.massnahmenBezueglich15GradCelsiusZielVorhanden == 'Yes',
          },
          {
            name: 'geplanteVollzeitaequivalenteAb2031',
            label: 'Geplante Vollzeitäquivalente ab 2031',
            description:
              'Bezüglich der angegebenen Maßnahmen: Bitte die geplanten Vollzeitäquivalente ab dem Jahr 2031 angeben.',

            unit: 'FTEs',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.massnahmenBezueglich15GradCelsiusZielVorhanden == 'Yes',
          },
          {
            name: 'chancenOderHindernisse',
            label: 'Chancen oder Hindernisse',
            description:
              'Welche grundsätzlichen Chancen oder Hindernisse bestehen für das Unternehmen bei der Berücksichtigung von ESG-Belangen?',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'taxonomieKpisAndBestimmteAktivitaeten',
        label: 'Taxonomie KPIs & bestimmte Aktivitäten',
        fields: [
          {
            name: 'wirtschaftszweige',
            label: 'Wirtschaftszweige',
            description:
              'In welchen Wirtschaftszweigen ist das Unternehmen primär aktiv? Bitte Angabe des primären NACE-Codes (4-stellig).',

            component: 'NaceCodeFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'gesamtumsatz',
            label: 'Gesamtumsatz',
            description: 'Geben Sie den Gesamtumsatz des Unternehmens in € an.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'taxonomiefaehigerUmsatz',
            label: 'Taxonomiefähiger Umsatz',
            description: 'Geben Sie den taxonomiefähigen Teilbetrag des Gesamtumsatzes in € an.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'taxonomiekonformerUmsatz',
            label: 'Taxonomiekonformer Umsatz',
            description: 'Geben Sie den taxonomiekonformen Teilbetrag des taxonomiefähigen Betrags in € an.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'gesamtCapex',
            label: 'Gesamt-CapEx',
            description: 'Geben Sie die CapEx des Unternehmens in € an.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'taxonomiefaehigeCapex',
            label: 'Taxonomiefähige CapEx',
            description: 'Geben Sie den taxonomiefähigen Teilbetrag der Gesamt-CapEx in € an.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'taxonomiekonformeCapex',
            label: 'Taxonomiekonforme CapEx',
            description: 'Geben Sie den taxonomiekonformen Teilbetrag der taxonomiefähigen CapEx in € an.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'taxonomiebezogeneCapexPlanungVorhanden',
            label: 'Taxonomiebezogene CapEx-Planung vorhanden',
            description: 'Hat das Unternehmen eine taxonomiebezogene CapEx-Planung? ',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'geplanteTaxonomiefaehigeCapexIn5Jahren',
            label: 'Geplante taxonomiefähige CapEx in 5 Jahren',
            description:
              'Welcher taxonomiefähige prozentuale Anteil an der Gesamt-CapEx wird im Rahmen der CapEx-Planung voraussichtlich in 5 Jahren erreicht werden? ',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.taxonomiebezogeneCapexPlanungVorhanden == 'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'geplanteTaxonomiekonformeCapexIn5Jahren',
            label: 'Geplante taxonomiekonforme CapEx in 5 Jahren',
            description:
              'Welcher taxonomiekonforme prozentuale Anteil an der Gesamt-CapEx wird im Rahmen der CapEx-Planung voraussichtlich in 5 Jahren erreicht werden? ',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.taxonomiebezogeneCapexPlanungVorhanden == 'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'aktivitaetImSektorFossileBrennstoffe',
            label: 'Aktivität im Sektor Fossile Brennstoffe',
            description: 'Ist das Unternehmen im Sektor "Fossile Brennstoffe (Kohle, Gas, Öl)" aktiv?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'aktuellerProzentualerUmsatzanteilImSektorFossileBrennstoffe',
            label: 'Aktueller prozentualer Umsatzanteil im Sektor "Fossile Brennstoffe"',
            description:
              'Welcher prozentuale Anteil am Gesamtumsatz ist auf den Sektor "Fossile Brennstoffe (Kohle, Gas, Öl)" zurückzuführen?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.aktivitaetImSektorFossileBrennstoffe == 'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'geplanterProzentualerUmsatzanteilImSektorFossileBrennstoffeIn2030',
            label: 'Geplanter prozentualer Umsatzanteil im Sektor "Fossile Brennstoffe" in 2030',
            description:
              'Welcher prozentuale Anteil am Gesamtumsatz wird im Jahr 2030 voraussichtlich auf den Sektor "Fossile Brennstoffe (Kohle, Gas, Öl)" zurückzuführen sein?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.aktivitaetImSektorFossileBrennstoffe == 'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'geplanterProzentualerUmsatzanteilImSektorFossileBrennstoffeIn2040',
            label: 'Geplanter prozentualer Umsatzanteil im Sektor "Fossile Brennstoffe" in 2040',
            description:
              'Welcher prozentuale Anteil am Gesamtumsatz wird im Jahr 2040 voraussichtlich auf den Sektor "Fossile Brennstoffe (Kohle, Gas, Öl)" zurückzuführen sein?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.aktivitaetImSektorFossileBrennstoffe == 'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'aktivitaetImSektorHerstellungVonChemikalien',
            label: 'Aktivität im Sektor "Herstellung von Chemikalien"',
            description: 'Ist das Unternehmen im Sektor "Herstellung von Chemikalien" aktiv?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'aktuellerProzentualerUmsatzanteilImSektorHerstellungVonChemikalien',
            label: 'Aktueller prozentualer Umsatzanteil im Sektor "Herstellung von Chemikalien"',
            description:
              'Welcher prozentuale Anteil am Gesamtumsatz ist auf den Sektor "Herstellung von Chemikalien" zurückzuführen?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.aktivitaetImSektorHerstellungVonChemikalien ==
              'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'geplanterProzentualerUmsatzanteilImSektorHerstellungVonChemikalienIn2030',
            label: 'Geplanter prozentualer Umsatzanteil im Sektor "Herstellung von Chemikalien" in 2030',
            description:
              'Welcher prozentuale Anteil am Gesamtumsatz wird im Jahr 2030 voraussichtlich auf den Sektor "Herstellung von Chemikalien" zurückzuführen sein?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.aktivitaetImSektorHerstellungVonChemikalien ==
              'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'geplanterProzentualerUmsatzanteilImSektorHerstellungVonChemikalienIn2040',
            label: 'Geplanter prozentualer Umsatzanteil im Sektor "Herstellung von Chemikalien" in 2040',
            description:
              'Welcher prozentuale Anteil am Gesamtumsatz wird im Jahr 2040 voraussichtlich auf den Sektor "Herstellung von Chemikalien" zurückzuführen sein?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.aktivitaetImSektorHerstellungVonChemikalien ==
              'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'aktivitaetImSektorUmstritteneWaffen',
            label: 'Aktivität im Sektor "Umstrittene Waffen"',
            description: 'Ist das Unternehmen im Sektor "Umstrittene Waffen" aktiv?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'aktuellerProzentualerUmsatzanteilImSektorUmstritteneWaffen',
            label: 'Aktueller prozentualer Umsatzanteil im Sektor "Umstrittene Waffen"',
            description:
              'Welcher prozentuale Anteil am Gesamtumsatz ist auf den Sektor "Umstrittene Waffen" zurückzuführen?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.aktivitaetImSektorUmstritteneWaffen == 'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'geplanterProzentualerUmsatzanteilImSektorUmstritteneWaffenIn2030',
            label: 'Geplanter prozentualer Umsatzanteil im Sektor "Umstrittene Waffen" in 2030',
            description:
              'Welcher prozentuale Anteil am Gesamtumsatz wird im Jahr 2030 voraussichtlich auf den Sektor "Umstrittene Waffen" zurückzuführen sein?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.aktivitaetImSektorUmstritteneWaffen == 'Yes',
            validation: 'between:0,100',
          },
          {
            name: 'geplanterProzentualerUmsatzanteilImSektorUmstritteneWaffenIn2040',
            label: 'Geplanter prozentualer Umsatzanteil im Sektor "Umstrittene Waffen" in 2040',
            description:
              'Welcher prozentuale Anteil am Gesamtumsatz wird im Jahr 2040 voraussichtlich auf den Sektor "Umstrittene Waffen" zurückzuführen sein?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.taxonomieKpisAndBestimmteAktivitaeten?.aktivitaetImSektorUmstritteneWaffen == 'Yes',
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'esgBerichte',
        label: 'ESG Berichte',
        fields: [
          {
            name: 'aktuelleBerichte',
            label: 'Aktuelle Berichte',
            description: 'Bitte teilen Sie die letzten Berichte mit uns (vorzugsweise die letzten drei).',

            component: 'ListOfBaseDataPointsFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.generelleEsgStrategie?.chancenOderHindernisse == 'Yes',
          },
        ],
      },
      {
        name: 'akkreditierungen',
        label: 'Akkreditierungen',
        fields: [
          {
            name: 'iso14001',
            label: 'ISO 14001',
            description:
              'Haben Sie eine ISO 14001 Akkreditierung? Bitte teilen Sie das entsprechende Zertifikat mit uns.',

            component: 'YesNoBaseDataPointFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'iso45001',
            label: 'ISO 45001',
            description:
              'Haben Sie eine ISO 45001 Akkreditierung? Bitte teilen Sie das entsprechende Zertifikat mit uns.',

            component: 'YesNoBaseDataPointFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'iso27001',
            label: 'ISO 27001',
            description:
              'Haben Sie eine ISO 27001 Akkreditierung? Bitte teilen Sie das entsprechende Zertifikat mit uns.',

            component: 'YesNoBaseDataPointFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'iso50001',
            label: 'ISO 50001',
            description:
              'Haben Sie eine ISO 50001 Akkreditierung? Bitte teilen Sie das entsprechende Zertifikat mit uns.',

            component: 'YesNoBaseDataPointFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'weitereAkkreditierungen',
            label: 'Weitere Akkreditierungen',
            description:
              'Bitte führen Sie weitere Akkreditierungen auf, sofern diese nicht bereits gelistet sind, und teilen Sie entsprechende Zertifikate mit uns.',

            component: 'ListOfBaseDataPointsFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'unGlobalConceptPrinzipien',
        label: 'UN Global Concept Prinzipien',
        fields: [
          {
            name: 'mechanismenZurUeberwachungDerEinhaltungDerUngcp',
            label: 'Mechanismen zur Überwachung der Einhaltung der UNGCP',
            description:
              'Verfügt das Unternehmen über Prozesse und Compliance-Mechanismen, um die Einhaltung der Prinzipien des UN Global Compact zu überwachen?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'richtlinienZurEinhaltungDerUngcp',
            label: 'Richtlinien zur Einhaltung der UNGCP',
            description:
              'Bitte teilen Sie die Richtlinien mit uns die beschreiben oder Informationen darüber liefern, wie das Unternehmen die Einhaltung der UN Global Compact Prinzipien überwacht.',

            component: 'ListOfBaseDataPointsFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.unGlobalConceptPrinzipien?.mechanismenZurUeberwachungDerEinhaltungDerUngcp == 'Yes',
          },
          {
            name: 'erklaerungDerEinhaltungDerUngcp',
            label: 'Erklärung der Einhaltung der UNGCP',
            description: 'Bitte geben Sie eine Erklärung ab, dass keine Verstöße gegen diese Grundsätze vorliegen.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.unGlobalConceptPrinzipien?.mechanismenZurUeberwachungDerEinhaltungDerUngcp == 'Yes',
          },
        ],
      },
      {
        name: 'oecdLeitsaetze',
        label: 'OECD Leitsätze',
        fields: [
          {
            name: 'mechanismenZurUeberwachungDerEinhaltungDerOecdLeitsaetze',
            label: 'Mechanismen zur Überwachung der Einhaltung der OECD-Leitsätze',
            description:
              'Verfügt das Unternehmen über Prozesse und Compliance-Mechanismen, um die Einhaltung der OECD-Leitsätze für multinationale Unternehmen (OECD MNE Guidelines) zu überwachen?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'richtlinienZurEinhaltungDerOecdLeitsaetze',
            label: 'Richtlinien zur Einhaltung der OECD-Leitsätze',
            description:
              'Bitte teilen Sie die Richtlinien mit uns die beschreiben oder Informationen darüber liefern, wie das Unternehmen die Einhaltung der OECD-Leitsätze überwacht.',

            component: 'ListOfBaseDataPointsFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.oecdLeitsaetze?.mechanismenZurUeberwachungDerEinhaltungDerOecdLeitsaetze == 'Yes',
          },
          {
            name: 'erklaerungDerEinhaltungDerOecdLeitsaetze',
            label: 'Erklärung der Einhaltung der OECD-Leitsätze',
            description: 'Bitte geben Sie eine Erklärung ab, dass keine Verstöße gegen diese Grundsätze vorliegen.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.oecdLeitsaetze?.mechanismenZurUeberwachungDerEinhaltungDerOecdLeitsaetze == 'Yes',
          },
        ],
      },
      {
        name: 'sonstige',
        label: 'Sonstige',
        fields: [
          {
            name: 'ausrichtungAufDieUnSdgsUndAktivesVerfolgen',
            label: 'Ausrichtung auf die UN SDGs und aktives Verfolgen',
            description:
              'Wie steht das Unternehmen in Einklang mit den 17 UN-Zielen für nachhaltige Entwicklung? Welche dieser Ziele verfolgt das Unternehmen aktiv, entweder durch ihre Geschäftstätigkeit oder durch die Unternehmensführung?',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'ausschlusslistenAufBasisVonEsgKriterien',
            label: 'Ausschlusslisten auf Basis von ESG Kriterien',
            description:
              'Führt das Unternehmen Ausschlusslisten? Von besonderem Interesse sind Listen die Ausschlusskriterien, die einen Bezug zu den Bereichen E, S oder G haben.',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'ausschlusslisten',
            label: 'Ausschlusslisten',
            description: 'Bitte nennen Sie die Ausschlusslisten auf Basis von ESG Kriterien.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.sonstige?.ausschlusslistenAufBasisVonEsgKriterien == 'Yes',
          },
        ],
      },
      {
        name: 'fuehrungsstandards',
        label: 'Führungsstandards',
        fields: [
          {
            name: 'oekologischeSozialeFuehrungsstandardsOderPrinzipien',
            label: 'Ökologische/soziale Führungsstandards oder -prinzipien',
            description:
              'Hat sich das Unternehmen zu ökologischen/sozialen Führungsstandards oder Prinzipien verpflichtet?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'anreizmechanismenFuerDasManagementUmwelt',
            label: 'Anreizmechanismen für das Management (Umwelt)',
            description:
              'Wie spiegeln sich die Anreizmechanismen für den Bereich Umwelt in der jährlichen Zielsetzung für das Management wieder? Bitte geben Sie die aktuellen Verpflichtungen an.',
            options: [
              {
                label: 'Nein',
                value: 'Nein',
              },
              {
                label: 'Ja, Aufsichtsrat',
                value: 'JaAufsichtsrat',
              },
              {
                label: 'Ja, Geschäftsleitung',
                value: 'JaGeschaeftsleitung',
              },
              {
                label: 'Ja, Aufsichtsrat und Geschäftsleitung',
                value: 'JaAufsichtsratUndGeschaeftsleitung',
              },
            ],

            component: 'SingleSelectFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.fuehrungsstandards?.oekologischeSozialeFuehrungsstandardsOderPrinzipien == 'Yes',
          },
          {
            name: 'anreizmechanismenFuerDasManagementSoziales',
            label: 'Anreizmechanismen für das Management (Soziales)',
            description:
              'Wie spiegeln sich die Anreizmechanismen für den Bereich Soziales in der jährlichen Zielsetzung für das Management wieder? Bitte geben Sie die aktuellen Verpflichtungen an.',
            options: [
              {
                label: 'Nein',
                value: 'Nein',
              },
              {
                label: 'Ja, Aufsichtsrat',
                value: 'JaAufsichtsrat',
              },
              {
                label: 'Ja, Geschäftsleitung',
                value: 'JaGeschaeftsleitung',
              },
              {
                label: 'Ja, Aufsichtsrat und Geschäftsleitung',
                value: 'JaAufsichtsratUndGeschaeftsleitung',
              },
            ],

            component: 'SingleSelectFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.fuehrungsstandards?.oekologischeSozialeFuehrungsstandardsOderPrinzipien == 'Yes',
          },
        ],
      },
      {
        name: 'rechtsstreitigkeiten',
        label: 'Rechtsstreitigkeiten',
        fields: [
          {
            name: 'esgBezogeneRechtsstreitigkeiten',
            label: 'ESG-bezogene Rechtsstreitigkeiten',
            description:
              'Ist das Unternehmen in laufende bzw. war das Unternehmen in den letzten 3 Jahren in abgeschlossenen Rechtsstreitigkeiten im Zusammenhang mit ESG involviert?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'rechtsstreitigkeitenMitBezugZuE',
            label: 'Rechtsstreitigkeiten mit Bezug zu E',
            description: 'Haben bzw. hatten die Rechtsstreitigkeiten Bezug zu "E"',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.rechtsstreitigkeiten?.esgBezogeneRechtsstreitigkeiten == 'Yes',
          },
          {
            name: 'statusZuE',
            label: 'Status zu E',
            description: 'Sind die Rechtsstreitigkeiten mit Bezug zu "E" noch offen oder bereits geklärt?',
            options: [
              {
                label: 'offen',
                value: 'Offen',
              },
              {
                label: 'geklärt',
                value: 'Geklaert',
              },
            ],

            component: 'SingleSelectFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.rechtsstreitigkeiten?.rechtsstreitigkeitenMitBezugZuE == 'Yes',
          },
          {
            name: 'einzelheitenZuDenRechtsstreitigkeitenZuE',
            label: 'Einzelheiten zu den Rechtsstreitigkeiten zu E',
            description: 'Bitte erläutern Sie Einzelheiten zu den Rechtsstreitigkeiten.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.rechtsstreitigkeiten?.rechtsstreitigkeitenMitBezugZuE == 'Yes',
          },
          {
            name: 'rechtsstreitigkeitenMitBezugZuS',
            label: 'Rechtsstreitigkeiten mit Bezug zu S',
            description: 'Haben bzw. hatten die Rechtsstreitigkeiten Bezug zu "S"',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.rechtsstreitigkeiten?.esgBezogeneRechtsstreitigkeiten == 'Yes',
          },
          {
            name: 'statusZuS',
            label: 'Status zu S',
            description: 'Sind die Rechtsstreitigkeiten mit Bezug zu "S" noch offen oder bereits geklärt?',
            options: [
              {
                label: 'offen',
                value: 'Offen',
              },
              {
                label: 'geklärt',
                value: 'Geklaert',
              },
            ],

            component: 'SingleSelectFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.rechtsstreitigkeiten?.rechtsstreitigkeitenMitBezugZuS == 'Yes',
          },
          {
            name: 'einzelheitenZuDenRechtsstreitigkeitenZuS',
            label: 'Einzelheiten zu den Rechtsstreitigkeiten zu S',
            description: 'Bitte erläutern Sie Einzelheiten zu den Rechtsstreitigkeiten.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.rechtsstreitigkeiten?.rechtsstreitigkeitenMitBezugZuS == 'Yes',
          },
          {
            name: 'rechtsstreitigkeitenMitBezugZuG',
            label: 'Rechtsstreitigkeiten mit Bezug zu G',
            description: 'Haben bzw. hatten die Rechtsstreitigkeiten Bezug zu "G"',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.rechtsstreitigkeiten?.esgBezogeneRechtsstreitigkeiten == 'Yes',
          },
          {
            name: 'statusZuG',
            label: 'Status zu G',
            description: 'Sind die Rechtsstreitigkeiten mit Bezug zu "G" noch offen oder bereits geklärt?',
            options: [
              {
                label: 'offen',
                value: 'Offen',
              },
              {
                label: 'geklärt',
                value: 'Geklaert',
              },
            ],

            component: 'SingleSelectFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.rechtsstreitigkeiten?.rechtsstreitigkeitenMitBezugZuG == 'Yes',
          },
          {
            name: 'einzelheitenZuDenRechtsstreitigkeitenZuG',
            label: 'Einzelheiten zu den Rechtsstreitigkeiten zu G',
            description: 'Bitte erläutern Sie Einzelheiten zu den Rechtsstreitigkeiten.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.rechtsstreitigkeiten?.rechtsstreitigkeitenMitBezugZuG == 'Yes',
          },
        ],
      },
      {
        name: 'rating',
        label: 'Rating',
        fields: [
          {
            name: 'esgRating',
            label: 'ESG-Rating',
            description: 'Hat das Unternehmen bereits ein ESG-Rating einer anerkannten Ratingagentur?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'agentur',
            label: 'Agentur',
            description: 'Welche Rating Agentur hat das Rating durchgeführt?',

            component: 'InputTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean => dataset.allgemein?.rating?.esgRating == 'Yes',
          },
          {
            name: 'ergebnis',
            label: 'Ergebnis',
            description: 'Wie lautet das Rating?',

            component: 'InputTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean => dataset.allgemein?.rating?.esgRating == 'Yes',
          },
          {
            name: 'ratingbericht',
            label: 'Ratingbericht',
            description: 'Liegt ein Ratingbericht vor?',

            component: 'YesNoBaseDataPointFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean => dataset.allgemein?.rating?.esgRating == 'Yes',
          },
          {
            name: 'kritischePunkte',
            label: 'Kritische Punkte',
            description: 'Was waren die kritischen Punkte beim ESG-Rating?',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean => dataset.allgemein?.rating?.esgRating == 'Yes',
          },
        ],
      },
      {
        name: 'anleihen',
        label: 'Anleihen',
        fields: [
          {
            name: 'grueneSozialeUndOderNachhaltigeEmissionen',
            label: 'Grüne, soziale und/oder nachhaltige Emissionen',
            description: 'Hat das Unternehmen „grüne“, „soziale“ und/oder „nachhaltige“ Schuldtitel begeben?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'ausstehendeGrueneSozialeUndOderNachhaltigeEmissionen',
            label: 'Ausstehende grüne, soziale und/oder nachhaltige Emissionen',
            description:
              'Bitte geben Sie Details zu den ausstehenden Emissionen für das letzte Jahr der Berichterstattung an (in Mio €).',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.anleihen?.grueneSozialeUndOderNachhaltigeEmissionen == 'Yes',
          },
          {
            name: 'sustainibilityLinkedDebt',
            label: 'Sustainibility Linked Debt',
            description: 'Hat das Unternehmen Sustainability Linked Debt („SLD“) emittiert?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'ausstehendeSustainibilityLinkedDebt',
            label: 'Ausstehende Sustainibility Linked Debt',
            description:
              'Bitte geben Sie Details zu den ausstehenden Emissionen für das letzte Jahr der Berichterstattung an (in Mio €).',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.allgemein?.anleihen?.sustainibilityLinkedDebt == 'Yes',
          },
        ],
      },
      {
        name: 'risiken',
        label: 'Risiken',
        fields: [
          {
            name: 'wichtigsteESUndGRisikenUndBewertung',
            label: 'Wichtigste E-, S- und G-Risiken und Bewertung',
            description:
              'Welche sind die wichtigsten von der Gruppe identifizierten E-, S- und G-Risiken? Bitte geben Sie die Details / Bewertung der identifizierten Risiken an.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'hindernisseBeimUmgangMitEsgBedenken',
            label: 'Hindernisse beim Umgang mit ESG-Bedenken',
            description:
              'Welche grundsätzlichen Hindernisse bestehen für das Unternehmen bei der Berücksichtigung von ESG-Belangen?',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
    ],
  },
  {
    name: 'umwelt',
    label: 'Umwelt',
    color: '',
    showIf: (): boolean => true,
    subcategories: [
      {
        name: 'treibhausgasemissionen',
        label: 'Treibhausgasemissionen',
        fields: [
          {
            name: 'treibhausgasBerichterstattungUndPrognosen',
            label: 'Treibhausgas-Berichterstattung und Prognosen',
            description:
              'Welche Treibhausgasinformationen werden derzeit auf Unternehmens-/Konzernebene berichtet und prognostiziert? Bitte geben Sie die Scope 1, Scope 2 und Scope 3 Emissionen für das aktuelle Kalenderjahr, die letzten drei Jahre sowie die Prognosen für die kommenden drei Jahre an (in tCO2-Äquiv.).',
            options: [
              {
                label: 'Scope 1 (in tCO2-Äquiv.)',
                value: 'scope1',
              },
              {
                label: 'Scope 2 (in tCO2-Äquiv.)',
                value: 'scope2',
              },
              {
                label: 'Scope 3 (in tCO2-Äquiv.)',
                value: 'scope3',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearDeltaDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'treibhausgasEmissionsintensitaetDerUnternehmenInDieInvestiertWird',
            label: 'Treibhausgas-Emissionsintensität der Unternehmen, in die investiert wird',
            description:
              'THG-Emissionsintensität der Unternehmen, in die investiert wird. (1) Scope 1 + Scope 2 Treibhausgasemissionen / Umsatz in Millionen EUR, (2) Scope 1 + Scope 2 Treibhausgasemissionen / Unternehmensgröße in Mio. EUR',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'strategieUndZieleZurReduzierungVonTreibhausgasEmissionen',
            label: 'Strategie und Ziele zur Reduzierung von Treibhausgas-Emissionen',
            description:
              'Welchen Entwicklungspfad bzgl. der (Reduktion von) Treibhausgasemissionen verfolgt das Unternehmen. Gibt es einen Zeitplan bzw. konkrete Ziele? Und wie plant das Unternehmen, diesen Kurs zu erreichen? Bitte erläutern Sie, in welchem Bezug dieser Entwicklungspfad zu dem auf dem Pariser Abkommen basierenden Kurs steht.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'produktion',
        label: 'Produktion',
        fields: [
          {
            name: 'produkteZurVerringerungDerUmweltbelastung',
            label: 'Produkte zur Verringerung der Umweltbelastung',
            description:
              'Entwickelt, produziert oder vertreibt das Unternehmen Produkte, die die Umweltbelastung verringern?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'verringerungenDerUmweltbelastung',
            label: 'Verringerungen der Umweltbelastung',
            description: 'Bitte beschreiben Sie möglichst genau, wie die Produkte die Umweltbelastung reduzieren.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.umwelt?.produktion?.produkteZurVerringerungDerUmweltbelastung == 'Yes',
          },
          {
            name: 'oekologischerMindestStandardFuerProduktionsprozesse',
            label: 'Ökologischer Mindest-Standard für Produktionsprozesse',
            description:
              'Verfügt das Unternehmen über interne Richtlinien, die einen Mindestumweltstandard im Produktionsprozess sicherstellen?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'energieverbrauch',
        label: 'Energieverbrauch',
        fields: [
          {
            name: 'berichterstattungEnergieverbrauch',
            label: 'Berichterstattung Energieverbrauch',
            description:
              'Bitte geben Sie den Energieverbrauch (in GWh), sowie den Verbrauch erneuerbaren Energien (%) und, falls zutreffend, die Erzeugung erneuerbaren Energien (%) für das aktuelle Kalenderjahr, die letzten drei Jahre sowie die Prognosen für die kommenden drei Jahre an.',
            options: [
              {
                label: 'Energieverbrauch (in GWh)',
                value: 'energieverbrauch',
              },
              {
                label: '% des Verbrauchs erneuerbarer Energien (in %)',
                value: 'prozentDesVerbrauchsErneuerbarerEnergien',
              },
              {
                label: 'Gegebenenfalls % der erneuerbaren Energieerzeugung (in %)',
                value: 'ggfProzentDerErneuerbarenEnergieerzeugung',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearDeltaDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'unternehmensGruppenStrategieBzglEnergieverbrauch',
            label: 'Unternehmens/Gruppen Strategie bzgl Energieverbrauch',
            description:
              'Bitte erläutern Sie den von der Gruppe/Unternehmen definierte Entwicklungspfad (Zeitplan und Ziel - falls vorhanden) und wie das Unternehmen den geplanten Entwicklungspfad erreichen möchte.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'energieeffizienzImmobilienanlagen',
        label: 'Energieeffizienz Immobilienanlagen',
        fields: [
          {
            name: 'berichterstattungEnergieverbrauchVonImmobilienvermoegen',
            label: 'Berichterstattung Energieverbrauch von Immobilienvermögen',
            description:
              'Bitte geben Sie den Anteil an energieeffizienten Immobilienanlagen (%) für das aktuelle Kalenderjahr, die letzten drei Jahre sowie die Prognosen für die kommenden drei Jahre an.',
            options: [
              {
                label: 'Engagement/Anteil in energieineffizienten Immobilienanlagen',
                value: 'engagementAnteilInEnergieineffizientenImmobilienanlagen',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearDeltaDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'unternehmensGruppenStrategieBzglEnergieeffizientenImmobilienanlagen',
            label: 'Unternehmens/Gruppen Strategie bzgl energieeffizienten Immobilienanlagen',
            description:
              'Bitte erläutern Sie den von der Gruppe/Unternehmen definierte Entwicklungspfad (Zeitplan und Ziel - falls vorhanden) und wie das Unternehmen den geplanten Entwicklungspfad erreichen möchte.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'wasserverbrauch',
        label: 'Wasserverbrauch',
        fields: [
          {
            name: 'berichterstattungWasserverbrauch',
            label: 'Berichterstattung Wasserverbrauch',
            description:
              'Bitte geben Sie den Wasserverbrauch (in l), sowie die Emissionen in Wasser (in Tonnen) für das aktuelle Kalenderjahr, die letzten drei Jahre sowie die Prognosen für die kommenden drei Jahre an.',
            options: [
              {
                label: 'Wasserverbrauch (in l)',
                value: 'wasserverbrauch',
              },
              {
                label: 'Emissionen in Wasser (in t)',
                value: 'emissionenInWasser',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearDeltaDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'unternehmensGruppenStrategieBzglWasserverbrauch',
            label: 'Unternehmens/Gruppen Strategie bzgl Wasserverbrauch',
            description:
              'Bitte erläutern Sie den von der Gruppe/Unternehmen definierte Entwicklungspfad (Zeitplan und Ziel - falls vorhanden) und wie das Unternehmen den geplanten Entwicklungspfad erreichen möchte.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'abfallproduktion',
        label: 'Abfallproduktion',
        fields: [
          {
            name: 'berichterstattungAbfallproduktion',
            label: 'Berichterstattung Abfallproduktion',
            description:
              'Bitte geben Sie die gesamte Abfallmenge (in Tonnen), sowie den Anteil (%) der gesamten Abfallmenge, der recyclet wird, sowie den Anteil (%) gefährlicher Abfall der gesamten Abfallmenge für das aktuelle Kalenderjahr, die letzten drei Jahre sowie die Prognosen für die kommenden drei Jahre an.',
            options: [
              {
                label: 'Gesamte Abfallmenge (in t)',
                value: 'gesamteAbfallmenge',
              },
              {
                label: '% Abfall recycelt (in %)',
                value: 'prozentAbfallRecyclet',
              },
              {
                label: '% Gefährlicher Abfall (in %)',
                value: 'prozentGefaehrlicherAbfall',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearDeltaDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'unternehmensGruppenStrategieBzglAbfallproduktion',
            label: 'Unternehmens/Gruppen Strategie bzgl Abfallproduktion',
            description:
              'Bitte erläutern Sie den von der Gruppe/Unternehmen definierte Entwicklungspfad (Zeitplan und Ziel - falls vorhanden) und wie das Unternehmen den geplanten Entwicklungspfad erreichen möchte.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'recyclingImProduktionsprozess',
            label: 'Recycling im Produktionsprozess',
            description:
              'Bitte geben Sie an, wie hoch der Anteil an Recyclaten (bereits recyceltes wiederverwertetes Material) im Produktionsprozess für das aktuelle Kalenderjahr, die letzten drei Jahre sowie die Prognosen für die kommenden drei Jahre ist.',
            options: [
              {
                label: '% Recycelte Werkstoffe im Produktionsprozess (in %)',
                value: 'prozentRecycelteWerkstoffeImProduktionsprozess',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearDeltaDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'gefaehrlicherAbfall',
            label: 'Gefährlicher Abfall',
            description:
              'Wie wird in dem Unternehmen während der Produktion und Verarbeitung mit gefährlichen Abfällen (brennbar, reaktiv, giftig, radioaktiv) umgegangen?',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'biodiversitaet',
        label: 'Biodiversität',
        fields: [
          {
            name: 'negativeAktivitaetenFuerDieBiologischeVielfalt',
            label: 'Negative Aktivitäten für die biologische Vielfalt',
            description:
              'Hat das Unternehmen Standorte / Betriebe in oder in der Nähe von biodiversitätssensiblen Gebieten, in denen sich die Aktivitäten des Unternehmens negativ auf diese Gebiete auswirken?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'negativeMassnahmenFuerDieBiologischeVielfalt',
            label: 'Negative Maßnahmen für die biologische Vielfalt',
            description:
              'Bitte erläutern Sie Aktivitäten, die sich negativ auf die Biodiversität auswirken. Teilen Sie bitte auch den von der Gruppe/Unternehmen definierte Entwicklungspfad für den Umgang mit diesen Maßnahmen (Zeitplan und Ziel - falls vorhanden) mit uns und wie das Unternehmen den geplanten Entwicklungspfad erreichen möchte.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.umwelt?.biodiversitaet?.negativeAktivitaetenFuerDieBiologischeVielfalt == 'Yes',
          },
          {
            name: 'positiveAktivitaetenFuerDieBiologischeVielfalt',
            label: 'Positive Aktivitäten für die biologische Vielfalt',
            description:
              'Hat das Unternehmen Standorte / Betriebe in oder in der Nähe von biodiversitätssensiblen Gebieten, in denen sich die Aktivitäten des Unternehmens positiv auf diese Gebiete auswirken?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'positiveMassnahmenFuerDieBiologischeVielfalt',
            label: 'Positive Maßnahmen für die biologische Vielfalt',
            description:
              'Bitte erläutern Sie Aktivitäten, die sich positiv auf die Biodiversität auswirken. Teilen Sie bitte auch den von der Gruppe/Unternehmen definierte Entwicklungspfad für die Weiterentwicklung dieser Maßnahmen (Zeitplan und Ziel - falls vorhanden) mit uns und wie das Unternehmen den geplanten Entwicklungspfad erreichen möchte.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.umwelt?.biodiversitaet?.positiveAktivitaetenFuerDieBiologischeVielfalt == 'Yes',
          },
        ],
      },
      {
        name: 'fossileBrennstoffe',
        label: 'Fossile Brennstoffe',
        fields: [
          {
            name: 'einnahmenAusFossilenBrennstoffen',
            label: 'Einnahmen aus fossilen Brennstoffen',
            description:
              'Erzielt das Unternehmen einen Teil seiner Einnahmen aus Aktivitäten im Bereich fossiler Brennstoffe und/oder besitzt das Unternehmen Immobilien, die an der Gewinnung, Lagerung, dem Transport oder der Herstellung fossiler Brennstoffe beteiligt sind?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'berichterstattungEinnahmenAusFossilenBrennstoffen',
            label: 'Berichterstattung Einnahmen aus fossilen Brennstoffen',
            description:
              'Bitte geben Sie den Anteil (%) der Einnahmen aus fossilen Brennstoffen aus den gesamten Einnahmen für das aktuelle Kalenderjahr, die letzten drei Jahre sowie die Prognosen für die kommenden drei Jahre an.',
            options: [
              {
                label: '% der Einnahmen aus fossilen Brennstoffen (in %)',
                value: 'prozentDerEinnahmenAusFossilenBrennstoffen',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearDeltaDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.umwelt?.fossileBrennstoffe?.einnahmenAusFossilenBrennstoffen == 'Yes',
          },
        ],
      },
      {
        name: 'taxonomie',
        label: 'Taxonomie',
        fields: [
          {
            name: 'taxonomieBerichterstattung',
            label: 'Taxonomie Berichterstattung',
            description: 'Wird der EU-Taxonomie Bericht auf Basis NFRD oder auf Basis CSRD erstellt?',
            options: [
              {
                label: 'NFRD',
                value: 'Nfrd',
              },
              {
                label: 'CSRD',
                value: 'Csrd',
              },
            ],

            component: 'SingleSelectFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'euTaxonomieKompassAktivitaeten',
            label: 'EU Taxonomie Kompass Aktivitäten',
            description: 'Welche Aktivitäten gem. dem EU Taxonomie-Kompass übt das Unternehmen aus?',
            options: getActivityNamesAsDropdownOptions(),

            component: 'MultiSelectFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'umsatzInvestitionsaufwandFuerNachhaltigeAktivitaeten',
            label: 'Umsatz/Investitionsaufwand für nachhaltige Aktivitäten',
            description:
              'Wie hoch ist der Umsatz/Investitionsaufwand des Unternehmens aus nachhaltigen Aktivitäten (Mio. €) gemäß einer Definition der EU-Taxonomie? Bitte machen Sie Angaben zu den betrachteten Sektoren und gegebenenfalls zu den Annahmen bzgl. Taxonomie-konformen (aligned) Aktivitäten für das aktuelle Kalenderjahr, die letzten drei Jahre sowie die Prognosen für die kommenden drei Jahre an.',
            options: [
              {
                label: 'Taxonomie geeignet (eligible) nach % Umsatz (in %)',
                value: 'taxonomieGeeignetNachProzentUmsatz',
              },
              {
                label: 'Taxonomie geeignet (eligible) nach % Capex (in %)',
                value: 'taxonomieGeeignetNachProzentCapex',
              },
              {
                label: 'Taxonomie konform (aligned) nach % Umsatz (in %)',
                value: 'taxonomieKonformNachProzentUmsatz',
              },
              {
                label: 'Taxonomie konform (aligned) nach % Capex (in %)',
                value: 'taxonomieKonformNachProzentCapex',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearDeltaDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
    ],
  },
  {
    name: 'soziales',
    label: 'Soziales',
    color: '',
    showIf: (): boolean => true,
    subcategories: [
      {
        name: 'unternehmensstrukturaenderungen',
        label: 'Unternehmensstrukturänderungen',
        fields: [
          {
            name: 'vorhandenseinKuerzlicherAenderungenDerUnternehmensstruktur',
            label: 'Vorhandensein kürzlicher Änderungen der Unternehmensstruktur',
            description:
              'Gab es kürzlich eine Veränderung im Unternehmen / in der Gruppe (Umstrukturierung, Verkauf oder Übernahme)?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'anzahlUnbefristeterVertraegeInDeutschland',
            label: 'Anzahl unbefristeter Verträge in Deutschland',
            description: 'Bitte teilen Sie mit uns wieviele unbefristete Verträge es insgesamt in Deutschland gibt.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.soziales?.unternehmensstrukturaenderungen
                ?.vorhandenseinKuerzlicherAenderungenDerUnternehmensstruktur == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlDerVonEinemVerkaufBetroffenenUnbefristetenVertraegeInDeutschland',
            label: 'Anzahl der von einem Verkauf betroffenen unbefristeten Verträge in Deutschland ',
            description:
              'Bitte teilen Sie mit uns wieviele unbefristete Verträge in Deutschland von einem etwaigen Verkauf betroffen waren.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.soziales?.unternehmensstrukturaenderungen
                ?.vorhandenseinKuerzlicherAenderungenDerUnternehmensstruktur == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlDerVonEinerAkquisitionBetroffenenUnbefristetenVertraegeInDeutschland',
            label: 'Anzahl der von einer Akquisition betroffenen unbefristeten Verträge in Deutschland ',
            description:
              'Bitte teilen Sie mit uns wieviele unbefristete Verträge in Deutschland von einer etwaigen Akquisition betroffen waren.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.soziales?.unternehmensstrukturaenderungen
                ?.vorhandenseinKuerzlicherAenderungenDerUnternehmensstruktur == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlUnbefristeterVertraegeInDerGesamtgruppe',
            label: 'Anzahl unbefristeter Verträge in der Gesamtgruppe',
            description:
              'Bitte teilen Sie mit uns wieviele unbefristete Verträge es insgesamt in der Gesamtgruppe gibt.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.soziales?.unternehmensstrukturaenderungen
                ?.vorhandenseinKuerzlicherAenderungenDerUnternehmensstruktur == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlDerVonEinemVerkaufBetroffenenUnbefristetenVertraegeInDerGesamtgruppe',
            label: 'Anzahl der von einem Verkauf betroffenen unbefristeten Verträge in der Gesamtgruppe',
            description:
              'Bitte teilen Sie mit uns wieviele unbefristete Verträge in der Gesamtgruppe von einem etwaigen Verkauf betroffen waren.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.soziales?.unternehmensstrukturaenderungen
                ?.vorhandenseinKuerzlicherAenderungenDerUnternehmensstruktur == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlDerVonEinerAkquisitionBetroffenenUnbefristetenVertraegeInDerGesamtgruppe',
            label: 'Anzahl der von einer Akquisition betroffenen unbefristeten Verträge in der Gesamtgruppe',
            description:
              'Bitte teilen Sie mit uns wieviele unbefristete Verträge in der Gesamtgruppe von einer etwaigen Akquisition betroffen waren.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.soziales?.unternehmensstrukturaenderungen
                ?.vorhandenseinKuerzlicherAenderungenDerUnternehmensstruktur == 'Yes',
            validation: 'integer',
          },
          {
            name: 'auswirkungenAufAnteilBefristerVertraegeUndFluktuation',
            label: 'Auswirkungen auf Anteil befrister Verträge und Fluktuation',
            description:
              'Bitte geben Sie die Anzahl der befristeten Verträge sowie die Fluktuation (%) für die letzten drei Jahre an.',
            options: [
              {
                label: '# der befristeten Verträge',
                value: 'anzahlDerBefristetenVertraege',
              },
              {
                label: 'Fluktuation (in %)',
                value: 'fluktuation',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearPastDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.soziales?.unternehmensstrukturaenderungen
                ?.vorhandenseinKuerzlicherAenderungenDerUnternehmensstruktur == 'Yes',
          },
        ],
      },
      {
        name: 'sicherheitUndWeiterbildung',
        label: 'Sicherheit und Weiterbildung',
        fields: [
          {
            name: 'sicherheitsmassnahmenFuerMitarbeiter',
            label: 'Sicherheitsmaßnahmen für Mitarbeiter',
            description:
              'Welche Maßnahmen werden ergriffen, um die Gesundheit und Sicherheit der Mitarbeiter des Unternehmens zu verbessern?',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'unfallrate',
            label: 'Unfallrate',
            description:
              'Wie hoch war die Häufigkeitsrate von Arbeitsunfällen mit Zeitverlust für die letzten drei Jahre?',
            options: [
              {
                label: 'Häufigkeitsrate von Arbeitsunfällen mit Zeitverlust',
                value: 'haeufigkeitsrateVonArbeitsunfaellenMitZeitverlust',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearPastDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'budgetFuerSchulungAusbildung',
            label: 'Budget für Schulung/Ausbildung',
            description:
              'Bitte geben Sie an wie hoch das Budget ist, das pro Mitarbeiter und Jahr für Schulungen/Fortbildungen in den letzten drei Jahren ausgegeben wurde.',
            options: [
              {
                label: 'Budget pro Mitarbeiter (in €)',
                value: 'budgetProMitarbeiter',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearPastDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'einkommensgleichheit',
        label: 'Einkommensgleichheit',
        fields: [
          {
            name: 'ueberwachungDerEinkommensungleichheit',
            label: 'Überwachung der Einkommensungleichheit',
            description:
              'Bitte geben Sie das unbereinigte geschlechtsspezifische Lohngefälle, das Einkommensungleichheitsverhältnis, sowie das CEO-Einkommensungleichheitsverhältnis für die letzten drei Jahre an.',
            options: [
              {
                label: 'Unbereinigtes geschlechtsspezifisches Lohngefälle (in %)',
                value: 'unbereinigtesGeschlechtsspezifischesLohngefaelle',
              },
              {
                label: 'Einkommensungleichheitsverhältnis (in %)',
                value: 'einkommensungleichheitsverhaeltnis',
              },
              {
                label: 'CEO-Einkommensungleichheitsverhältnis (in %)',
                value: 'ceoEinkommensungleichheitsverhaeltnis',
              },
            ],

            component: 'EsgQuestionnaireYearlyDecimalTimeseriesThreeYearPastDataFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'massnahmenZurVerbesserungDerEinkommensungleichheit',
            label: 'Maßnahmen zur Verbesserung der Einkommensungleichheit',
            description:
              'Wie überwacht das Unternehmen die Einkommens(un)gleichheit und welche Maßnahmen wurden ergriffen, um die Einkommensungleichheit abzustellen?',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'geschlechterdiversitaet',
        label: 'Geschlechterdiversität',
        fields: [
          {
            name: 'mitarbeiterAufTopManagementEbene',
            label: 'Mitarbeiter auf Top-Management Ebene',
            description: 'Geben Sie bitte an wieviele Personen eine Top-Management Position innehaben.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'frauenAufTopManagementEbene',
            label: 'Frauen auf Top-Management-Ebene',
            description: 'Geben Sie bitte an wieviele Frauen eine Top-Management Position innehaben.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'mitgliederGeschaeftsfuehrung',
            label: 'Mitglieder Geschäftsführung',
            description: 'Geben Sie bitte an wieviele Mitglieder die Geschäftsführung hat.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'frauenInDerGeschaeftsfuehrung',
            label: 'Frauen in der Geschäftsführung',
            description: 'Geben Sie bitte an wieviele Frauen in der Geschäftsführung sind.',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'definitionTopManagement',
            label: 'Definition Top-Management',
            description: 'Bitte geben Sie Ihre Definition von "Top-Management".',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'einhaltungRechtlicherVorgaben',
            label: 'Einhaltung rechtlicher Vorgaben',
            description:
              'Welche Maßnahmen wurden ergriffen, um das geltende Recht in Bezug auf die Geschlechterdiversität von Exekutivinstanzen einzuhalten?',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'audit',
        label: 'Audit',
        fields: [
          {
            name: 'auditsZurEinhaltungVonArbeitsstandards',
            label: 'Audits zur Einhaltung von Arbeitsstandards',
            description:
              'Führt das Unternehmen interne oder externe Audits durch, um die Einhaltung der Arbeitsnormen durch das Unternehmen zu bewerten?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'artDesAudits',
            label: 'Art des Audits',
            description: 'Wie werden die Audits zur Einhaltung von Arbeitsstandards durchgeführt?',
            options: [
              {
                label: 'Interne Anhörung',
                value: 'InterneAnhoerung',
              },
              {
                label: 'Prüfung durch Dritte',
                value: 'PruefungDurchDritte',
              },
              {
                label: 'Sowohl intern als auch von Drittanbietern',
                value: 'SowohlInternAlsAuchVonDrittanbietern',
              },
            ],

            component: 'SingleSelectFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.soziales?.audit?.auditsZurEinhaltungVonArbeitsstandards == 'Yes',
          },
          {
            name: 'auditErgebnisse',
            label: 'Audit Ergebnisse',
            description: 'Bitte geben Sie Informationen über das letzte Audit an.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.soziales?.audit?.auditsZurEinhaltungVonArbeitsstandards == 'Yes',
          },
        ],
      },
    ],
  },
  {
    name: 'unternehmensfuehrungGovernance',
    label: 'Unternehmensführung/ Governance',
    color: '',
    showIf: (): boolean => true,
    subcategories: [
      {
        name: 'aufsichtsrat',
        label: 'Aufsichtsrat',
        fields: [
          {
            name: 'anzahlDerMitgliederImAufsichtsrat',
            label: 'Anzahl der Mitglieder im Aufsichtsrat',
            description: 'Wieviele Mitglieder hat der Aufsichtsrat?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlUnabhaengigerMitgliederImAufsichtsrat',
            label: 'Anzahl unabhängiger Mitglieder im Aufsichtsrat',
            description: 'Wieviele unabhängige Mitglieder hat der Aufsichtsrat?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlVonFrauenImAufsichtsrat',
            label: 'Anzahl von Frauen im Aufsichtsrat',
            description: 'Wieviele Frauen sind im Aufsichtsrat?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
        ],
      },
      {
        name: 'verguetungsausschuss',
        label: 'Vergütungsausschuss',
        fields: [
          {
            name: 'anzahlDerMitgliederImVerguetungsausschuss',
            label: 'Anzahl der Mitglieder im Vergütungsausschuss',
            description: 'Wieviele Mitglieder hat der Vergütungsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlUnabhaengigerMitgliederImVerguetungsausschuss',
            label: 'Anzahl unabhängiger Mitglieder im Vergütungsausschuss',
            description: 'Wieviele unabhängige Mitglieder hat der Vergütungsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlVonFrauenImVerguetungsausschuss',
            label: 'Anzahl von Frauen im Vergütungsausschuss',
            description: 'Wieviele Frauen sind im Vergütungsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
        ],
      },
      {
        name: 'nominierungsausschuss',
        label: 'Nominierungsausschuss',
        fields: [
          {
            name: 'anzahlDerMitgliederImNominierungsausschuss',
            label: 'Anzahl der Mitglieder im Nominierungsausschuss',
            description: 'Wieviele Mitglieder hat der Nominierungsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlUnabhaengigerMitgliederImNominierungsausschuss',
            label: 'Anzahl unabhängiger Mitglieder im Nominierungsausschuss',
            description: 'Wieviele unabhängige Mitglieder hat der Nominierungsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlVonFrauenImVerguetungsausschuss',
            label: 'Anzahl von Frauen im Vergütungsausschuss',
            description: 'Wieviele Frauen sind im Nominierungsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
        ],
      },
      {
        name: 'pruefungsausschuss',
        label: 'Prüfungsausschuss',
        fields: [
          {
            name: 'anzahlDerMitgliederImPruefungsausschuss',
            label: 'Anzahl der Mitglieder im Prüfungsausschuss',
            description: 'Wieviele Mitglieder hat der Prüfungsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlUnabhaengigerMitgliederImPruefungsausschuss',
            label: 'Anzahl unabhängiger Mitglieder im Prüfungsausschuss',
            description: 'Wieviele unabhängige Mitglieder hat der Prüfungsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlVonFrauenImPruefungsausschuss',
            label: 'Anzahl von Frauen im Prüfungsausschuss',
            description: 'Wieviele Frauen sind im Prüfungsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
        ],
      },
      {
        name: 'nachhaltigkeitsausschuss',
        label: 'Nachhaltigkeitsausschuss',
        fields: [
          {
            name: 'anzahlDerMitgliederImNachhaltigkeitsausschuss',
            label: 'Anzahl der Mitglieder im Nachhaltigkeitsausschuss',
            description: 'Wieviele Mitglieder hat der Nachhaltigkeitsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlUnabhaengigerMitgliederImNachhaltigkeitsausschuss',
            label: 'Anzahl unabhängiger Mitglieder im Nachhaltigkeitsausschuss',
            description: 'Wieviele unabhängige Mitglieder hat der Nachhaltigkeitsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
          {
            name: 'anzahlVonFrauenImNachhaltigkeitsausschuss',
            label: 'Anzahl von Frauen im Nachhaltigkeitsausschuss',
            description: 'Wieviele Frauen sind im Nachhaltigkeitsausschuss?',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
            validation: 'integer',
          },
        ],
      },
      {
        name: 'sonstige',
        label: 'Sonstige',
        fields: [
          {
            name: 'wirtschaftspruefer',
            label: 'Wirtschaftsprüfer',

            component: 'InputTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'trennungVonCeoOderVorsitzenden',
            label: 'Trennung von CEO oder Vorsitzenden',
            description:
              'Hat sich das Unternehmen im aktuellen Jahr der Berichterstattung von CEO/Vorsitzenden getrennt?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'amtszeitBisZurTrennung',
            label: 'Amtszeit bis zur Trennung',
            description: 'Wieviele Jahre war der/die CEO/Vorsitzende(r) im Amt?',

            unit: 'Jahre',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.unternehmensfuehrungGovernance?.sonstige?.trennungVonCeoOderVorsitzenden == 'Yes',
            validation: 'integer',
          },
        ],
      },
      {
        name: 'stakeholder',
        label: 'Stakeholder',
        fields: [
          {
            name: 'einbeziehungVonStakeholdern',
            label: 'Einbeziehung von Stakeholdern',
            description: 'Gibt es einen kontinuierlichen Prozess des Dialogs mit den Stakeholdern des Unternehmens?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'prozessDerEinbeziehungVonStakeholdern',
            label: 'Prozess der Einbeziehung von Stakeholdern',
            description:
              'Bitte geben Sie Einzelheiten zu einem solchen Prozess an, z.B. eine Umfrage zur Bewertung der Mitarbeiter- oder Kundenzufriedenheit. Falls zutreffend, teilen Sie uns bitte die wichtigsten Schlussfolgerungen mit.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.unternehmensfuehrungGovernance?.stakeholder?.einbeziehungVonStakeholdern == 'Yes',
          },
          {
            name: 'mechanismenZurAusrichtungAufStakeholder',
            label: 'Mechanismen zur Ausrichtung auf Stakeholder',
            description:
              'Welche Mechanismen gibt es derzeit, um sicherzustellen, dass die Stakeholder im besten Interesse des Unternehmens handeln? Bitte erläutern Sie (falls zutreffend) die Beteiligungsmechanismen, verschiedene Anreizsysteme usw.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.unternehmensfuehrungGovernance?.stakeholder?.einbeziehungVonStakeholdern == 'Yes',
          },
        ],
      },
      {
        name: 'unternehmensrichtlinien',
        label: 'Unternehmensrichtlinien',
        fields: [
          {
            name: 'veroeffentlichteUnternehmensrichtlinien',
            label: 'Veröffentlichte Unternehmensrichtlinien',
            description: 'Welche Richtlinien sind im Unternehmen veröffentlicht?',
            options: [
              {
                label: 'Anti-Korruption',
                value: 'AntiKorruption',
              },
              {
                label: 'Verhaltenskodex',
                value: 'Verhaltenskodex',
              },
              {
                label: 'Interessenkonflikte',
                value: 'Interessenkonflikte',
              },
              {
                label: 'Datenschutz',
                value: 'Datenschutz',
              },
              {
                label: 'Diversität & Inklusion',
                value: 'DiversitaetAndInklusion',
              },
              {
                label: 'Faire Behandlung von Kunden',
                value: 'FaireBehandlungVonKunden',
              },
              {
                label: 'Zwangsarbeit',
                value: 'Zwangsarbeit',
              },
              {
                label: 'Gesundheit und Sicherheit',
                value: 'GesundheitUndSicherheit',
              },
              {
                label: 'Mgt von Umweltgefahren',
                value: 'MgtVonUmweltgefahren',
              },
              {
                label: 'Verantwortungsvolles Marketing',
                value: 'VerantwortungsvollesMarketing',
              },
              {
                label: 'Whistleblowing',
                value: 'Whistleblowing',
              },
              {
                label: 'other',
                value: 'Other',
              },
            ],

            component: 'MultiSelectFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'weitereVeroeffentlicheUnternehmensrichtlinien',
            label: 'Weitere veröffentliche Unternehmensrichtlinien',
            description: 'Bitte nennen Sie weitere wichtige Richtlinien, falls diese nicht angegeben sind.',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
        ],
      },
      {
        name: 'lieferantenauswahl',
        label: 'Lieferantenauswahl',
        fields: [
          {
            name: 'esgKriterienUndUeberwachungDerLieferanten',
            label: 'ESG-Kriterien und Überwachung der Lieferanten',
            description:
              'Wendet das Unternehmen ESG-Kriterien bei der Auswahl seiner Lieferanten an, einschließlich einer Bestandsaufnahme der Lieferkette?',

            component: 'YesNoFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.general?.masterData?.berichtspflichtUndEinwilligungZurVeroeffentlichung == 'Yes',
          },
          {
            name: 'auswahlkriterien',
            label: 'Auswahlkriterien',
            description:
              'Bitte nennen Sie die Auswahlkriterien und erläutern Sie, wie diese Kriterien im Laufe der Zeit überwacht/geprüft werden. Bezieht das Unternehmen beispielsweise Rohstoffe aus Gebieten, in denen umstrittene Abholzungsaktivitäten stattfinden (z.B. Soja, Palmöl, Tropenholz, Holz oder industrielle Viehzucht)?',

            component: 'FreeTextFormField',
            required: false,
            showIf: (dataset: EsgQuestionnaireData): boolean =>
              dataset.unternehmensfuehrungGovernance?.lieferantenauswahl?.esgKriterienUndUeberwachungDerLieferanten ==
              'Yes',
          },
        ],
      },
    ],
  },
] as Category[];
