// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type AxiosPromise, type AxiosRequestConfig, type AxiosInstance } from 'axios';
import { type CompanyAssociatedData } from '@/api-models/CompanyAssociatedData';
import {
  type Configuration,
  type DataMetaInformation,
  type EsgDatenkatalogData,
  EsgDatenkatalogDataControllerApi,
} from '@clients/backend';
import { type PublicFrameworkDataApi } from '@/utils/api/UnifiedFrameworkDataApi';
import { type DataAndMetaInformation } from '@/api-models/DataAndMetaInformation';

export class EsgDatenkatalogApiClient implements PublicFrameworkDataApi<EsgDatenkatalogData> {
  private readonly openApiDataController: EsgDatenkatalogDataControllerApi;

  constructor(configuration: Configuration | undefined, axiosInstance: AxiosInstance | undefined) {
    this.openApiDataController = new EsgDatenkatalogDataControllerApi(configuration, undefined, axiosInstance);
  }

  getAllCompanyData(
    companyId: string,
    showOnlyActive?: boolean,
    reportingPeriod?: string,
    options?: AxiosRequestConfig
  ): AxiosPromise<DataAndMetaInformation<EsgDatenkatalogData>[]> {
    return this.openApiDataController.getAllCompanyEsgDatenkatalogData(
      companyId,
      showOnlyActive,
      reportingPeriod,
      options
    );
  }

  getFrameworkData(
    dataId: string,
    options?: AxiosRequestConfig
  ): AxiosPromise<CompanyAssociatedData<EsgDatenkatalogData>> {
    return this.openApiDataController.getCompanyAssociatedEsgDatenkatalogData(dataId, options);
  }

  postFrameworkData(
    data: CompanyAssociatedData<EsgDatenkatalogData>,
    bypassQa?: boolean,
    options?: AxiosRequestConfig
  ): AxiosPromise<DataMetaInformation> {
    return this.openApiDataController.postCompanyAssociatedEsgDatenkatalogData(data, bypassQa, options);
  }
}
