/**
 * An enum that holds the nuclear and gas economic activities with their names as values
 */
export enum ActivityName {
  taxonomyAlignedShareDenominatorNAndG426 = " Proportion of taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyAlignedShareDenominatorNAndG427 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyAlignedShareDenominatorNAndG428 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyAlignedShareDenominatorNAndG429 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyAlignedShareDenominatorNAndG430 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyAlignedShareDenominatorNAndG431 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyAlignedShareDenominatorOtherActivities = "Proportion of other taxonomy-aligned economic activities not referred to in rows 1 to 6 above in the denominator of the applicable KPI ",
  taxonomyAlignedShareDenominator = "Total applicable KPI ",
  taxonomyAlignedShareNumeratorNAndG426 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI",
  taxonomyAlignedShareNumeratorNAndG427 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI",
  taxonomyAlignedShareNumeratorNAndG428 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI",
  taxonomyAlignedShareNumeratorNAndG429 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI",
  taxonomyAlignedShareNumeratorNAndG430 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI",
  taxonomyAlignedShareNumeratorNAndG431 = "Proportion of taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI",
  taxonomyAlignedShareNumeratorOtherActivities = "Proportion of other taxonomy-aligned economic activities not referred to in rows 1 to 6 above in the numerator of the applicable KPI ",
  taxonomyAlignedShareNumerator = "Total proportion of taxonomy-aligned economic activities in the numerator of the applicable KPI ",
  taxonomyEligibleButNotAlignedShareNAndG426 = "Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation",
  taxonomyEligibleButNotAlignedShareNAndG427 = "Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation",
  taxonomyEligibleButNotAlignedShareNAndG428 = "Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation",
  taxonomyEligibleButNotAlignedShareNAndG429 = "Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation",
  taxonomyEligibleButNotAlignedShareNAndG430 = "Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation",
  taxonomyEligibleButNotAlignedShareNAndG431 = "Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation",
  taxonomyEligibleButNotAlignedShareOtherActivities = "Proportion of other taxonomy-eligible but not taxonomy-aligned economic activities not referred to in rows 1 to 6 above in the denominator of the applicable KPI ",
  taxonomyEligibleButNotAlignedShare = "Total proportion of taxonomy eligible but not taxonomy-aligned economic activities in the denominator of the applicable KPI ",
  taxonomyNonEligibleShareNAndG426 ="Proportion of economic activity referred to in row 1 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyNonEligibleShareNAndG427 ="Proportion of economic activity referred to in row 2 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyNonEligibleShareNAndG428 = "Proportion of economic activity referred to in row 3 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyNonEligibleShareNAndG429 = "Proportion of economic activity referred to in row 4 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyNonEligibleShareNAndG430 = "Proportion of economic activity referred to in row 5 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyNonEligibleShareNAndG431 = "Proportion of economic activity referred to in row 6 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI",
  taxonomyNonEligibleShareOtherActivities  = "Proportion of other taxonomy-non-eligible economic activities not referred to in rows 1 to 6 above in the denominator of the applicable KPI ",
  taxonomyNonEligibleShare = "Total proportion of taxonomy-non-eligible economic activities in the denominator of the applicable KPI "
}
