/**
 * Fieldname-Tooltip Mapping for the Nuclear and Gas Framework. Generated by DatalandDevTools
 */
export const nuclearAndGasTooltipMapping = {
  taxonomyAlignedShareDenominatorClimateChangeMitigationAndClimateChangeAdaptationNAndG426:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeMitigationNAndG426:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeAdaptationNAndG426:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorClimateChangeMitigationAndClimateChangeAdaptationNAndG427:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeMitigationNAndG427:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeAdaptationNAndG427:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorClimateChangeMitigationAndClimateChangeAdaptationNAndG428:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeMitigationNAndG428:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeAdaptationNAndG428:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorClimateChangeMitigationAndClimateChangeAdaptationNAndG429:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeMitigationNAndG429:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeAdaptationNAndG429:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorClimateChangeMitigationAndClimateChangeAdaptationNAndG430:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeMitigationNAndG430:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeAdaptationNAndG430:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorClimateChangeMitigationAndClimateChangeAdaptationNAndG431:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeMitigationNAndG431:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeAdaptationNAndG431:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorClimateChangeMitigationAndClimateChangeAdaptationOtherActivities:
    'Proportion of other taxonomy-aligned economic activities not referred to in Sections 4.26-4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeMitigationOtherActivities:
    'Proportion of other taxonomy-aligned economic activities not referred to in Sections 4.26-4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeAdaptationOtherActivities:
    'Proportion of other taxonomy-aligned economic activities not referred to in Sections 4.26-4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorClimateChangeMitigationAndClimateChangeAdaptation:
    'Total applicable KPI. Taxonomy-aligned share (denominator) substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeMitigation:
    'Total applicable KPI. Taxonomy-aligned share (denominator) substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareDenominatorSubstantiallyContributingToClimateChangeAdaptation:
    'Total applicable KPI. Taxonomy-aligned share (denominator) substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorClimateChangeMitigationAndClimateChangeAdaptationNAndG426:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeMitigationNAndG426:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeAdaptationNAndG426:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorClimateChangeMitigationAndClimateChangeAdaptationNAndG427:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeMitigationNAndG427:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeAdaptationNAndG427:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorClimateChangeMitigationAndClimateChangeAdaptationNAndG428:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeMitigationNAndG428:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeAdaptationNAndG428:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorClimateChangeMitigationAndClimateChangeAdaptationNAndG429:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeMitigationNAndG429:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeAdaptationNAndG429:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorClimateChangeMitigationAndClimateChangeAdaptationNAndG430:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeMitigationNAndG430:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeAdaptationNAndG430:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorClimateChangeMitigationAndClimateChangeAdaptationNAndG431:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeMitigationNAndG431:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeAdaptationNAndG431:
    'Proportion of taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the numerator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorClimateChangeMitigationAndClimateChangeAdaptationOtherActivities:
    'Proportion of other taxonomy-aligned economic activities not referred to in rows 1 to 6 above in the numerator of the applicable KPI to Climate Change Mitigation and Climate Change Adaptation  - other activities.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeMitigationOtherActivities:
    'Proportion of other taxonomy-aligned economic activities not referred to in rows 1 to 6 above in the numerator of the applicable KPI substantially contributing to Climate Change Mitigation - other activities.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeAdaptationOtherActivities:
    'Proportion of other taxonomy-aligned economic activities not referred to in rows 1 to 6 above in the numerator of the applicable KPI substantially contributing to Climate Change Adaptation - other activities.',
  taxonomyAlignedShareNumeratorClimateChangeMitigationAndClimateChangeAdaptation:
    'Total proportion of taxonomy-aligned economic activities in the numerator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeMitigation:
    'Total proportion of taxonomy-aligned economic activities in the numerator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyAlignedShareNumeratorSubstantiallyContributingToClimateChangeAdaptation:
    'Total proportion of taxonomy-aligned economic activities in the numerator of the applicable KP substantially contributing to Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareClimateChangeMitigationAndClimateChangeAdaptationNAndG426:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeMitigationNAndG426:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeAdaptationNAndG426:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareClimateChangeMitigationAndClimateChangeAdaptationNAndG427:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeMitigationNAndG427:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeAdaptationNAndG427:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareClimateChangeMitigationAndClimateChangeAdaptationNAndG428:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeMitigationNAndG428:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeAdaptationNAndG428:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareClimateChangeMitigationAndClimateChangeAdaptationNAndG429:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeMitigationNAndG429:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeAdaptationNAndG429:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareClimateChangeMitigationAndClimateChangeAdaptationNAndG430:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeMitigationNAndG430:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeAdaptationNAndG430:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareClimateChangeMitigationAndClimateChangeAdaptationNAndG431:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeMitigationNAndG431:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeAdaptationNAndG431:
    'Proportion of taxonomy-eligible but not taxonomy-aligned economic activity referred to in Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareClimateChangeMitigationAndClimateChangeAdaptationOtherActivities:
    'Proportion of other taxonomy-eligible but not taxonomy-aligned economic activities not referred to in rows 1 to 6 above in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation  - other activities.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeMitigationOtherActivities:
    'Proportion of other taxonomy-eligible but not taxonomy-aligned economic activities not referred to in rows 1 to 6 above in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation - other activities.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeAdaptationOtherActivities:
    'Proportion of other taxonomy-eligible but not taxonomy-aligned economic activities not referred to in rows 1 to 6 above in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation - other activities.',
  taxonomyEligibleButNotAlignedShareClimateChangeMitigationAndClimateChangeAdaptation:
    'Total proportion of taxonomy-eligible but not taxonomy-aligned economic activities in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeMitigation:
    'Total proportion of taxonomy-eligible but not taxonomy-aligned economic activities in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation.',
  taxonomyEligibleButNotAlignedShareSubstantiallyContributingToClimateChangeAdaptation:
    'Total proportion of taxonomy-eligible but not taxonomy-aligned economic activities in the denominator of the applicable KPI substantially contributing to Climate Change Adaptation.',
  taxonomyNonEligibleShareNAndG426:
    'Proportion of economic activity referred to in row 1 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.26 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyNonEligibleShareNAndG427:
    'Proportion of economic activity referred to in row 2 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.27 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyNonEligibleShareNAndG428:
    'Proportion of economic activity referred to in row 3 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.28 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyNonEligibleShareNAndG429:
    'Proportion of economic activity referred to in row 4 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.29 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyNonEligibleShareNAndG430:
    'Proportion of economic activity referred to in row 5 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.30 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyNonEligibleShareNAndG431:
    'Proportion of economic activity referred to in row 6 of Template 1 that is taxonomy-non-eligible in accordance with Section 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
  taxonomyNonEligibleShareOtherActivities:
    'Proportion of other taxonomy-non-eligible economic activities not referred to in rows 1 to 6 above in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation - other activities.',
  taxonomyNonEligibleShare:
    'Total proportion of taxonomy-non-eligible economic activities in the denominator of the applicable KPI substantially contributing to Climate Change Mitigation and Climate Change Adaptation.',
};
