// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials.model.creditInstitution

import jakarta.validation.Valid
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials.model.creditInstitution
    .capexBasedGreenAssetRatioStock.EuTaxonomyFinancialsCreditinstitutionCapexBasedGreenAssetRatioStock
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials.model.creditInstitution.tradingAndLoans
    .EuTaxonomyFinancialsCreditinstitutionTradingAndLoans
import org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials.model.creditInstitution
    .turnoverBasedGreenAssetRatioStock.EuTaxonomyFinancialsCreditinstitutionTurnoverBasedGreenAssetRatioStock

/**
 * The QA-model for the CreditInstitution section
 */
data class EuTaxonomyFinancialsCreditInstitution(
    @field:Valid()
    val tradingAndLoans: EuTaxonomyFinancialsCreditinstitutionTradingAndLoans? = null,

    @field:Valid()
    val turnoverBasedGreenAssetRatioStock:
    EuTaxonomyFinancialsCreditinstitutionTurnoverBasedGreenAssetRatioStock? = null,

    @field:Valid()
    val capexBasedGreenAssetRatioStock: EuTaxonomyFinancialsCreditinstitutionCapexBasedGreenAssetRatioStock? = null,

)
