export const gdvDataModel = [    {
        name: "general",
        label: "General",
        color: " ", 
        showIf: ():boolean => true,
        subcategories: [    {
            name: "masterData",
            label: "Master Data",
            color: " ", 
            showIf: ():boolean => true,
            subcategories: [    {
                name: "berichts-pflicht",
                label: "Berichts-Pflicht",
                description: "Ist das Unternehmen berichtspflichtig?",
                unit: "",
                uploadComponentName: "YesNoFormField",
                required: false,
                showIf: ():boolean => true, 
                validation: "",
                },
            {
                name: "(gültigkeits)Datum",
                label: "(Gültigkeits) Datum",
                description: "Datum bis wann die Information gültig ist",
                unit: "",
                uploadComponentName: "DateFormField",
                required: false,
                showIf: ():boolean => true, 
                validation: "",
                },
            ],
            },
        ],
        },
    {
        name: "allgemein",
        label: "Allgemein",
        color: " ", 
        showIf: ():boolean => true,
        subcategories: [    {
            name: "esg-ziele",
            label: "ESG-Ziele",
            description: "Hat das Unternehmen spezifische ESG-Ziele/Engagements? Werden bspw. spezifische Ziele / Maßnahmen ergriffen, um das 1,5 Grad Ziel zu erreichen?",
            unit: "",
            uploadComponentName: "YesNoFormField",
            required: false,
            showIf: ():boolean => true, 
            validation: "",
            },
        {
            name: "ziele",
            label: "Ziele",
            description: "Bitte geben Sie eine genaue Beschreibung der ESG-Ziele.",
            unit: "",
            uploadComponentName: "InputTextFormField",
            required: false,
            showIf: ():boolean => true, 
            validation: "",
            },
        {
            name: "investitionen",
            label: "Investitionen",
            description: "Bitte geben Sie an wieviele Budgets/Vollzeitäquivalente für das Erreichen der ESG-Ziele zugewiesen wurden.",
            unit: "",
            uploadComponentName: "InputTextFormField",
            required: false,
            showIf: ():boolean => true, 
            validation: "",
            },
        {
            name: "sektorMitHohenKlimaauswirkungen",
            label: "Sektor mit hohen Klimaauswirkungen",
            description: "Kann das Unternehmen einem oder mehreren Sektoren mit hohen Klimaauswirkungen zugeordnet werden?",
            unit: "",
            uploadComponentName: "YesNoFormField",
            required: false,
            showIf: ():boolean => true, 
            validation: "",
            },
        {
            name: "sektor",
            label: "Sektor",
            description: "Bitte geben Sie an, zu welchen Sektoren (mit hohen Klimaauswirkungen) das Unternehmen zugeordnet werden kann.",
            unit: "",
            uploadComponentName: "MultiSelectFormField",
            required: false,
            showIf: ():boolean => true, 
            validation: "",
            },
        {
            name: "nachhaltigkeitsbericht",
            label: "Nachhaltigkeitsbericht",
            description: "Erstellt das Unternehmen Nachhaltigkeits- oder ESG-Berichte?",
            unit: "",
            uploadComponentName: "YesNoFormField",
            required: false,
            showIf: ():boolean => true, 
            validation: "",
            },
        {
            name: "frequenzDerBerichterstattung",
            label: "Frequenz der Berichterstattung",
    
            unit: "",
            uploadComponentName: "SingleSelectFormField",
            required: false,
            showIf: ():boolean => true, 
            validation: "",
            },
        ],
        },
    ];

