// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type Category } from '@/utils/GenericFrameworkTypes';

export const nuclearAndGasDataModel = [
  {
    name: 'general',
    label: 'General',
    color: '',
    showIf: (): boolean => true,
    subcategories: [
      {
        name: 'nuclearEnergyRelatedActivitiesSection426',
        label: 'Nuclear Energy related Activities (Section 4.26)',
        fields: [],
      },
      {
        name: 'nuclearEnergyRelatedActivitiesSection427',
        label: 'Nuclear Energy related Activities (Section 4.27)',
        fields: [],
      },
      {
        name: 'nuclearEnergyRelatedActivitiesSection428',
        label: 'Nuclear Energy related Activities (Section 4.28)',
        fields: [],
      },
      {
        name: 'fossilGasRelatedActivitiesSection429',
        label: 'Fossil Gas related Activities (Section 4.29)',
        fields: [],
      },
      {
        name: 'fossilGasRelatedActivitiesSection430',
        label: 'Fossil Gas related Activities (Section 4.30)',
        fields: [],
      },
      {
        name: 'fossilGasRelatedActivitiesSection431',
        label: 'Fossil Gas related Activities (Section 4.31)',
        fields: [],
      },
    ],
  },
  {
    name: 'taxonomyAlignedDenominator',
    label: 'Taxonomy-aligned (denominator)',
    color: '',
    showIf: (): boolean => true,
    subcategories: [],
  },
  {
    name: 'taxonomyAlignedNumerator',
    label: 'Taxonomy-aligned (numerator)',
    color: '',
    showIf: (): boolean => true,
    subcategories: [],
  },
  {
    name: 'taxonomyEligibleButNotAligned',
    label: 'Taxonomy-eligible but not aligned',
    color: '',
    showIf: (): boolean => true,
    subcategories: [],
  },
  {
    name: 'taxonomyNonEligible',
    label: 'Taxonomy-non-eligible',
    color: '',
    showIf: (): boolean => true,
    subcategories: [],
  },
] as Category[];
