// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.general.general

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.custom.AssuranceDataPoint
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import org.dataland.datalandbackend.model.documents.CompanyReport
import org.dataland.datalandbackend.model.enums.commons.YesNo
import org.dataland.datalandbackend.utils.JsonExampleFormattingConstants
import org.dataland.datalandbackend.validator.MinimumValue
import java.math.BigDecimal
import java.time.LocalDate

/**
 * The data-model for the General section
 */
@Suppress("MaxLineLength")
data class EutaxonomyFinancialsGeneralGeneral(
    @field:Valid()
    val fiscalYearDeviation: ExtendedDataPoint<EutaxonomyFinancialsGeneralGeneralFiscalYearDeviationOptions?>? = null,

    @field:Valid()
    val fiscalYearEnd: ExtendedDataPoint<LocalDate?>? = null,

    @field:Schema(example = JsonExampleFormattingConstants.REFERENCED_REPORTS_DEFAULT_VALUE)
    @field:Valid()
    val referencedReports: Map<String, CompanyReport>? = null,

    @field:Valid()
    val areAllGroupEntitiesCovered: ExtendedDataPoint<YesNo?>? = null,

    @field:MinimumValue(minimumValue = 0)
    @field:Valid()
    val numberOfEmployees: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val isNfrdMandatory: ExtendedDataPoint<YesNo?>? = null,

    @field:Valid()
    val assurance: AssuranceDataPoint? = null,

)
