// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandqaservice.frameworks.pcaf.model.companyValue

import jakarta.validation.Valid
import org.dataland.datalandqaservice.frameworks.pcaf.model.companyValue.listedCompany.PcafCompanyvalueListedCompany
import org.dataland.datalandqaservice.frameworks.pcaf.model.companyValue.unlistedCompany.PcafCompanyvalueUnlistedCompany

/**
 * The QA-model for the CompanyValue section
 */
data class PcafCompanyValue(
    @field:Valid()
    val listedCompany: PcafCompanyvalueListedCompany? = null,
    @field:Valid()
    val unlistedCompany: PcafCompanyvalueUnlistedCompany? = null,
)
