// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.heimathafen.model.general.impactmerkmaleLebenUnterWasser

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.BaseDataPoint
import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the ImpactmerkmaleLebenUnterWasser section
 */
data class HeimathafenGeneralImpactmerkmaleLebenUnterWasser(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Kann mit der Methodik ein Beitrag zum SDG "Leben unter Wasser" gemessen werden?""",
        example = """ "Yes"  """,
    )
    val sdgLebenUnterWasser: YesNo? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """null""",
        example = """ "This is some free text"  """,
    )
    val wennNeinBitteBegruenden: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Kennzahlen werden verwendet?
Angaben zu den KPIs die zur Messung des SDGs verwendet werden.""",
        example = """ "This is some free text"  """,
    )
    val verwendeteSchluesselzahlen: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Wie erfolgt die Datenerhebung?
Angaben zu dem Vorgang bei der Datenerhebung (z.B. Fragebogen, Interviews, Nutzung der Daten aus Geschäftsberichten)""",
        example = """ "This is some free text"  """,
    )
    val datenerfassung: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Wie erfolgt die Datenplausibilisierung?
Erkennung von Ausreißern (z.B. mithilfe von Benchmarking), Maßnahmen zur Erkennung von unplausiblen Daten z.B. numerische Daten werden verlangt und Text wurde eingetragen""",
        example = """ "This is some free text"  """,
    )
    val datenPlausibilitaetspruefung: String? = null,
    @field:Valid()
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Quellen werden genutzt?
Angabe von Quellen, zum Beispiel Geschäftsberichte von Unternehmen, Nachhaltigkeitsberichte etc.""",
        example = """[
						{
							"value": "lifetime value",
							"dataSource": {
								"fileName": "Certification",
								"fileReference": "1902e40099c913ecf3715388cb2d9f7f84e6f02a19563db6930adb7b6cf22868"
							}
						},
						{
							"value": "technologies",
							"dataSource": {
								"fileName": "Policy",
								"fileReference": "04c4e6cd07eeae270635dd909f58b09b2104ea5e92ec22a80b6e7ba1d0b75dd0"
							}
						}
					] """,
    )
    val datenquellen: List<BaseDataPoint<String>>? = null,
)
