// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type BasePublicFrameworkDefinition } from '@/frameworks/BasePublicFrameworkDefinition';
import { type Configuration, type EuTaxonomyFinancialsData } from '@clients/backend';
import { type AxiosInstance } from 'axios';
import { type PublicFrameworkDataApi } from '@/utils/api/UnifiedFrameworkDataApi';
import { EuTaxonomyFinancialsApiClient } from '@/frameworks/eu-taxonomy-financials/ApiClient';

export class BaseEuTaxonomyFinancialsFrameworkDefinition
  implements BasePublicFrameworkDefinition<EuTaxonomyFinancialsData>
{
  readonly identifier = 'eu-taxonomy-financials';
  readonly explanation = 'Additional Taxonomy for Financials';
  readonly label = 'EU Taxonomy Financials';
  getPublicFrameworkApiClient(
    configuration?: Configuration,
    axiosInstance?: AxiosInstance
  ): PublicFrameworkDataApi<EuTaxonomyFinancialsData> {
    return new EuTaxonomyFinancialsApiClient(configuration, axiosInstance);
  }
}

export default new BaseEuTaxonomyFinancialsFrameworkDefinition();
