// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.allgemein.richtlinienDesUnternehmens

import java.util.EnumSet

/**
 * The data-model for the RichtlinienDesUnternehmens section
 */
data class EsgDatenkatalogAllgemeinRichtlinienDesUnternehmens(
    val existenzVonRichtlinienZuSpezifischenThemen: EnumSet<ExistenzVonRichtlinienZuSpezifischenThemenOptions>? = null,
    val beruecksichtigungVonNachhaltigkeitskriterienBeiDerLieferantenauswahl: String? = null,
)
