version: "3.8"
services:
  proxy:
    restart: always
    profiles: ["production"]
    networks:
      - external
      - internal
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dataland-inbound-proxy/nginx.conf:/etc/nginx/nginx.conf
  backend:
    restart: always
    profiles: ["production"]
    networks:
      - internal
    build:
      context: ./
      dockerfile: ${BACKEND_DOCKERFILE:-./dataland-backend/DockerfileTest}
    expose:
      - "8080"
    environment:
      DATALAND_SKYMINDERCLIENT_TOKEN: ${DATALAND_SKYMINDERCLIENT_TOKEN}
      DATALAND_SKYMINDERCLIENT_USER: ${DATALAND_SKYMINDERCLIENT_USER}
      DATALAND_EDC_TOKEN: ${DATALAND_EDC_TOKEN}
      DATALAND_EDC_USER: ${DATALAND_EDC_USER}
      SKYMINDER_URL: ${SKYMINDER_URL}
      SKYMINDER_USER: ${SKYMINDER_USER}
      SKYMINDER_PW: ${SKYMINDER_PW}
  frontend:
    restart: always
    profiles: ["production"]
    build:
      context: ./
      dockerfile: ${FRONTEND_DOCKERFILE:-./dataland-frontend/DockerfileTest}
      args:
        DATALAND_EDC_TOKEN: ${DATALAND_EDC_TOKEN}
        DATALAND_EDC_USER: ${DATALAND_EDC_USER}
    expose:
      - "80"
    networks:
      - internal
  edc-dummyserver:
    restart: always
    profiles: ["production"]
    image: ghcr.io/d-fine/datalandedc/edcdummyserver:0.2.0
    environment:
      SERVER_PORT: 9191
      SERVER_SERVLET_CONTEXT-PATH: /api
    networks:
      internal:
        aliases:
          - dataland-edc
    ports:
      - "9191:9191"
networks:
  internal:
  external:
