// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgquestionnaire.model.umwelt.abfallproduktion

import java.math.BigDecimal

/**
 * Data class for the timeseries data contained in the field berichterstattungAbfallproduktion
 */
data class BerichterstattungAbfallproduktionValues(
    val gesamteAbfallmenge: BigDecimal? = null,
    val prozentAbfallRecyclet: BigDecimal? = null,
    val prozentGefaehrlicherAbfall: BigDecimal? = null,
)
