// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgQuestionnaire.model.umwelt.abfallproduktion

import org.dataland.datalandbackend.frameworks.esgQuestionnaire.custom.YearlyTimeseriesData

/**
 * The data-model for the Abfallproduktion section
 */
data class EsgQuestionnaireUmweltAbfallproduktion(
    val berichterstattungAbfallproduktion: YearlyTimeseriesData<BerichterstattungAbfallproduktionValues?>? = null,
    val unternehmensGruppenStrategieBzglAbfallproduktion: String? = null,
    val recyclingImProduktionsprozess: YearlyTimeseriesData<RecyclingImProduktionsprozessValues?>? = null,
    val gefaehrlicherAbfall: String? = null,
)
