// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgquestionnaire.model.umwelt.abfallproduktion

import java.math.BigDecimal

/**
 * Data class for the timeseries data contained in the field recyclingImProduktionsprozess
 */
data class RecyclingImProduktionsprozessValues(
    val prozentRecycelteWerkstoffeImProduktionsprozess: BigDecimal? = null,
)
