// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.sfdr.model.environmental.biodiversity

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the Biodiversity section
 */
@Suppress("MaxLineLength")
data class SfdrEnvironmentalBiodiversity(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Sites or operations that are located, either partially or entirely, in or near primary forests and other wooded areas where their activities have a negative impact on these environments. See also Regulation (EU) 2022/1288, Annex I, top (19).
Linked to Regulation (EU) 2022/1288, Annex I, Table 1, Adverse sustainability indicator 7""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val primaryForestAndWoodedLandOfNativeSpeciesExposure: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Sites or operations that are partially or fully located in or near protected or biodiversity-sensitive areas, where their activities adversely impact these regions.
Linked to Regulation (EU) 2022/1288, Annex I, Table 1, Adverse sustainability indicator 7""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val protectedAreasExposure: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Sites or operations located in or near areas designated for the protection of species, including flora and fauna, where their activities lead to the deterioration of natural habitats and disturb the species for which these areas have been designated. See also Regulation (EU) 2022/1288, Annex I, top 18(a).
Linked to Regulation (EU) 2022/1288, Annex I, Table 1, Adverse sustainability indicator 7""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val rareOrEndangeredEcosystemsExposure: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Sites or operations that are partially or fully situated in areas of highly biodiverse grassland, which may be categorized as either: (i) natural grassland, meaning areas that would remain grassland without human intervention and preserve natural species composition and ecological characteristics; or (ii) non-natural grassland, meaning areas that would no longer be grassland without human intervention but are species-rich and not degraded, unless it is demonstrated that harvesting the raw material is essential to maintain its grassland status.
Linked to Regulation (EU) 2022/1288, Annex I, Table 1, Adverse sustainability indicator 7""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val highlyBiodiverseGrasslandExposure: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Involvements in manufacture of pesticides and other agrochemical products. See Regulation (EC) No 1893/2006, Annex I, Division 20.2.
Linked to Regulation (EU) 2022/1288, Annex I, Table 2, Adverse impact on sustainability factor 9""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val manufactureOfAgrochemicalPesticidesProducts: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Involvement in activities, which cause land degradation, desertification or soil sealing.
Linked to Regulation (EU) 2022/1288, Annex I, Table 2, Adverse impact on sustainability factor 10""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val landDegradationDesertificationSoilSealingExposure: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Existence of sustainable land or agriculture practices or policies.
Linked to Regulation (EU) 2022/1288, Annex I, Table 2, Adverse impact on sustainability factor 11""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val sustainableAgriculturePolicy: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Existence of sustainable oceans or seas practices or policies.
Linked to Regulation (EU) 2022/1288, Annex I, Table 2, Adverse impact on sustainability factor 12""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val sustainableOceansAndSeasPolicy: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Operations, which affect threatened species. See also Regulation (EU) 2022/1288, Annex I, top (20).
Linked to Regulation (EU) 2022/1288, Annex I, Table 2, Adverse impact on sustainability factor 14.1""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val threatenedSpeciesExposure: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Existence of a biodiversity protection policy that encompasses operational sites owned, leased, managed in, or adjacent to a protected area or an area of high biodiversity value outside protected areas.
Linked to Regulation (EU) 2022/1288, Annex I, Table 2, Adverse impact on sustainability factor 14.2""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val biodiversityProtectionPolicy: ExtendedDataPoint<YesNo?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Existence of a policy to address deforestation. "Deforestation" means the human-induced conversion of forested land to non-forested land, which can be permanent, when this change is definitive, or temporary when this change is part of a cycle that includes natural or assisted regeneration, according to the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES) as referred to in paragraph 100 of Decision No 1386/2013/EU of the European Parliament and of the Council. See also Regulation (EU) 2022/1288, Annex I, top (21).
Linked to Regulation (EU) 2022/1288, Annex I, Table 2, Adverse impact on sustainability factor 15""",
        example = """{
      "value" :  "Yes" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val deforestationPolicy: ExtendedDataPoint<YesNo?>? = null,
)
