// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.gdv.model.soziales.geschlechterdiversitaet

import java.math.BigDecimal

/**
 * The data-model for the Geschlechterdiversitaet section
 */
data class GdvSozialesGeschlechterdiversitaet(
    val mitarbeiterAufTopManagementEbene: BigDecimal?,
    val frauenAufTopManagementEbene: BigDecimal?,
    val mitgliederGeschaeftsfuehrung: BigDecimal?,
    val frauenInDerGeschaeftsfuehrung: BigDecimal?,
    val definitionTopManagement: String?,
    val einhaltungRechtlicherVorgaben: String?,
)
