name: "Download Image Versions"
description: "Download Image Versions and make them available as env-vars"

runs:
  using: "composite"
  steps:
    - name: Download Image Versions
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8
      with:
        pattern: dockerImageVersions-*
        merge-multiple: true
    - name: Make Image Versions Available
      shell: bash
      run: cat ./*github_env.log >> $GITHUB_ENV
