export const LksgKpis = {
  dataDate: "Data Date",
  companyLegalForm: "Company Legal Form",
  vatIdentificationNumber: "Vat Identification Number",
  numberOfEmployees: "Number Of Employees",
  shareOfTemporaryWorkers: "Share Of Temporary Workers",
  totalRevenue: "Total Revenue",
  totalRevenueCurrency: "Total Revenue Currency",
  responsibilitiesForFairWorkingConditions: "Responsibilities For Fair Working Conditions",
  responsibilitiesForOccupationalSafety: "Responsibilities For Occupational Safety",
  riskManagementSystem: "Risk Management System",
  betterWorkProgramCertificate: "Better Work Program Certificate",
  grievanceHandlingMechanismUsedForReporting: "Grievance Handling Mechanism Used For Reporting",
  codeOfConduct: "Code Of Conduct",
  codeOfConductTraining: "Code Of Conduct Training",
  legalProceedings: "Legal Proceedings",
  employeeUnder18Under15: "Employee Under 18 Under 15",
  employmentUnderLocalMinimumAgePreventionCheckingOfLegalMinimumAge:
    "Employment Under Local Minimum Age Prevention Checking Of Legal Minimum Age",
  forcedLabourAndSlaveryPrevention: "Forced Labour And Slavery Prevention",
  forcedLabourAndSlaveryPreventionIdentityDocuments: "Forced Labour And Slavery Prevention Identity Documents",
  forcedLabourAndSlaveryPreventionFreeMovement: "Forced Labour And Slavery Prevention Free Movement",
  forcedLabourAndSlaveryPreventionProvisionSocialRoomsAndToilets:
    "Forced Labour And Slavery Prevention Provision Social Rooms And Toilets",
  forcedLabourAndSlaveryPreventionProvisionTraining: "Forced Labour And Slavery Prevention Provision Training",
  adequateLivingWage: "Adequate Living Wage",
  regularWagesProcessFlow: "Regular Wages Process Flow",
  fixedHourlyWages: "Fixed Hourly Wages",
  workplaceAccidentsUnder10: "Workplace Accidents Under 10",
  freedomOfAssociation: "Freedom Of Association",
  discriminationForTradeUnionMembers: "Discrimination For Trade Union Members",
  freedomOfOperationForTradeUnion: "Freedom Of Operation For Trade Union",
  worksCouncil: "Works Council",
  diversityAndInclusionRole: "Diversity And Inclusion Role",
  equalOpportunitiesOfficer: "Equal Opportunities Officer",
  riskOfHarmfulPollution: "Risk Of Harmful Pollution",
  unlawfulEvictionAndTakingOfLand: "Unlawful Eviction And Taking Of Land",
  useOfPrivatePublicSecurityForcesAndRiskOfViolationOfHumanRights:
    "Use Of Private Public Security Forces And Risk Of Violation Of Human Rights",
  mercuryAndMercuryWasteHandlingPolicy: "Mercury And Mercury Waste Handling Policy",
  chemicalHandling: "Chemical Handling",
  environmentalManagementSystem: "Environmental Management System",
  legalRestrictedWaste: "Legal Restricted Waste",
  mercuryAddedProductsHandling: "Mercury Added Products Handling",
  mercuryAndMercuryCompoundsProductionAndUseRiskOfExposure:
    "Mercury And Mercury Compounds Production And Use Risk Of Exposure",
  persistentOrganicPollutantsProductionAndUse: "Persistent Organic Pollutants Production And Use",
  persistentOrganicPollutantsProductionAndUseRiskOfDisposal:
    "Persistent Organic Pollutants Production And Use Risk Of Disposal",
  hazardousWasteDisposal: "Hazardous Waste Disposal",
  hazardousAndOtherWasteImport: "Hazardous And Other Waste Import",
  riskManagementSystemCertification: "Risk Management System Certification",
  amforiBsciAuditReport: "Amfori Bsci Audit Report",
  fairLabourAssociationCertification: "Fair Labour Association Certification",
  lksgInScope: "Lksg In Scope",
  oshMonitoring: "Osh Monitoring",
  oshPolicy: "Osh Policy",
  smetaSocialAuditConcept: "Smeta Social Audit Concept",
  iso45001Certification: "iso45001 Certification",
  iso14000Certification: "iso14000 Certification",
  sa8000Certification: "sa8000 Certification",
  iso37001Certification: "iso37001 Certification",
  iso37301Certification: "iso37301 Certification",
  oshPolicyFireProtection: "Osh Policy Fire Protection",
  oshPolicyWorkingHours: "Osh Policy Working Hours",
  oshManagementSystem: "Osh Management System",
  oshPolicyWorkplaceErgonomics: "Osh Policy Workplace Ergonomics",
  oshPolicyTraining: "Osh Policy Training",
  oshPolicyPersonalProtectiveEquipment: "Osh Policy Personal Protective Equipment",
  oshPolicyAccidentsBehaviouralResponse: "Osh Policy Accidents Behavioural Response",
  oshPolicyDisasterBehaviouralResponse: "Osh Policy Disaster Behavioural Response",
  oshPolicyHandlingChemicalsAndOtherHazardousSubstances: "Osh Policy Handling Chemicals And Other Hazardous Substances",
  equalOpportunitiesAndNondiscriminationPolicy: "Equal Opportunities And Nondiscrimination Policy",
  healthAndSafetyPolicy: "Health And Safety Policy",
  complaintsAndGrievancesPolicy: "Complaints And Grievances Policy",
};

export const LksgKpisImpactArea = {
  dataDate: "General",
  companyLegalForm: "General",
  vatIdentificationNumber: "General",
  numberOfEmployees: "General",
  shareOfTemporaryWorkers: "General",
  totalRevenue: "General",
  totalRevenueCurrency: "General",
  lksgInScope: "General",
  betterWorkProgramCertificate: "Better Work Program Certificate",
  responsibilitiesForFairWorkingConditions: "Social and employee matters",
  responsibilitiesForOccupationalSafety: "OSH",
  riskManagementSystem: "Risk management",
  grievanceHandlingMechanismUsedForReporting: "Grievance mechanism",
  codeOfConduct: "Code Of Conduct",
  codeOfConductTraining: "Code Of Conduct",
  legalProceedings: "Grievance mechanism",
  employeeUnder18Under15: "Child labour",
  employmentUnderLocalMinimumAgePreventionCheckingOfLegalMinimumAge: "Child labour",
  forcedLabourAndSlaveryPrevention: "Forced labour, slavery and debt bondage",
  forcedLabourAndSlaveryPreventionIdentityDocuments: "Forced labour, slavery and debt bondage",
  forcedLabourAndSlaveryPreventionFreeMovement: "Forced labour, slavery and debt bondage",
  forcedLabourAndSlaveryPreventionProvisionSocialRoomsAndToilets: "Forced labour, slavery and debt bondage",
  forcedLabourAndSlaveryPreventionProvisionTraining: "Forced labour, slavery and debt bondage",
  adequateLivingWage: "Forced labour, slavery and debt bondage",
  regularWagesProcessFlow: "Forced labour, slavery and debt bondage",
  fixedHourlyWages: "Forced labour, slavery and debt bondage",
  workplaceAccidentsUnder10: "OSH",
  freedomOfAssociation: "Freedom of association",
  discriminationForTradeUnionMembers: "Freedom of association",
  freedomOfOperationForTradeUnion: "Freedom of association",
  worksCouncil: "Freedom of association",
  diversityAndInclusionRole: "Human rights",
  equalOpportunitiesOfficer: "Human rights",
  riskOfHarmfulPollution: "Human rights",
  unlawfulEvictionAndTakingOfLand: "Human rights",
  useOfPrivatePublicSecurityForcesAndRiskOfViolationOfHumanRights: "Human rights",
  mercuryAndMercuryWasteHandlingPolicy: "Human rights",
  chemicalHandling: "Waste",
  environmentalManagementSystem: "Waste",
  legalRestrictedWaste: "Waste",
  mercuryAddedProductsHandling: "Waste",
  mercuryAndMercuryCompoundsProductionAndUseRiskOfExposure: "Waste",
  persistentOrganicPollutantsProductionAndUse: "Waste",
  persistentOrganicPollutantsProductionAndUseRiskOfDisposal: "Waste",
  hazardousWasteDisposal: "Waste",
  hazardousAndOtherWasteImport: "Waste",
  riskManagementSystemCertification: "Evidence, certificates and attestations",
  amforiBsciAuditReport: "Evidence, certificates and attestations",
  fairLabourAssociationCertification: "Evidence, certificates and attestations",
  oshMonitoring: "OSH",
  oshPolicy: "OSH",
  smetaSocialAuditConcept: "Evidence, certificates and attestations",
  iso45001Certification: "Evidence, certificates and attestations",
  iso14000Certification: "Evidence, certificates and attestations",
  sa8000Certification: "Evidence, certificates and attestations",
  iso37001Certification: "Evidence, certificates and attestations",
  iso37301Certification: "Evidence, certificates and attestations",
  oshPolicyFireProtection: "OSH",
  oshPolicyWorkingHours: "OSH",
  oshManagementSystem: "OSH",
  oshPolicyWorkplaceErgonomics: "OSH",
  oshPolicyTraining: "OSH",
  oshPolicyPersonalProtectiveEquipment: "OSH",
  oshPolicyAccidentsBehaviouralResponse: "OSH",
  oshPolicyDisasterBehaviouralResponse: "OSH",
  oshPolicyHandlingChemicalsAndOtherHazardousSubstances: "OSH",
  equalOpportunitiesAndNondiscriminationPolicy: "Human rights",
  healthAndSafetyPolicy: "Evidence, certificates and attestations",
  complaintsAndGrievancesPolicy: "Evidence, certificates and attestations",
};

export const LksgGroupOrder = {
  "General": "1",
  "Social and employee matters": "2",
  "Risk management": "1",
  "Grievance mechanism": "1",
  "Code Of Conduct": "1",
  "Child labour": "1",
  "Forced labour, slavery and debt bondage": "1",
  "Freedom of association": "1",
  "Human rights": "1",
  "Evidence, certificates and attestations": "1",
  };
