// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import smeBaseFrameworkDefinition from '@/frameworks/sme/BaseFrameworkDefinition';
import { type BasePrivateFrameworkDefinition } from '@/frameworks/BasePrivateFrameworkDefinition';

export const PrivateFrameworkDefinitions: Record<string, BasePrivateFrameworkDefinition<object>> = {
  sme: smeBaseFrameworkDefinition,
};
