// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type FrontendFrameworkDefinition } from "@/frameworks/FrameworkDefinition";
import esgquestionnaire from "@/frameworks/esgquestionnaire/FrontendFrameworkDefinition";

export const FrameworkDefinitions: Record<string, FrontendFrameworkDefinition<object>> = {
  esgquestionnaire: esgquestionnaire,
};
