// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.capex

import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.custom.EuTaxonomyActivity
import org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.custom.EuTaxonomyAlignedActivity
import org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.capex.alignedShare
    .EutaxonomyNonFinancialsCapexAlignedShare
import org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.capex.eligibleShare
    .EutaxonomyNonFinancialsCapexEligibleShare
import org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.capex.nonAlignedShare
    .EutaxonomyNonFinancialsCapexNonAlignedShare
import org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.capex.nonEligibleShare
    .EutaxonomyNonFinancialsCapexNonEligibleShare
import org.dataland.datalandbackend.model.datapoints.CurrencyDataPoint
import java.math.BigDecimal
import kotlin.collections.MutableList

/**
 * The data-model for the Capex section
 */
data class EutaxonomyNonFinancialsCapex(
    @field:Valid()
    val totalAmount: CurrencyDataPoint? = null,

    @field:Valid()
    val nonEligibleShare: EutaxonomyNonFinancialsCapexNonEligibleShare? = null,

    @field:Valid()
    val eligibleShare: EutaxonomyNonFinancialsCapexEligibleShare? = null,

    @field:Valid()
    val nonAlignedShare: EutaxonomyNonFinancialsCapexNonAlignedShare? = null,

    val nonAlignedActivities: MutableList<EuTaxonomyActivity>? = null,

    @field:Valid()
    val alignedShare: EutaxonomyNonFinancialsCapexAlignedShare? = null,

    val substantialContributionToClimateChangeMitigationInPercent: BigDecimal? = null,

    val substantialContributionToClimateChangeAdaptationInPercent: BigDecimal? = null,

    val substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercent: BigDecimal? = null,

    val substantialContributionToTransitionToACircularEconomyInPercent: BigDecimal? = null,

    val substantialContributionToPollutionPreventionAndControlInPercent: BigDecimal? = null,

    val substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercent: BigDecimal? = null,

    val alignedActivities: MutableList<EuTaxonomyAlignedActivity>? = null,

    val enablingShareInPercent: BigDecimal? = null,

    val transitionalShareInPercent: BigDecimal? = null,

)
