// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomyfinancials202673.model.general

import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.eutaxonomyfinancials202673.model.general.general
    .EutaxonomyFinancials202673GeneralGeneral

/**
 * The data-model for the General section
 */
@Suppress("MaxLineLength")
data class EutaxonomyFinancials202673General(
    @field:Valid()
    val general: EutaxonomyFinancials202673GeneralGeneral? = null,
)
