import { getStringCypressEnv } from "@e2e/utils/Cypress";

describe("As a developer, I expect the RabbitMQ GUI console to be available to me. Also check if all expected channels exist.", () => {
  it("Checks if the RabbitMQ Management GUI is available and the login page is shown. Also check if all expected channels exist.", () => {
    cy.visit("http://dataland-admin:6789/rabbitmq")
      .get("input[name=username]")
      .should("exist")
      .type(getStringCypressEnv("RABBITMQ_USER"))
      .get("input[name=password]")
      .should("exist")
      .type(getStringCypressEnv("RABBITMQ_PASS"))
      .get("input[type=submit]")
      .should("contain.value", "Login")
      .click()
      .get("#logout")
      .contains("Log out")
      .should("contain.value", "Log out");
    cy.visit("http://dataland-admin:6789/rabbitmq/#/queues")
      .get("table[class=list]")
      .contains("dataQualityAssuredBackendDataManager")
      .should("contain.text", "dataQualityAssuredBackendDataManager")
      .get("table[class=list]")
      .contains("dataReceivedInternalStorageDataManager")
      .should("contain.text", "dataReceivedInternalStorageDataManager")
      .get("table[class=list]")
      .contains("dataStoredBackendDataManager")
      .should("contain.text", "dataStoredBackendDataManager")
      .get("table[class=list]")
      .contains("dataStoredDocumentManager")
      .should("contain.text", "dataStoredDocumentManager")
      .get("table[class=list]")
      .contains("dataStoredQaService")
      .should("contain.text", "dataStoredQaService")
      .get("table[class=list]")
      .contains("deadLetterQueue")
      .should("contain.text", "deadLetterQueue")
      .get("table[class=list]")
      .contains("documentQualityAssuredDocumentManager")
      .should("contain.text", "documentQualityAssuredDocumentManager")
      .get("table[class=list]")
      .contains("documentReceivedDatabaseDataStore")
      .should("contain.text", "documentReceivedDatabaseDataStore")
      .get("table[class=list]")
      .contains("documentStoredQaService")
      .should("contain.text", "documentStoredQaService");
  });
});
