// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.sfdr.model.environmental.water

import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import org.dataland.datalandbackend.model.enums.commons.YesNo
import java.math.BigDecimal

/**
 * The data-model for the Water section
 */
data class SfdrEnvironmentalWater(
    @field:Valid()
    val emissionsToWater: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val waterConsumption: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val waterReused: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val relativeWaterUsage: ExtendedDataPoint<BigDecimal?>? = null,

    val waterManagementPolicy: ExtendedDataPoint<YesNo?>? = null,

    val highWaterStressAreaExposure: ExtendedDataPoint<YesNo?>? = null,

)
