// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgquestionnaire.model.governance.vorstandsprofil

import org.dataland.datalandbackend.model.enums.commons.YesNo
import java.math.BigDecimal

/**
 * The data-model for the Vorstandsprofil section
 */
data class EsgQuestionnaireGovernanceVorstandsprofil(
    val umfangDesTopManagementImUnternehmen: EsgQuestionnaireGovernanceVorstandsprofilUmfangDesTopManagementImUnternehmenOptions? = null,
    val anteilWeiblicherPersonenImTopManagement: BigDecimal? = null,
    val anteilMaennlicherPersonenImTopManagement: BigDecimal? = null,
    val anteilDiverserPersonenImTopManagement: BigDecimal? = null,
    val kopplungVonVerguetungDesTopManagementsAnNachhaltigkeitsziele: YesNo? = null,
    val kopplungVonVerguetungDesTopManagementsAnNachhaltigkeitszieleErlaeuterung: String? = null,
)
