// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.validator

import jakarta.validation.Constraint
import jakarta.validation.ConstraintValidator
import jakarta.validation.ConstraintValidatorContext
import jakarta.validation.Payload
import org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.EuTaxonomyFinancialsData
import org.dataland.datalandbackend.model.documents.CompanyReport
import kotlin.reflect.KClass

/**
* Annotation for the validation of referenced reports list for eu-taxonomy-financials
*/

@Constraint(validatedBy = [ReferencedReportsListConstraintValidator::class])
@Target(AnnotationTarget.FIELD, AnnotationTarget.CLASS)
annotation class ReferencedReportsListValidator(
    val message: String = "The list of referenced reports is not complete. Please ensure that any file used as a " +
        "data source in the dataset is included in the list of referenced reports.",
    val groups: Array<KClass<*>> = [],
    val payload: Array<KClass<out Payload>> = [],
)

/**
* Class holding the validation logic for referenced reports list. It checks if the referenced reports list is complete
*/
class ReferencedReportsListConstraintValidator :
    ConstraintValidator<ReferencedReportsListValidator, EuTaxonomyFinancialsData> {

    override fun isValid(dataset: EuTaxonomyFinancialsData?, context: ConstraintValidatorContext?): Boolean {
        if (dataset == null) {
            return false
        }
        val referencedReportsMap = dataset.general?.general?.referencedReports
        val referencedReportsFileReference = getFileReferencesFromReports(referencedReportsMap)

        val extendedDocumentsFileReferences = getExtendedDocumentReferences(dataset).filterNotNull()
        return extendedDocumentsFileReferences.all {
            referencedReportsFileReference.contains(it)
        }
    }

    private fun getFileReferencesFromReports(map: Map<String, CompanyReport>?): List<String> {
        if (map == null) return emptyList()
        val referencedReportsList = mutableListOf<String>()
        for (entry in map.entries) {
            referencedReportsList.add(entry.value.fileReference)
        }
        return referencedReportsList
    }

    @Suppress("MaxLineLength", "LongMethod")
    private fun getExtendedDocumentReferences(dataset: EuTaxonomyFinancialsData): List<String?> {
        return listOf(
            dataset.general?.general?.fiscalYearDeviation?.dataSource?.fileReference,
            dataset.general?.general?.fiscalYearEnd?.dataSource?.fileReference,
            dataset.general?.general?.areAllGroupEntitiesCovered?.dataSource?.fileReference,
            dataset.general?.general?.numberOfEmployees?.dataSource?.fileReference,
            dataset.general?.general?.isNfrdMandatory?.dataSource?.fileReference,
            dataset.general?.general?.levelOfAssurance?.dataSource?.fileReference,
            dataset.creditInstitution?.assetsForCalculationOfGreenAssetRatio?.totalGrossCarryingAmount?.dataSource?.fileReference,
            dataset.creditInstitution?.assetsForCalculationOfGreenAssetRatio?.totalAmountOfAssetsTowardsTaxonomyRelevantSectorsTaxonomyEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.assetsForCalculationOfGreenAssetRatio?.totalAmountOfAssetsWhichAreEnvironmentallySustainableTaxonomyAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.assetsForCalculationOfGreenAssetRatio?.totalAmountOfEnvironmentallySustainableAssetsWhichAreUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.assetsForCalculationOfGreenAssetRatio?.totalAmountOfEnvironmentallySustainableAssetsWhichAreTransitional?.dataSource?.fileReference,
            dataset.creditInstitution?.assetsForCalculationOfGreenAssetRatio?.totalAmountOfEnvironmentallySustainableAssetsWhichAreEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToClimateChangeAdaptationInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToClimateChangeAdaptationInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToClimateChangeAdaptationInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToClimateChangeAdaptationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToTransitionToACircularEconomyInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToTransitionToACircularEconomyInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToPollutionPreventionAndControlInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToPollutionPreventionAndControlInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.turnoverBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToClimateChangeMitigationInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToClimateChangeAdaptationInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToClimateChangeAdaptationInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToClimateChangeAdaptationInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToClimateChangeAdaptationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToTransitionToACircularEconomyInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToTransitionToACircularEconomyInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToPollutionPreventionAndControlInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToPollutionPreventionAndControlInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentEligible?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentAligned?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentOfWhichUseOfProceeds?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.creditInstitution?.capexBasedGreenAssetRatioStock?.substantialContributionToAnyOfTheSixEnvironmentalObjectivesInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToClimateChangeMitigationInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToClimateChangeMitigationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToClimateChangeMitigationInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.turnoverBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToClimateChangeMitigationInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToClimateChangeMitigationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToClimateChangeMitigationInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentAligned?.dataSource?.fileReference,
            dataset.assetManagement?.capexBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.general?.taxonomyEligibleNonLifeInsuranceEconomicActivities?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeMitigationInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeMitigationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeMitigationInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeAdaptationInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeAdaptationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToTransitionToACircularEconomyInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToPollutionPreventionAndControlInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.revenueBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeMitigationInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeMitigationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeMitigationInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeAdaptationInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToClimateChangeAdaptationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToTransitionToACircularEconomyInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToPollutionPreventionAndControlInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentAligned?.dataSource?.fileReference,
            dataset.insuranceReinsurance?.capexBasedGrossPremiumsWrittenReInsuranceRevenue?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServices?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToClimateChangeMitigationInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToClimateChangeMitigationInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToClimateChangeMitigationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToClimateChangeMitigationInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServicesInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServicesInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServicesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.turnoverBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServicesInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServices?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToClimateChangeMitigationInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToClimateChangeMitigationInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToClimateChangeMitigationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToClimateChangeMitigationInPercentOfWhichTransitional?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToClimateChangeAdaptationInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToTransitionToACircularEconomyInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToPollutionPreventionAndControlInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServicesInPercentEligible?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServicesInPercentAligned?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServicesInPercentOfWhichEnabling?.dataSource?.fileReference,
            dataset.investmentFirms?.capexBasedKpi?.totalAssetsInvestedRevenueFromInvestmentAndServicesInPercentOfWhichTransitional?.dataSource?.fileReference,
        )
    }
}
