# This is a complete configuration to deploy Loki backed by the filesystem.
# Please refer to https://grafana.com/docs/loki/latest/configure/
# The index will be shipped to the storage via tsdb-shipper.


# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
# Disable reporting
analytics:
  reporting_enabled: false

# Enables authentication through the X-Scope-OrgID header, which must be present
# if true. If false, the OrgID will always be set to 'fake'.
auth_enabled: false

# Configures the server of the launched module(s).
server:
  http_listen_port: 3100  # default 3100

# Common configuration to be shared between multiple modules. If a more specific
# configuration is given in other sections, the related configuration within
# this section will be ignored.
common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
#    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory


schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# TODO ????
storage_config:
  tsdb_shipper:
    # Directory where ingesters would write index files which would then be
    # uploaded by shipper to configured storage
    active_index_directory: /tmp/loki/index
    # Cache location for restoring index files from storage for queries
    cache_location: /tmp/loki/index_cache
  filesystem:
    directory: /tmp/loki/chunks

# TODO
#pattern_ingester:
#  enabled: true
