// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.capex.alignedShare

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.CurrencyDataPoint
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import java.math.BigDecimal

/**
 * The data-model for the AlignedShare section
 */
@Suppress("MaxLineLength")
data class EutaxonomyNonFinancialsCapexAlignedShare(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Relative share of CapEx that is taxonomy-aligned, i.e., generated by an eligible economic activity that is making a substantial contribution to at least one of the climate and environmental objectives, while also doing no significant harm to the remaining objectives and meeting minimum standards on human rights and labour standards.""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val relativeShareInPercent: ExtendedDataPoint<BigDecimal?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Absolute value of CapEx that is taxonomy-aligned, i.e., generated by an eligible economic activity that is making a substantial contribution to at least one of the climate and environmental objectives, while also doing no significant harm to the remaining objectives and meeting minimum standards on human rights and labour standards.""",
        example = """{
      "value" : 100.5,
      "currency" : "USD",
      "quality" : "Reported",
      "comment" : "The value is reported by the company.",
      "dataSource" : {
      "page" : "5-7",
      "tagName" : "monetaryAmount",
      "fileName" : "AnnualReport2020.pdf",
      "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
    } """,
    )
    val absoluteShare: CurrencyDataPoint? = null,
)
