// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.lksg.model.general.masterData

import org.dataland.datalandbackend.model.enums.commons.YesNo
import org.dataland.datalandbackend.model.generics.AmountWithCurrency
import org.dataland.datalandbackend.validator.MinimumValue
import java.math.BigDecimal
import java.time.LocalDate

/**
 * The data-model for the MasterData section
 */
data class LksgGeneralMasterData(
    val dataDate: LocalDate,
    val headOfficeInGermany: YesNo? = null,
    val groupOfCompanies: YesNo? = null,
    val groupOfCompaniesName: String? = null,
    val industry: List<String>? = null,
    @field:MinimumValue(minimumValue = 0)
    val numberOfEmployees: BigDecimal? = null,
    val seasonalOrMigrantWorkers: YesNo? = null,
    val shareOfTemporaryWorkers: LksgGeneralMasterdataShareOfTemporaryWorkersOptions? = null,
    val annualTotalRevenue: AmountWithCurrency? = null,
    val fixedAndWorkingCapital: AmountWithCurrency? = null,
)
