{
 "title": "Error Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "label": "Service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Internal Server Error 500",
   "type": "logs",
   "description": "Show Log messages of Internal Server Errors 500, containing \"internal server error\" (case-insensitive). Ignore duplicate logs that process these error messages by excluding logs with label \"level=info\" (field \"detected_level=info\" cannot be filtered out automatically but manually). \n\nNote: Log message timestamps may use server time instead of browser time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\", level!=\"info\"} |~ \"(?i)internal server error\""
    }
   ]
  },
  {
   "title": "Number of Internal Server Error 500 Logs",
   "type": "timeseries",
   "description": "Note: Time is based on browser time. \n\nAlerts are resolved automatically after 6h.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=~\".+\", level!=\"info\"} |~ \"(?i)internal server error\" [1m])"
    }
   ]
  },
  {
   "title": "Unhealthy Containers",
   "type": "logs",
   "description": "Show log messages of unhealthy container, identified by job=health_check, level=error.  \n\nNote: Log timestamps use server time, not browser time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"health_check\", level=\"error\"}"
    }
   ]
  },
  {
   "title": "Number of Unhealthy Container Logs",
   "type": "timeseries",
   "description": "Note: Time is based on browser time. \n\nAlerts are resolved 'directly' when a container is healthy again.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"health_check\", level=\"error\"} [1m])"
    }
   ]
  },
  {
   "title": "Stack Traces",
   "type": "logs",
   "description": "Show detected Stack Traces, identified by log message containing \"Exception\" (case-insensitive match).  Ignore duplicate logs that process these error messages by excluding logs with label \"level=info\" (field \"detected_level=info\" cannot be filtered out automatically but manually).\n\nNote: Log message timestamps may use server time, not browser time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\", level!=\"info\"} |~ \"(?i)Exception\""
    }
   ]
  },
  {
   "title": "Number of Stack Trace Logs",
   "type": "timeseries",
   "description": "Note: Time is based on browser time. \n\nAlerts are resolved automatically after 24h.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=~\".+\", level!=\"info\"} |~ \"(?i)Exception(\\\\(|:)?\" [1m])"
    }
   ]
  },
  {
   "title": "All Error Log Messages",
   "type": "logs",
   "description": "Show all Log Messages containing \"error\" (case-insensitive match). Ignore duplicate logs that process these error messages by excluding logs with label \"level=info\" (field \"detected_level=info\" cannot be filtered out automatically but manually).\n\nNote: Log message timestamps may use server time, not browser time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\", job!=\"health_check\", level!=\"info\"} |~ \"(?i)error\" "
    }
   ]
  },
  {
   "title": "Number of Error Logs",
   "type": "timeseries",
   "description": "Note: Time is based on browser time. \n\nAlerts are resolved automatically after 24h.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=~\".+\", job!=\"health_check\", level!=\"info\"} |~ \"(?i)error\" [1m])"
    }
   ]
  },
  {
   "title": "Export Job Timeouts",
   "type": "logs",
   "description": "Show log messages for export jobs that exceeded configured timeout minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\", level!=\"info\"} |~ \"(?i)export job .+ exceeded .+ minutes\""
    }
   ]
  }
 ]
}