// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgQuestionnaire.model.allgemein.fuehrungsstandards

import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the Fuehrungsstandards section
 */
data class EsgQuestionnaireAllgemeinFuehrungsstandards(
    val oekologischeSozialeFuehrungsstandardsOderPrinzipien: YesNo? = null,
    val anreizmechanismenFuerDasManagementUmwelt: AnreizmechanismenFuerDasManagementUmweltOptions? = null,
    val anreizmechanismenFuerDasManagementSoziales: AnreizmechanismenFuerDasManagementSozialesOptions? = null,
)
