// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.pcaf.model.general.company

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint

/**
 * The data-model for the Company section
 */
@Suppress("MaxLineLength")
data class PcafGeneralCompany(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """One of the following sectors the company is mainly operating in: "Communication Services"; "Consumer Discretionary"; "Consumer Staples"; "Energy"; "Financials"; "Health Care"; "Industrials"; "Industry"; "Information Technology"; "Materials"; "Real estate"; "Sovereign"; "Utilities";""",
        example = """{
      "value" :  "Option 1" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val mainPcafSector: ExtendedDataPoint<PcafGeneralCompanyMainPcafSectorOptions?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """"Listed" if the company is listed on an exchange - otherwise "Unlisted"""",
        example = """{
      "value" :  "Option 1" , 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val companyExchangeStatus: ExtendedDataPoint<PcafGeneralCompanyCompanyExchangeStatusOptions?>? = null,
)
