// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.sfdr.model.general.general

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.documents.CompanyReport
import org.dataland.datalandbackend.utils.JsonExampleFormattingConstants
import java.time.LocalDate

/**
 * The data-model for the General section
 */
data class SfdrGeneralGeneral(
    val dataDate: LocalDate,
    val fiscalYearDeviation: SfdrGeneralGeneralFiscalYearDeviationOptions,
    val fiscalYearEnd: LocalDate,
    @field:Schema(example = JsonExampleFormattingConstants.REFERENCED_REPORTS_DEFAULT_VALUE)
    @field:Valid()
    val referencedReports: Map<String, CompanyReport>? = null,
)
