// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.nuclearandgas.model.general.taxonomyAlignedDenominator

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.nuclearandgas.custom.NuclearAndGasAlignedDenominator
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint

/**
 * The data-model for the TaxonomyAlignedDenominator section
 */
@Suppress("MaxLineLength")
data class NuclearAndGasGeneralTaxonomyAlignedDenominator(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Proportion of Taxonomy-aligned Economic Activity referred to in Sections 4.26 to 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the Denominator of the applicable KPI - Revenue-based""",
        example = """
            {
            "value" :  {
      "taxonomyAlignedShareDenominatorNAndG426" : {
        "mitigationAndAdaptation" : 0.2,
        "mitigation" : 0.3,
        "adaptation" : 0.1
      },
      "taxonomyAlignedShareDenominatorNAndG427" : {
        "mitigationAndAdaptation" : 1.2,
        "mitigation" : 0.4,
        "adaptation" : 0.2
      },
      "taxonomyAlignedShareDenominatorNAndG428" : {
        "mitigationAndAdaptation" : 1,
        "mitigation" : null,
        "adaptation" : null
      },
      "taxonomyAlignedShareDenominatorNAndG429" : {
        "mitigationAndAdaptation" : null,
        "mitigation" : null,
        "adaptation" : null
      },
      "taxonomyAlignedShareDenominatorNAndG430" : {
        "mitigationAndAdaptation" : 0.3,
        "mitigation" : 2.4,
        "adaptation" : 0.5
      },
      "taxonomyAlignedShareDenominatorNAndG431" : {
        "mitigationAndAdaptation" : 0.2,
        "mitigation" : 0.5,
        "adaptation" : 0.6
      },
      "taxonomyAlignedShareDenominatorOtherActivities" : {
        "mitigationAndAdaptation" : 1.1,
        "mitigation" : 1.4,
        "adaptation" : 1.1
      },
      "taxonomyAlignedShareDenominator" : {
        "mitigationAndAdaptation" : 4,
        "mitigation" : 5,
        "adaptation" : 2.5
      }
    }, 
            "quality" : "Reported",
            "comment" : "The value is reported by the company."
            "dataSource" : {
            "page" : "5-7",
            "tagName" : "monetaryAmount",
            "fileName" : "AnnualReport2020.pdf",
            "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
            }
    } """,
    )
    @field:Valid()
    val nuclearAndGasTaxonomyAlignedRevenueDenominator: ExtendedDataPoint<NuclearAndGasAlignedDenominator?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Proportion of Taxonomy-aligned Economic Activity referred to in Sections 4.26 to 4.31 of Annexes I and II to Delegated Regulation 2021/2139 in the Denominator of the applicable KPI - CapEx-based""",
        example = """
            {
            "value" :  {
      "taxonomyAlignedShareDenominatorNAndG426" : {
        "mitigationAndAdaptation" : 0.2,
        "mitigation" : 0.3,
        "adaptation" : 0.1
      },
      "taxonomyAlignedShareDenominatorNAndG427" : {
        "mitigationAndAdaptation" : 1.2,
        "mitigation" : 0.4,
        "adaptation" : 0.2
      },
      "taxonomyAlignedShareDenominatorNAndG428" : {
        "mitigationAndAdaptation" : 1,
        "mitigation" : null,
        "adaptation" : null
      },
      "taxonomyAlignedShareDenominatorNAndG429" : {
        "mitigationAndAdaptation" : null,
        "mitigation" : null,
        "adaptation" : null
      },
      "taxonomyAlignedShareDenominatorNAndG430" : {
        "mitigationAndAdaptation" : 0.3,
        "mitigation" : 2.4,
        "adaptation" : 0.5
      },
      "taxonomyAlignedShareDenominatorNAndG431" : {
        "mitigationAndAdaptation" : 0.2,
        "mitigation" : 0.5,
        "adaptation" : 0.6
      },
      "taxonomyAlignedShareDenominatorOtherActivities" : {
        "mitigationAndAdaptation" : 1.1,
        "mitigation" : 1.4,
        "adaptation" : 1.1
      },
      "taxonomyAlignedShareDenominator" : {
        "mitigationAndAdaptation" : 4,
        "mitigation" : 5,
        "adaptation" : 2.5
      }
    }, 
            "quality" : "Reported",
            "comment" : "The value is reported by the company."
            "dataSource" : {
            "page" : "5-7",
            "tagName" : "monetaryAmount",
            "fileName" : "AnnualReport2020.pdf",
            "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
            }
    } """,
    )
    @field:Valid()
    val nuclearAndGasTaxonomyAlignedCapexDenominator: ExtendedDataPoint<NuclearAndGasAlignedDenominator?>? = null,
)
