// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandqaservice.frameworks.eutaxonomyfinancials.model.creditInstitution.capexBasedGreenAssetRatioStock

import jakarta.validation.Valid
import org.dataland.datalandbackend.openApiClient.model.ExtendedDataPointBigDecimal
import org.dataland.datalandqaservice.model.reports.QaReportDataPoint

/**
 * The QA-model for the CapexBasedGreenAssetRatioStock section
 */
data class EuTaxonomyFinancialsCreditinstitutionCapexBasedGreenAssetRatioStock(
    @field:Valid()
    val totalCapexBasedGreenAssetRatio: QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeMitigationInPercentEligible:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeMitigationInPercentAligned:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeMitigationInPercentOfWhichUseOfProceeds:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeMitigationInPercentEnablingShare:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeMitigationInPercentTransitionalShare:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeAdaptationInPercentEligible:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeAdaptationInPercentAligned:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeAdaptationInPercentOfWhichUseOfProceeds:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeAdaptationInPercentEnablingShare:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToClimateChangeAdaptationInPercentAdaptingShare:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentEligible:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentAligned:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentOfWhichUseOfProceeds:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResourcesInPercentEnablingShare:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToTransitionToACircularEconomyInPercentEligible:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToTransitionToACircularEconomyInPercentAligned:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToTransitionToACircularEconomyInPercentOfWhichUseOfProceeds:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToTransitionToACircularEconomyInPercentEnablingShare:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToPollutionPreventionAndControlInPercentEligible:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToPollutionPreventionAndControlInPercentAligned:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToPollutionPreventionAndControlInPercentOfWhichUseOfProceeds:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToPollutionPreventionAndControlInPercentEnablingShare:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentEligible:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentAligned:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentOfWhichUseOfProceeds:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

    @field:Valid()
    val substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystemsInPercentEnablingShare:
    QaReportDataPoint<ExtendedDataPointBigDecimal?>? = null,

)
