// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.hochwertigeBildung

import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the HochwertigeBildung section
 */
data class HeimathafenSdgHochwertigeBildung(
    val sdgHochwertigeBildung: YesNo? = null,
    val wennNeinBitteBegruendenHochwertigeBildung: String? = null,
    val verwendeteSchluesselzahlenHochwertigeBildung: String? = null,
    val datenerfassungHochwertigeBildung: String? = null,
    val datenPlausibilitaetspruefungHochwertigeBildung: String? = null,
    val datenquelleHochwertigeBildung: String? = null,
)
