// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.vsme.model.basic.biodiversity

import io.swagger.v3.oas.annotations.media.Schema
import org.dataland.datalandbackend.frameworks.vsme.custom.VsmeSiteAndArea
import java.math.BigDecimal

/**
 * The data-model for the Biodiversity section
 */
@Suppress("MaxLineLength")
data class VsmeBasicBiodiversity(
    val sitesAndAreas: List<VsmeSiteAndArea?>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)""",
        example = """100.5 """,
    )
    val totalSealedAreaPreviousYearInHectare: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)""",
        example = """100.5 """,
    )
    val totalSealedAreaReportingYearInHectare: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof. """,
        example = """13.52 """,
    )
    val relativeChangeSealedArea: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)""",
        example = """100.5 """,
    )
    val totalNatureOrientedAreaOnSitePreviousYearInHectare: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)""",
        example = """100.5 """,
    )
    val totalNatureOrientedAreaOnSiteReportingYearInHectare: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof. """,
        example = """13.52 """,
    )
    val relativeChangeNatureOrientedOnSite: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)""",
        example = """100.5 """,
    )
    val totalNatureOrientedAreaOffSitePreviousYearInHectare: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)""",
        example = """100.5 """,
    )
    val totalNatureOrientedAreaOffSiteReportingYearInHectare: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof. """,
        example = """13.52 """,
    )
    val relativeChangeNatureOrientedOffSite: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)""",
        example = """100.5 """,
    )
    val totalUseOfLandPreviousYearInHectare: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)""",
        example = """100.5 """,
    )
    val totalUseOfLandReportingYearInHectare: BigDecimal? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.""",
        example = """13.52 """,
    )
    val relativeChangeLandUse: BigDecimal? = null,
)
