// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.gdv.model.allgemein.fuehrungsstandards

import io.swagger.v3.oas.annotations.media.Schema

/**
 * Enum class for the single-select-field anreizmechanismenFuerDasManagementUmwelt
 */
@Schema(
    enumAsRef = true,
)
enum class AnreizmechanismenFuerDasManagementUmweltOptions {
    Nein,
    JaAufsichtsrat,
    JaGeschaeftsleitung,
    JaAufsichtsratUndGeschaeftsleitung,
}
