// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.sme.model.basic.resourceUseCircularEconomyAndWasteManagement

import io.swagger.v3.oas.annotations.media.Schema

/**
 * Enum class for the single-select-field measureWaste
 */
@Schema(
    enumAsRef = true,
)
enum class SmeBasicResourceusecirculareconomyandwastemanagementMeasureWasteOptions {
    WeightPreferred,
    Volume,
}
