// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type Category } from '@/utils/GenericFrameworkTypes';
import { type VsmeData } from '@clients/backend';

export const vsmeDataModel = [
  {
    name: 'basic',
    label: 'Basic',
    color: '',
    showIf: (): boolean => true,
    subcategories: [
      {
        name: 'basisForPreparation',
        label: 'Basis for Preparation',
        fields: [
          {
            name: 'reportingBasis',
            label: 'Reporting Basis',
            description:
              'Has the sustainability report been prepared on a consolidated basis (i.e., the report includes information of the undertaking and its subsidiaries) or on an individual basis (i.e., the report is limited only to the information of the undertaking)?',

            component: 'YesNoBaseDataPointFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'subsidiary',
            label: 'Subsidiary',
            description: 'Please provide a list of your subsidiaries including their registered addresses.',

            component: 'SubsidiaryFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'referencedReports',
            label: 'Referenced Reports',
            description: 'Please upload all relevant reports for this dataset in the PDF format.',

            component: 'UploadReports',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'practicesForTransitioningTowardsAMoreSustainableEconomy',
        label: 'Practices for transitioning towards a more sustainable economy',
        fields: [
          {
            name: 'undertakenMeasures',
            label: 'Undertaken Measures',
            description:
              'Please, describe specific practices for transitioning towards a more sustainable economy in case you have them in place.',

            component: 'ListOfBaseDataPointsFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'energyAndGreenhousGasEmissions',
        label: 'Energy and greenhous gas emissions',
        fields: [
          {
            name: 'energyFossilFuelsInMWh',
            label: 'Energy Fossil Fuels',
            description:
              'Please disclose your total energy consumption in MWh (in the reporting period) for fossil fuels.',

            unit: 'MWh',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'electricityTotalInMWh',
            label: 'Electricity Total',
            description:
              'Please disclose your total energy consumption in MWh (in the reporting period) for electricity as reflected in utility billings. If available distinguish between renewable and non\x02renewable sources.',

            unit: 'MWh',
            component: 'BigDecimalExtendedDataPointFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'electricityNonRenewableInMWh',
            label: 'Electricity Non-Renewable',
            description: 'Please provide the amount of electricity in MWh generated from non renewable sources.',

            unit: 'MWh',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'electricityRenewableInMWh',
            label: 'Electricity Renewable',
            description: 'Please provide the amount of electricity in MWh generated from renewable sources.',

            unit: 'MWh',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'totalEmissionsInTonnesOfCO2Equivalents',
            label: 'Total Emissions',
            description:
              'Please disclose your estimated gross greenhouse gas (GHG) emissions in tons of CO2 equivalents (tCO2eq) considering the content of the GHG Protocol Corporate Standard.\n(a) total GHG emissions in tCO2eq',

            unit: 'tCO2eq',
            component: 'BigDecimalExtendedDataPointFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'scope1EmissionsInTonnesOfCO2Equivalents',
            label: 'Scope 1 Emissions',
            description: '(b) the Scope 1 GHG emissions in tCO2eq (from owned or controlled sources)',

            unit: 'tCO2eq',
            component: 'BigDecimalExtendedDataPointFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'scope2EmissionsInTonnesOfCO2Equivalents',
            label: 'Scope 2 Emissions',
            description:
              '(c) the Scope 2 emissions in tCO2eq (i.e., emissions from the generation of purchased energy)',

            unit: 'tCO2eq',
            component: 'BigDecimalExtendedDataPointFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'scope3EmissionsInTonnesOfCO2Equivalents',
            label: 'Scope 3 Emissions',
            description: '(d) Scope 3 emissions, in case you can provide them',

            unit: 'tCO2eq',
            component: 'BigDecimalExtendedDataPointFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'pollutionOfAirWaterSoil',
        label: 'Pollution of air, water, soil',
        fields: [
          {
            name: 'pollutionEmission',
            label: 'Pollution Emission',
            description:
              'Please disclose, if applicable, the pollutants (with respective amounts in kg) you emit to air, water and soil in your own operations.',

            component: 'PollutionEmissionFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'biodiversity',
        label: 'Biodiversity',
        fields: [
          {
            name: 'sitesAndAreas',
            label: 'Sites and Areas',
            description:
              'Please, provide a list of relevant company sites adjoint to key biodiversity areas (including their country, area in hectares, adjoint biodiversity area, and level of adjointness).',

            component: 'SiteAndAreaFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'totalSealedAreaPreviousYearInHectare',
            label: 'Total Sealed Area Previous Year',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)',

            unit: 'Hectare',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'totalSealedAreaReportingYearInHectare',
            label: 'Total Sealed Area Reporting Year',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)',

            unit: 'Hectare',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'relativeChangeSealedArea',
            label: 'Relative Change Sealed Area',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof. ',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'totalNatureOrientedAreaOnSitePreviousYearInHectare',
            label: 'Total Nature-Oriented Area On-Site Previous Year',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)',

            unit: 'Hectare',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'totalNatureOrientedAreaOnSiteReportingYearInHectare',
            label: 'Total Nature-Oriented Area On-Site Reporting Year',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)',

            unit: 'Hectare',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'relativeChangeNatureOrientedOnSite',
            label: 'Relative Change Nature-Oriented On-Site',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof. ',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'totalNatureOrientedAreaOffSitePreviousYearInHectare',
            label: 'Total Nature-Oriented Area Off-Site Previous Year',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)',

            unit: 'Hectare',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'totalNatureOrientedAreaOffSiteReportingYearInHectare',
            label: 'Total Nature-Oriented Area Off-Site Reporting Year',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)',

            unit: 'Hectare',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'relativeChangeNatureOrientedOffSite',
            label: 'Relative Change Nature-Oriented Off-Site',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof. ',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'totalUseOfLandPreviousYearInHectare',
            label: 'Total Use Of Land Previous Year',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)',

            unit: 'Hectare',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'totalUseOfLandReportingYearInHectare',
            label: 'Total Use Of Land Reporting Year',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.  (Area is in hectares.)',

            unit: 'Hectare',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'relativeChangeLandUse',
            label: 'Relative Change Land Use',
            description:
              'Please, report on the land-use of your company with respect to different kinds of surfaces/landscapes. Provide the corresponding values for the year before the reporting year, for the reporting year itself and the percentual change thereof.',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'water',
        label: 'Water',
        fields: [
          {
            name: 'waterWithdrawalAllSitesInCubicMeters',
            label: 'Water Withdrawal All Sites',
            description:
              'Please, disclose your total water withdrawal (in m^3), i.e., the amount of water drawn into the boundaries of the organisation (or facility); pay additional attention to sites located in areas of high water-stress.',

            unit: 'Cubic Meters',
            component: 'BigDecimalExtendedDataPointFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'waterWithdrawalStressSitesInCubicMeters',
            label: 'Water Withdrawal Stress Sites',
            description: 'Please disclose your water withdrawal (in m^3) from sites with high water stress.',

            unit: 'Cubic Meters',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'waterDischargeAllSitesInCubicMeters',
            label: 'Water Discharge All Sites',
            description:
              'If applicable, we aim to determine your water consumption (as the difference between water withdrawal and water discharge). Hence, please disclose your respective water discharge from your production processes.',

            unit: 'Cubic Meters',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'waterDischargeStressSitesInCubicMeters',
            label: 'Water Discharge Stress Sites',
            description: 'Please disclose your water discharge (in m^3) from sites with high water stress.',

            unit: 'Cubic Meters',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'rainwaterAllSitesInCubicMeters',
            label: 'Rainwater All Sites',
            description: 'Please disclose the amount of rainwater (in m^3) for all sites.',

            unit: 'Cubic Meters',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'rainwaterStressSitesInCubicMeters',
            label: 'Rainwater Stress Sites',
            description: 'Please disclose the amount of rainwater (in m^3) for all sites with high water stress.',

            unit: 'Cubic Meters',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'waterConsumptionAllSitesInCubicMeters',
            label: 'Water Consumption All Sites',
            description: 'Please disclose the amount of water consumption (in m^3) for all sites.',

            unit: 'Cubic Meters',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'waterConsumptionStressSitesInCubicMeters',
            label: 'Water Consumption Stress Sites',
            description:
              'Please disclose the amount of water consumption (in m^3) for all sites with high water stress.',

            unit: 'Cubic Meters',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'resourceUseCircularEconomyAndWasteManagement',
        label: 'Resource use, circular economy and waste management',
        fields: [
          {
            name: 'totalWeightMaterialsInTonnes',
            label: 'Total Weight Materials',
            description:
              'In case you operate manufacturing, construction and/or packaging processes, please provide the share of recycled content in your products and packaging (in per cent based on weight, during the reporting period) For this we require the total weight  (in tons, in the reporting year) of both recycled and overall materials used in products and packaging. \n\nMoreover, please provide the share of recycable content in your products and packaging (in per cent based on weight, during the reporting period). For this we require the  total weight  (in tons, in the reporting year) of both recycable materials used in products and packaging. ',

            unit: 'Tonnes',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'weightRecycledMaterialsInTonnes',
            label: 'Weight Recycled Materials',
            description: 'Please disclose the weight of recycled materials in tonnes.',

            unit: 'Tonnes',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'percentageRecycledMaterials',
            label: 'Percentage Recycled Materials',
            description:
              'Please disclose percentage of recycled materials in regards to the total weight of maerials. ',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'weightRecyclableMaterialsInTonnes',
            label: 'Weight Recyclable Materials',
            description: 'Please disclose the weight of recycable materials in tonnes.',

            unit: 'Tonnes',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'percentageRecyclableMaterials',
            label: 'Percentage Recyclable Materials',
            description:
              'Please disclose percentage of recycable materials in regards to the total weight of maerials. ',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'measureWaste',
            label: 'Measure Waste',
            description:
              'Please, for each type of waste, provide your total annual generation of it (in tons or m^3) differentiating whether it is non-hazardous or hazardous. Also indicate the share of it diverted to recycling or reuse (in absolute numbers). First choose the unit you want to report in.',
            options: [
              {
                label: 'Weight (preferred)',
                value: 'WeightPreferred',
              },
              {
                label: 'Volume',
                value: 'Volume',
              },
            ],

            component: 'RadioButtonsFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'wasteClassification',
            label: 'Waste Classification',
            description: 'Please disclose the waste classification for every type of waste.',

            component: 'WasteClassificationFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'workforceGeneralCharacteristics',
        label: 'Workforce - General Characteristics',
        fields: [
          {
            name: 'measureEmployees',
            label: 'Measure Employees',
            description:
              'You will be asked to provide information related to the number of your employees. How do you want to count them? Please stick to this measure for all the subsequent questions.',
            options: [
              {
                label: 'Full-Time Equivalents',
                value: 'FullTimeEquivalents',
              },
              {
                label: 'Head Count',
                value: 'HeadCount',
              },
            ],

            component: 'RadioButtonsFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'numberOfEmployeesInFte',
            label: 'Number Of Employees In FTE',
            description:
              'What is your number of employees? (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
          },
          {
            name: 'numberOfEmployeesInHeadcount',
            label: 'Number Of Employees In Headcount',
            description:
              'What is your number of employees? (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
          },
          {
            name: 'numberOfTemporaryContractEmployeesInFte',
            label: 'Number Of Temporary Contract Employees In FTE',
            description:
              'Please disclose the number of employees broken down by employment contract. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
          },
          {
            name: 'numberOfTemporaryContractEmployeesInHeadcount',
            label: 'Number Of Temporary Contract Employees In Headcount',
            description:
              'Please disclose the number of employees broken down by employment contract. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
          },
          {
            name: 'numberOfPermanentContractEmployeesInFte',
            label: 'Number Of Permanent Contract Employees In FTE',
            description:
              'Please disclose the number of emplyees with a permanent contract. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
          },
          {
            name: 'numberOfPermanentContractEmployeesInHeadcount',
            label: 'Number Of Permanent Contract Employees In Headcount',
            description:
              'Please disclose the number of emplyees with a permanent contract. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
          },
          {
            name: 'numberOfMaleEmployeesInFte',
            label: 'Number Of Male Employees In FTE',
            description:
              'Please disclose the number of employees broken down by gender. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
          },
          {
            name: 'numberOfMaleEmployeesInHeadcount',
            label: 'Number Of Male Employees In Headcount',
            description:
              'Please disclose the number of employees broken down by gender. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
          },
          {
            name: 'numberFemaleEmployeesInFte',
            label: 'Number Female Employees In FTE',
            description:
              'Please disclose the number of female employees. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
          },
          {
            name: 'numberOfFemaleEmployeesInHeadcount',
            label: 'Number Of Female Employees In Headcount',
            description:
              'Please disclose the number of female employees. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
          },
          {
            name: 'numberOfOtherEmployeesInFte',
            label: 'Number Of Other Employees In FTE',
            description:
              'Please disclose the number of other employees. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
          },
          {
            name: 'numberOfOtherEmployeesInHeadcount',
            label: 'Number Of Other Employees In Headcount ',
            description:
              'Please disclose the number of other employees. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
          },
          {
            name: 'numberOfNotReportedEmployeesInFte',
            label: 'Number Of Not Reported Employees In FTE',
            description:
              'Please disclose the number of not reported employees. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
          },
          {
            name: 'numberOfNotReportedEmployeesInHeadcount',
            label: 'Number Of Not Reported Employees In Headcount',
            description:
              'Please disclose the number of not reported employees. (Use full-time equivalents or head count according to your initial choice.)',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
          },
          {
            name: 'employeesPerCountry',
            label: 'Employees Per Country',
            description:
              'Please list your employees presented by the country they work in. (Use full-time equivalents or head count according to your initial choice.)',

            component: 'EmployeesPerCountryFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'workforceHealthAndSafety',
        label: 'Workforce - Health and Safety',
        fields: [
          {
            name: 'totalHours',
            label: 'Total Hours',
            description: 'Please provide the total number of hours worked in a year by all your employees.',

            unit: 'h',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'numberOfAccidents',
            label: 'Number Of Accidents',
            description: 'Please disclose the number of work related accidents in the reporting year.',

            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'integer',
          },
          {
            name: 'accidentLevel',
            label: 'Accident Level',
            description:
              'Please provide work-related accidents, namely the number of work related accidents per 100 full-time workers over a yearly timeframe (assuming 2000 work hours per worker per year).',

            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'numberOfTotalFatalitiesInFte',
            label: 'Number Of Total Fatalities In FTE',
            description:
              'Please disclose the total number of fatalities in the reporting year due to work-related injuries or work-related ill health.',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
            validation: 'integer',
          },
          {
            name: 'numberOfTotalFatalitiesInHeadcount',
            label: 'Number Of Total Fatalities In Headcount',
            description:
              'Please disclose the total number of fatalities in the reporting year due to work-related injuries or work-related ill health.',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
            validation: 'integer',
          },
          {
            name: 'numberOfFatalitiesOfAccidentsInFte',
            label: 'Number Of Fatalities Of Accidents In FTE',
            description:
              'Please, if possible, distinguish further and separately provide the numbers of  fatalities in the reporting year due to work-related injuries and work-related ill health.',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
            validation: 'integer',
          },
          {
            name: 'numberOfFatalitiesOfAccidentsInHeadcount',
            label: 'Number Of Fatalities Of Accidents In Headcount',
            description:
              'Please, if possible, distinguish further and separately provide the numbers of  fatalities in the reporting year due to work-related injuries and work-related ill health.',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
            validation: 'integer',
          },
          {
            name: 'numberOfHealthFatalitiesInFte',
            label: 'Number Of Health Fatalities In FTE',
            description:
              'Please disclose the number of health fatalities in full time equilivants in the reporting year.',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
            validation: 'integer',
          },
          {
            name: 'numberOfHealthFatalitiesInHeadcount',
            label: 'Number Of Health Fatalities In Headcount',
            description: 'Please disclose the number of health fatalities in head count in the reporting year.',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
            validation: 'integer',
          },
        ],
      },
      {
        name: 'workforceRenumerationCollectiveBargainingAndTraining',
        label: 'Workforce - Renumeration, collective bargaining, and training',
        fields: [
          {
            name: 'numberOfMinimumWageEmployeesInFte',
            label: 'Number of minimum Wage Employees In FTE',
            description:
              'What is the number of employees (disregarding interns and apprentices) being compensated by wages based on minimum wage rules?',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
          },
          {
            name: 'numberOfMinimumWageEmployeesInHeadcount',
            label: 'Number Of Minimum Wage Employees In Headcount',
            description:
              'What is the number of employees (disregarding interns and apprentices) being compensated by wages based on minimum wage rules?',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
          },
          {
            name: 'percentageOfMinimumWageEmployees',
            label: 'Percentage Of Minimum Wage Employees',
            description:
              'What is the percentage of employees (disregarding interns and apprentices) being compensated by wages based on minimum wage rules?',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'majorityOfMinimumWageEmployees',
            label: 'Majority Of Minimum Wage Employees',
            description:
              'Do these constitute more than half of your employees (disregarding interns and apprentices, in the reporting measure you chose)?',

            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'entryLevelWageInEuro',
            label: 'Entry Level Wage',
            description: 'Please provide the entry level wage you pay.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'minimumWageInEuro',
            label: 'Minimum Wage',
            description: 'Please provide the minimum wage you pay.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'wageRatio',
            label: 'Wage Ratio',
            description: 'Please provide the ratio of entry level wage and minimum wage.',

            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'payGapBasis',
            label: 'Pay Gap Basis',
            description:
              'Please, in the following provide pay rates and work hours. On which basis do you prefer to report?',
            options: [
              {
                label: 'annual',
                value: 'Annual',
              },
              {
                label: 'weekly',
                value: 'Weekly',
              },
            ],

            component: 'RadioButtonsFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'grossPayMaleInEuro',
            label: 'Gross Pay Male',
            description:
              'Now taking into account all your employees, according to your choice of timeframe, please provide the gross pay for male employees. ',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'grossPayFemaleInEuro',
            label: 'Gross Pay Female',
            description:
              'Now taking into account all your employees, according to your choice of timeframe, please provide the gross pay for female employees. ',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'totalWorkHoursMale',
            label: 'Total Work Hours Male',
            description:
              'Taking into account all your employees and your choice of timeframe, please provide the number of average work hours (per week/year) by male employees. ',

            unit: 'h',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'totalWorkHoursFemale',
            label: 'Total Work Hours Female',
            description:
              'Taking into account all your employees and your choice of timeframe, please provide the number of average work hours (per week/year) by female employees. ',

            unit: 'h',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'averageWorkHoursMale',
            label: 'Average Work Hours Male',
            description:
              'Taking into account all your employees and your choice of timeframe, please provide the number of average work hours (per week/year) by male employees. ',

            unit: 'h',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'averageWorkHoursFemale',
            label: 'Average Work Hours Female',
            description:
              'Taking into account all your employees and your choice of timeframe, please provide the number of average work hours (per week/year) by female employees. ',

            unit: 'h',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'averageHourlyPayMaleInEuroPerHour',
            label: 'Average Hourly Pay Male',
            description: 'What is the average hourly pay for male employees?',

            unit: 'Euro/h',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'averageHourlyPayFemaleInEuroPerHour',
            label: 'Average Hourly Pay Female',
            description: 'What is the average hourly pay for female employees?',

            unit: 'Euro/h',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'payGap',
            label: 'Pay Gap',
            description: 'What is your pay gap? ',

            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean => {
              const firstValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInHeadcount ?? 0;
              const secondValue = dataset.basic?.workforceGeneralCharacteristics?.numberOfEmployeesInFte ?? 0;
              return firstValue >= 150 || secondValue >= 150;
            },
          },
          {
            name: 'numberBargainingAgreementsInFte',
            label: 'Number Bargaining Agreements  In FTE',
            description: 'Please state the number of employees covered by collective bargaining agreements.',

            unit: 'Full Time Equivalents',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'FullTimeEquivalents',
          },
          {
            name: 'numberBargainingAgreementsInHeadcount',
            label: 'Number Bargaining Agreements In Headcount',
            description: 'Please state the number of employees covered by collective bargaining agreements.',

            unit: 'Head Count',
            component: 'NumberFormField',
            required: false,
            showIf: (dataset: VsmeData): boolean =>
              dataset.basic?.workforceGeneralCharacteristics?.measureEmployees == 'HeadCount',
          },
          {
            name: 'ratioBargainingAgreement',
            label: 'Ratio Bargaining Agreement',
            description:
              'Please provide the ratio of employees with a bargaining agreement with respect to all your employees.',

            unit: '%',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'totalTrainingHoursMale',
            label: 'Total Training Hours Male',
            description:
              'Please state the total numbers of annual training hours per male employee, that are related to the development of skills and competences, whether acquired through formal or informal forms of capacity-building.',

            unit: 'h',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'totalTrainingHoursFemale',
            label: 'Total Training Hours Female',
            description:
              'Please state the total numbers of annual training hours per female employee, that are related to the development of skills and competences, whether acquired through formal or informal forms of capacity-building.',

            unit: 'h',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'averageTrainingHoursMale',
            label: 'Average Training Hours Male',
            description:
              'Please state average numbers of annual training hours per male employee that are related to the development of skills and competences, whether acquired through formal or informal forms of capacity-building.',

            unit: 'h',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'averageTrainingHoursFemale',
            label: 'Average Training Hours Female',
            description:
              'Please state average numbers of annual training hours per female employee that are related to the development of skills and competences, whether acquired through formal or informal forms of capacity-building.',

            unit: 'h',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'workersInTheValueChainAffectedCommunitiesConsumersAndEndUsers',
        label: 'Workers in the value chain, affected communities, consumers, and end-users',
        fields: [
          {
            name: 'negativeEffects',
            label: 'Negative Effects',
            description:
              'Please disclose whether you have a process in place for identifying wether there are value chain workers, affected communities, or consumers and end-users who are affected or are likely to be affected by severe negative impacts in relation to the undertaking’s operations (i.e., its products, services and activities). If this is in place, please describe this process. If identified, please also describe the types of impacts, including where they arise and the groups that are affected by them.',

            component: 'ListOfBaseDataPointsFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'numberOfConvictions',
            label: 'Number Of Convictions',
            description:
              'In case of convictions and fines in the reporting period, please disclose the number of convictions and the total amount of fines incurred for the violation of anti-corruption or anti-bribery laws.',

            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'sumOfFinesInEuro',
            label: 'Sum Of Fines',
            description: 'Please disclose the sum of all fines.',

            unit: 'Euro',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
] as Category[];
