// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.governance.stakeholderdialog

import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the Stakeholderdialog section
 */
data class EsgDatenkatalogGovernanceStakeholderdialog(
    val csrdKonformerProzessZurBeruecksichtigungDerStakeholderinteressen: YesNo? = null,
    val skizzierungDesCsrdKonformenProzessesZurBeruecksichtigungDerStakeholderinteressen: String? = null,
)
