// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.gdv.model.allgemein.sektoren

import io.swagger.v3.oas.annotations.media.Schema

/**
 * Enum class for the multi-select-field auflistungDerSektoren
 */
@Schema(
    enumAsRef = true,
)
enum class AuflistungDerSektorenOptions {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    L,
}
