// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.nuclearandgas.model.general.taxonomyAlignedNumerator

import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import org.dataland.datalandbackend.frameworks.nuclearandgas.custom.NuclearAndGasAlignedNumerator
import jakarta.validation.Valid

/**
 * The data-model for the TaxonomyAlignedNumerator section
 */
data class NuclearAndGasGeneralTaxonomyAlignedNumerator(
@field:Valid()
    val nuclearAndGasTaxonomyAlignedRevenueNumerator: ExtendedDataPoint<NuclearAndGasAlignedNumerator?>? = null,

@field:Valid()
    val nuclearAndGasTaxonomyAlignedCapexNumerator: ExtendedDataPoint<NuclearAndGasAlignedNumerator?>? = null,

)
