import {assertDefined} from "@/utils/TypeScriptUtils";

/**
 * @param target the camel case string we want to format
 * @returns a human readable version
 */
export function activityApiNameToHumanizedName(target: string): string {
    return assertDefined(Object.entries(ActivityName)
      .find(([key, value]) => key == target))[1]
}

/**
 * An enum that holds the EU taxonomy activities with their names as values
 */
enum ActivityName {
    Afforestation = "Afforestation",
    RehabilitationAndRestorationOfForestsIncludingReforestationAndNaturalForestRegenerationAfterAnExtremeEvent = "Rehabilitation and restoration of forests, including reforestation and natural forest regeneration after an extreme event",
    ForestManagement = "Forest management",
    ConservationForestry = "Conservation forestry",
    RestorationOfWetlands = "Restoration of wetlands",
    ManufactureOfRenewableEnergyTechnologies = "Manufacture of renewable energy technologies",
    ManufactureOfEquipmentForTheProductionAndUseOfHydrogen = "Manufacture of equipment for the production and use of hydrogen",
    ManufactureOfLowCarbonTechnologiesForTransport = "Manufacture of low carbon technologies for transport",
    ManufactureOfBatteries = "Manufacture of batteries",
    ManufactureOfEnergyEfficiencyEquipmentForBuildings = "Manufacture of energy efficiency equipment for buildings",
    ManufactureOfOtherLowCarbonTechnologies = "Manufacture of other low carbon technologies",
    ManufactureOfCement = "Manufacture of cement",
    ManufactureOfAluminium = "Manufacture of aluminium",
    ManufactureOfIronAndSteel = "Manufacture of iron and steel",
    ManufactureOfHydrogen = "Manufacture of hydrogen",
    ManufactureOfCarbonBlack = "Manufacture of carbon black",
    ManufactureOfSodaAsh = "Manufacture of soda ash",
    ManufactureOfChlorine = "Manufacture of chlorine",
    ManufactureOfOrganicBasicChemicals = "Manufacture of organic basic chemicals",
    ManufactureOfAnhydrousAmmonia = "Manufacture of anhydrous ammonia",
    ManufactureOfNitricAcid = "Manufacture of nitric acid",
    ManufactureOfPlasticsInPrimaryForm = "Manufacture of plastics in primary form",
    ElectricityGenerationUsingSolarPhotovoltaicTechnology = "Electricity generation using solar photovoltaic technology",
    ElectricityGenerationUsingConcentratedSolarPowerCspTechnology = "Electricity generation using concentrated solar power (CSP) technology",
    ElectricityGenerationFromWindPower = "Electricity generation from wind power",
    ElectricityGenerationFromOceanEnergyTechnologies = "Electricity generation from ocean energy technologies",
    ElectricityGenerationFromHydropower = "Electricity generation from hydropower",
    ElectricityGenerationFromGeothermalEnergy = "Electricity generation from geothermal energy",
    ElectricityGenerationFromRenewableNonFossilGaseousAndLiquidFuels = "Electricity generation from renewable non-fossil gaseous and liquid fuels",
    ElectricityGenerationFromBioenergy = "Electricity generation from bioenergy",
    TransmissionAndDistributionOfElectricity = "Transmission and distribution of electricity",
    StorageOfElectricity = "Storage of electricity",
    StorageOfThermalEnergy = "Storage of thermal energy",
    StorageOfHydrogen = "Storage of hydrogen",
    ManufactureOfBiogasAndBiofuelsForUseInTransportAndOfBioliquids = "Manufacture of biogas and biofuels for use in transport and of bioliquids",
    TransmissionAndDistributionNetworksForRenewableAndLowCarbonGases = "Transmission and distribution networks for renewable and low-carbon gases",
    DistrictHeatingCoolingDistribution = "District heating/cooling distribution",
    InstallationAndOperationOfElectricHeatPumps = "Installation and operation of electric heat pumps",
    CogenerationOfHeatCoolAndPowerFromSolarEnergy = "Cogeneration of heat/cool and power from solar energy",
    CogenerationOfHeatCoolAndPowerFromGeothermalEnergy = "Cogeneration of heat/cool and power from geothermal energy",
    CogenerationOfHeatCoolAndPowerFromRenewableNonFossilGaseousAndLiquidFuels = "Cogeneration of heat/cool and power from renewable non-fossil gaseous and liquid fuels",
    CogenerationOfHeatCoolAndPowerFromBioenergy = "Cogeneration of heat/cool and power from bioenergy",
    ProductionOfHeatCoolFromSolarThermalHeating = "Production of heat/cool from solar thermal heating",
    ProductionOfHeatCoolFromGeothermalEnergy = "Production of heat/cool from geothermal energy",
    ProductionOfHeatCoolFromRenewableNonFossilGaseousAndLiquidFuels = "Production of heat/cool from renewable non-fossil gaseous and liquid fuels",
    ProductionOfHeatCoolFromBioenergy = "Production of heat/cool from bioenergy",
    ProductionOfHeatCoolUsingWasteHeat = "Production of heat/cool using waste heat",
    PreCommercialStagesOfAdvancedTechnologiesToProduceEnergyFromNuclearProcessesWithMinimalWasteFromTheFuelCycle = "Pre-commercial stages of advanced technologies to produce energy from nuclear processes with minimal waste from the fuel cycle",
    ConstructionAndSafeOperationOfNewNuclearPowerPlantsForTheGenerationOfElectricityAndOrHeatIncludingForHydrogenProductionUsingBestAvailableTechnologies = "Construction and safe operation of new nuclear power plants, for the generation of electricity and/or heat, including for hydrogen production, using best-available technologies",
    ElectricityGenerationFromNuclearEnergyInExistingInstallations = "Electricity generation from nuclear energy in existing installations",
    ElectricityGenerationFromFossilGaseousFuels = "Electricity generation from fossil gaseous fuels",
    HighEfficiencyCoGenerationOfHeatCoolAndPowerFromFossilGaseousFuels = "High-efficiency co-generation of heat/cool and power from fossil gaseous fuels",
    ProductionOfHeatCoolFromFossilGaseousFuelsInAnEfficientDistrictHeatingAndCoolingSystem = "Production of heat/cool from fossil gaseous fuels in an efficient district heating and cooling system",
    ConstructionExtensionAndOperationOfWaterCollectionTreatmentAndSupplySystems = "Construction, extension and operation of water collection, treatment and supply systems",
    RenewalOfWaterCollectionTreatmentAndSupplySystems = "Renewal of water collection, treatment and supply systems",
    ConstructionExtensionAndOperationOfWasteWaterCollectionAndTreatment = "Construction, extension and operation of waste water collection and treatment",
    RenewalOfWasteWaterCollectionAndTreatment = "Renewal of waste water collection and treatment",
    CollectionAndTransportOfNonHazardousWasteInSourceSegregatedFractions = "Collection and transport of non-hazardous waste in source segregated fractions",
    AnaerobicDigestionOfSewageSludge = "Anaerobic digestion of sewage sludge",
    AnaerobicDigestionOfBioWaste = "Anaerobic digestion of bio-waste",
    CompostingOfBioWaste = "Composting of bio-waste",
    MaterialRecoveryFromNonHazardousWaste = "Material recovery from non-hazardous waste",
    LandfillGasCaptureAndUtilisation = "Landfill gas capture and utilisation",
    TransportOfCo2 = "Transport of CO2",
    UndergroundPermanentGeologicalStorageOfCo2 = "Underground permanent geological storage of CO2",
    PassengerInterurbanRailTransport = "Passenger interurban rail transport",
    FreightRailTransport = "Freight rail transport",
    UrbanAndSuburbanTransportRoadPassengerTransport = "Urban and suburban transport, road passenger transport",
    OperationOfPersonalMobilityDevicesCycleLogistics = "Operation of personal mobility devices, cycle logistics",
    TransportByMotorbikesPassengerCarsAndLightCommercialVehicles = "Transport by motorbikes, passenger cars and light commercial vehicles",
    FreightTransportServicesByRoad = "Freight transport services by road",
    InlandPassengerWaterTransport = "Inland passenger water transport",
    InlandFreightWaterTransport = "Inland freight water transport",
    RetrofittingOfInlandWaterPassengerAndFreightTransport = "Retrofitting of inland water passenger and freight transport",
    SeaAndCoastalFreightWaterTransportVesselsForPortOperationsAndAuxiliaryActivities = "Sea and coastal freight water transport, vessels for port operations and auxiliary activities",
    SeaAndCoastalPassengerWaterTransport = "Sea and coastal passenger water transport",
    RetrofittingOfSeaAndCoastalFreightAndPassengerWaterTransport = "Retrofitting of sea and coastal freight and passenger water transport",
    InfrastructureForPersonalMobilityCycleLogistics = "Infrastructure for personal mobility, cycle logistics",
    InfrastructureForRailTransport = "Infrastructure for rail transport",
    InfrastructureEnablingLowCarbonRoadTransportAndPublicTransport = "Infrastructure enabling low-carbon road transport and public transport",
    InfrastructureEnablingLowCarbonWaterTransport = "Infrastructure enabling low carbon water transport",
    LowCarbonAirportInfrastructure = "Low carbon airport infrastructure",
    ConstructionOfNewBuildings = "Construction of new buildings",
    RenovationOfExistingBuildings = "Renovation of existing buildings",
    InstallationMaintenanceAndRepairOfEnergyEfficiencyEquipment = "Installation, maintenance and repair of energy efficiency equipment",
    InstallationMaintenanceAndRepairOfChargingStationsForElectricVehiclesInBuildingsAndParkingSpacesAttachedToBuildings = "Installation, maintenance and repair of charging stations for electric vehicles in buildings (and parking spaces attached to buildings)",
    InstallationMaintenanceAndRepairOfInstrumentsAndDevicesForMeasuringRegulationAndControllingEnergyPerformanceOfBuildings = "Installation, maintenance and repair of instruments and devices for measuring, regulation and controlling energy performance of buildings",
    InstallationMaintenanceAndRepairOfRenewableEnergyTechnologies = "Installation, maintenance and repair of renewable energy technologies",
    AcquisitionAndOwnershipOfBuildings = "Acquisition and ownership of buildings",
    DataProcessingHostingAndRelatedActivities = "Data processing, hosting and related activities",
    DataDrivenSolutionsForGhgEmissionsReductions = "Data-driven solutions for GHG emissions reductions",
    CloseToMarketResearchDevelopmentAndInnovation = "Close to market research, development and innovation",
    ResearchDevelopmentAndInnovationForDirectAirCaptureOfCo2 = "Research, development and innovation for direct air capture of CO2",
    ProfessionalServicesRelatedToEnergyPerformanceOfBuildings = "Professional services related to energy performance of buildings",
    InfrastructureEnablingRoadTransportAndPublicTransport = "Infrastructure enabling road transport and public transport",
    InfrastructureForWaterTransport = "Infrastructure for water transport",
    AirportInfrastructure = "Airport infrastructure",
    ComputerProgrammingConsultancyAndRelatedActivities = "Computer programming, consultancy and related activities",
    ProgrammingAndBroadcastingActivities = "Programming and broadcasting activities",
    EngineeringActivitiesAndRelatedTechnicalConsultancyDedicatedToAdaptationToClimateChange = "Engineering activities and related technical consultancy dedicated to adaptation to climate change",
    NonLifeInsuranceUnderwritingOfClimateRelatedPerils = "Non-life insurance: underwriting of climate-related perils",
    Reinsurance = "Reinsurance",
    Education = "Education",
    ResidentialCareActivities = "Residential care activities",
    CreativeArtsAndEntertainmentActivities = "Creative, arts and entertainment activities",
    LibrariesArchivesMuseumsAndCulturalActivities = "Libraries, archives, museums and cultural activities",
    MotionPictureVideoAndTelevisionProgrammeProductionSoundRecordingAndMusicPublishingActivities = "Motion picture, video and television programme production, sound recording and music publishing activities",
}
