export const euTaxonomyForNonFinancialsModalColumnHeaders = {
  alignedActivities: {
    activityName: "Activity",
    naceCodes: "NACE Code(s)",
    share: "Share",
    revenue: "Revenue",
    revenuePercent: "Revenue (%)",
    substantialContributionToClimateChangeMitigation: "Climate Change Mitigation",
    substantialContributionToClimateChangeAdaption: "Climate Change Adaptation",
    substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResources: "Water and Marine Resources",
    substantialContributionToTransitionToACircularEconomy: "Circular Economy",
    substantialContributionToPollutionPreventionAndControl: "Pollution Prevention",
    substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystems: "Biodiversity and Ecosystems",
    dnshToClimateChangeMitigation: "Climate Change Mitigation",
    dnshToClimateChangeAdaption: "Climate Change Adaptation",
    dnshToSustainableUseAndProtectionOfWaterAndMarineResources: "Water and Marine Resources",
    dnshToTransitionToACircularEconomy: "Circular Economy",
    dnshToPollutionPreventionAndControl: "Pollution Prevention",
    dnshToProtectionAndRestorationOfBiodiversityAndEcosystems: "Biodiversity and Ecosystems",
    minimumSafeguards: "Minimum safeguards",
    substantialContributionCriteria: "Substantial Contribution Criteria",
    dnshCriteria: "DNSH Criteria",
  },
  nonAlignedActivities: {
    activityName: "Activity",
    naceCodes: "NACE Code(s)",
    share: "Share",
    revenue: "Revenue",
    revenuePercent: "Revenue (%)",
  },
};
