import { type Category } from "@/utils/GenericFrameworkTypes";

/*
Note: This file is not in the same state as it is in the devtools repo, where it has been auto-generated.
Manual adjustments have been made in oder to make the view page work while using this file here.
Therefore, the view page for eu-taxo will break if you replace the current content of this file here with the
content from the auto-generated file in the devtools repo.
 */

export const euTaxonomyForNonFinancialsDisplayDataModel = [
  {
    name: "basicInformation",
    label: "Basic Information",
    color: "orange",
    showIf: (): boolean => true,
    subcategories: [
      {
        name: "basicInformation",
        label: "Basic Information",
        fields: [
          {
            name: "fiscalYearDeviation",
            label: "Fiscal Year Deviation",
            description: "Fiscal Year (Deviation/ No Deviation)",
            unit: "",
            component: "RadioButtonsFormField",
            evidenceDesired: false,
            options: [
              {
                label: "Deviation",
                value: "Deviation",
              },
              {
                label: "No Deviation",
                value: "NoDeviation",
              },
            ],
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "fiscalYearEnd",
            label: "Fiscal Year End",
            description: "The date the fiscal year ends",
            unit: "",
            component: "DateFormField",
            evidenceDesired: false,
            required: true,
            showIf: (): boolean => true,
            validation: "required",
          },
          {
            name: "scopeOfEntities",
            label: "Scope Of Entities",
            description:
                "Does a list of legal entities covered by Sust./Annual/Integrated/ESEF report match with a list of legal entities covered by Audited Consolidated Financial Statement ",
            unit: "",
            component: "YesNoNaFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
            certificateRequiredIfYes: false,
          },
          {
            name: "euTaxonomyActivityLevelReporting",
            label: "EU Taxonomy Activity Level Reporting",
            description: "Activity Level disclosure",
            unit: "",
            component: "YesNoFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
            certificateRequiredIfYes: false,
          },
          {
            name: "numberOfEmployees",
            label: "Number Of Employees",
            description: "Total number of employees (including temporary workers)",
            unit: "",
            component: "NumberFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "nfrdMandatory",
            label: "NFRD Mandatory",
            description: "The reporting obligation for companies whose number of employees is greater or equal to 500",
            unit: "",
            component: "YesNoFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
            certificateRequiredIfYes: false,
          },
        ],
      },
    ],
  },
  {
    name: "assurance",
    label: "Assurance",
    showIf: (): boolean => true,
    subcategories: [
      {
        name: "assurance",
        label: "Assurance",
        fields: [
          {
            name: "levelOfAssurance",
            label: "Level of Assurance",
            description:
                "Level of Assurance of the EU Taxonomy disclosure (Reasonable Assurance, Limited Assurance, None)",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: true,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "assuranceProvider",
            label: "Assurance Provider",
            description: "Provider of the Assurance",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: true,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
  {
    name: "revenue",
    label: "Revenue",
    color: "yellow",
    showIf: (): boolean => true,
    subcategories: [
      {
        name: "totalAmount",
        label: "Total Revenue",
        fields: [
          {
            name: "quality",
            label: "Quality",
            description: "The quality of the provided data",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "value",
            label: "Value",
            description: "The provided data",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "dataSource",
            label: "Data Source",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => false,
          },
          {
            name: "comment",
            label: "Comment",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => false,
          },
          {
            name: "unit",
            label: "Currency",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "eligibleShare",
        label: "Eligible Revenue",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "alignedShare",
        label: "Aligned Revenue",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "substantialContributionToClimateChangeMitigation",
            label: "Substantial Contribution to Climate Change Mitigation",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToClimateChangeAdaption",
            label: "Substantial Contribution to Climate Change Adaption",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResources",
            label: "Substantial Contribution to Sustainable Use and Protection of Water and Marine Resources",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToTransitionToACircularEconomy",
            label: "Substantial Contribution to Transition to a Circular Economy",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToPollutionPreventionAndControl",
            label: "Substantial Contribution to Pollution Prevention and Control",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystems",
            label: "Substantial Contribution to Protection and Restoration of Biodiversity and Ecosystems",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "alignedActivities",
            label: "Aligned Revenue per Activity",
            description: "",
            unit: "",
            component: "AlignedActivitiesDataTable",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "nonAlignedShare",
        label: "Non-Aligned Revenue",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "nonAlignedActivities",
            label: "Non-Aligned Revenue per Activity",
            description: "",
            unit: "",
            component: "NonAlignedActivitiesDataTable",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "nonEligibleShare",
        label: "Non-Eligible Revenue",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "enablingShare",
        label: "Enabling Revenue",
        fields: [
          {
            name: "enablingShare",
            label: "Enabling Revenue",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "transitionalShare",
        label: "Transitional Revenue",
        fields: [
          {
            name: "transitionalShare",
            label: "Transitional Revenue",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
  {
    name: "capex",
    label: "CapEx",
    color: "green",
    showIf: (): boolean => true,
    subcategories: [
      {
        name: "totalAmount",
        label: "Total CapEx",
        fields: [
          {
            name: "quality",
            label: "Quality",
            description: "The quality of the provided data",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "value",
            label: "Value",
            description: "The provided data",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "dataSource",
            label: "Data Source",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => false,
          },
          {
            name: "comment",
            label: "Comment",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => false,
          },
          {
            name: "unit",
            label: "Currency",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "eligibleShare",
        label: "Eligible CapEx",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "alignedShare",
        label: "Aligned CapEx",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "substantialContributionToClimateChangeMitigation",
            label: "Substantial Contribution to Climate Change Mitigation",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToClimateChangeAdaption",
            label: "Substantial Contribution to Climate Change Adaption",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResources",
            label: "Substantial Contribution to Sustainable Use and Protection of Water and Marine Resources",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToTransitionToACircularEconomy",
            label: "Substantial Contribution to Transition to a Circular Economy",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToPollutionPreventionAndControl",
            label: "Substantial Contribution to Pollution Prevention and Control",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystems",
            label: "Substantial Contribution to Protection and Restoration of Biodiversity and Ecosystems",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "alignedActivities",
            label: "Aligned CapEx per Activity",
            description: "",
            unit: "",
            component: "AlignedActivitiesDataTable",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "nonAlignedShare",
        label: "Non-Aligned CapEx",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "nonAlignedActivities",
            label: "Non-Aligned CapEx per Activity",
            description: "",
            unit: "",
            component: "NonAlignedActivitiesDataTable",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "nonEligibleShare",
        label: "Non-Eligible CapEx",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "enablingShare",
        label: "Enabling CapEx",
        fields: [
          {
            name: "enablingShare",
            label: "Enabling CapEx",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "transitionalShare",
        label: "Transitional CapEx",
        fields: [
          {
            name: "transitionalShare",
            label: "Transitional CapEx",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
  {
    name: "opex",
    label: "OpEx",
    color: "blue",
    showIf: (): boolean => true,
    subcategories: [
      {
        name: "totalAmount",
        label: "Total OpEx",
        fields: [
          {
            name: "quality",
            label: "Quality",
            description: "The quality of the provided data",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "value",
            label: "Value",
            description: "The provided data",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "dataSource",
            label: "Data Source",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => false,
          },
          {
            name: "comment",
            label: "Comment",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => false,
          },
          {
            name: "unit",
            label: "Currency",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "eligibleShare",
        label: "Eligible OpEx",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "alignedShare",
        label: "Aligned OpEx",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "substantialContributionToClimateChangeMitigation",
            label: "Substantial Contribution to Climate Change Mitigation",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToClimateChangeAdaption",
            label: "Substantial Contribution to Climate Change Adaption",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToSustainableUseAndProtectionOfWaterAndMarineResources",
            label: "Substantial Contribution to Sustainable Use and Protection of Water and Marine Resources",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToTransitionToACircularEconomy",
            label: "Substantial Contribution to Transition to a Circular Economy",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToPollutionPreventionAndControl",
            label: "Substantial Contribution to Pollution Prevention and Control",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "substantialContributionToProtectionAndRestorationOfBiodiversityAndEcosystems",
            label: "Substantial Contribution to Protection and Restoration of Biodiversity and Ecosystems",
            showIf: (): boolean => true,
            description: "",
            component: "UndefinedFormField",
          },
          {
            name: "alignedActivities",
            label: "Aligned OpEx per Activity",
            description: "",
            unit: "",
            component: "AlignedActivitiesDataTable",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "nonAlignedShare",
        label: "Non-Aligned OpEx",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "nonAlignedActivities",
            label: "Non-Aligned OpEx per Activity",
            description: "",
            unit: "",
            component: "NonAlignedActivitiesDataTable",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "nonEligibleShare",
        label: "Non-Eligible OpEx",
        fields: [
          {
            name: "relativeShareInPercent",
            label: "Percentage",
            description: "The relative share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "absoluteShare",
            label: "Absolute share",
            description: "The absolute share on the financial asset",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "enablingShare",
        label: "Enabling OpEx",
        fields: [
          {
            name: "enablingShare",
            label: "Enabling OpEx",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: "transitionalShare",
        label: "Transitional OpEx",
        fields: [
          {
            name: "transitionalShare",
            label: "Transitional OpEx",
            description: "",
            unit: "",
            component: "UndefinedFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
] as Array<Category>;