import { Category } from "@/utils/GenericFrameworkTypes";
import { DropdownDatasetIdentifier, getDataset } from "@/utils/PremadeDropdownDatasets";

export const euTaxonomyForNonFinancialsDataModel = [
  {
    name: "general",
    label: "General",
    color: "orange",
    showIf: (): boolean => true,
    subcategories: [
      {
        name: "general",
        label: "General",
        fields: [
          {
            name: "fiscalYearDeviation",
            label: "Fiscal Year Deviation",
            description: "Fiscal Year (Deviation/ No Deviation)",
            unit: "",
            component: "RadioButtonsFormField",
            evidenceDesired: false,
            options: [
              {
                label: "Deviation",
                value: "Deviation",
              },
              {
                label: "No Deviation",
                value: "NoDeviation",
              },
            ],
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "fiscalYearEnd",
            label: "Fiscal Year End",
            description: "The date the fiscal year ends",
            unit: "",
            component: "DateFormField",
            evidenceDesired: false,
            required: true,
            showIf: (): boolean => true,
            validation: "required",
          },
          {
            name: "referencedReports",
            label: "Referenced Reports",
            description:
              "Does your company have a current annual report, sustainability report, integrated report or ESEF report? If yes, please share the information with us.",
            unit: "",
            component: "UploadReports",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "scopeOfEntities",
            label: "Scope Of Entities",
            description:
              "Does a list of legal entities covered by Sust./Annual/Integrated/ESEF report match with a list of legal entities covered by Audited Consolidated Financial Statement ",
            unit: "",
            component: "YesNoNaFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
            certificateRequiredIfYes: false,
          },
          {
            name: "euTaxonomyActivityLevelReporting",
            label: "EU Taxonomy Activity Level Reporting",
            description: "Activity Level disclosure",
            unit: "",
            component: "YesNoFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
            certificateRequiredIfYes: false,
          },
          {
            name: "numberOfEmployees",
            label: "Number Of Employees",
            description: "Total number of employees (including temporary workers)",
            unit: "",
            component: "NumberFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
            validation: "min:0",
          },
          {
            name: "nfrdMandatory",
            label: "NFRD Mandatory",
            description: "The reporting obligation for companies whose number of employees is greater or equal to 500",
            unit: "",
            component: "YesNoFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
            certificateRequiredIfYes: false,
          },
          {
            name: "assurance",
            label: "Assurance",
            description:
              "Level of Assurance of the EU Taxonomy disclosure (Reasonable Assurance, Limited Assurance, None)",
            unit: "",
            component: "AssuranceFormField",
            evidenceDesired: true,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
  {
    name: "revenue",
    label: "Revenue",
    color: "orange",
    showIf: (): boolean => true,
    subcategories: [
      {
        name: "revenue",
        label: "Revenue",
        fields: [
          {
            name: "totalAmount",
            label: "Total Revenue",
            description:
              "Total Revenue for the financial year. I.e. income arising in the course of an entity's ordinary activities., the amounts derived from the sale of products and the provision of services after deducting sales rebates and value added tax and other taxes directly linked to turnover. Overall turnover is equivalent to a firm's total revenues over some period of time",
            unit: "",
            component: "DataPointFormField",
            evidenceDesired: true,
            options: getDataset(DropdownDatasetIdentifier.CurrencyCodes),
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalEligibleShare",
            label: "Total Eligible Revenue",
            description:
              "Absolute value and share of the revenue where the economic activity meets taxonomy criteria for substantial contribution to climate change mitigation and does no serious harm to the other environmental objectives (DNSH criteria)",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalAlignedShare",
            label: "Total Aligned Revenue",
            description:
              "Absolute value and share of the revenue that is taxonomy-aligned, i.e., generated by an eligible economic activity that is making a substantial contribution to at least one of the climate and environmental objectives, while also doing no significant harm to the remaining objectives and meeting minimum standards on human rights and labour standards",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "substantialContributionCriteria",
            label: "Substantial Contribution Criteria",
            fields: [
              {
                name: "climateMitigation",
                label: "Substantial Contribution to Climate Change Mitigation",
                description: "",
                unit: "Percentage",
                component: "PercentageFormField",
                evidenceDesired: false,
                required: false,
                showIf: (): boolean => true,
              },
              {
                name: "climateAdaptation",
                label: "Substantial Contribution to Climate Change Adaption",
                description: "",
                unit: "Percentage",
                component: "PercentageFormField",
                evidenceDesired: false,
                required: false,
                showIf: (): boolean => true,
              },
              {
                name: "water",
                label: "Substantial Contribution to Sustainable Use and Protection of Water and Marine Resources",
                description: "",
                unit: "Percentage",
                component: "PercentageFormField",
                evidenceDesired: false,
                required: false,
                showIf: (): boolean => true,
              },
              {
                name: "circularEconomy",
                label: "Substantial Contribution to Transition to a Circular Economy",
                description: "",
                unit: "Percentage",
                component: "PercentageFormField",
                evidenceDesired: false,
                required: false,
                showIf: (): boolean => true,
              },
              {
                name: "pollutionPrevention",
                label: "Substantial Contribution to Pollution Prevention and Control",
                description: "",
                unit: "Percentage",
                component: "PercentageFormField",
                evidenceDesired: false,
                required: false,
                showIf: (): boolean => true,
              },
              {
                name: "biodiversity",
                label: "Substantial Contribution to Protection and Restoration of Biodiversity and Ecosystems",
                description: "",
                unit: "Percentage",
                component: "PercentageFormField",
                evidenceDesired: false,
                required: false,
                showIf: (): boolean => true,
              },
            ],
          },
          {
            name: "alignedActivities",
            label: "Aligned Revenue per Activity",
            description: "",
            unit: "",
            component: "AlignedActivitiesFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalNonAlignedShare",
            label: "Total Non-Aligned Revenue",
            description: "Absolute value and share",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "nonAlignedActivities",
            label: "Non-Aligned Revenue per Activity",
            description: "",
            unit: "",
            component: "NonAlignedActivitiesFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalNonEligibleShare",
            label: "Total Non-Eligible Revenue",
            description: "Absolute value and share",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalEnablingShare",
            label: "Total Enabling Revenue",
            description: "",
            unit: "",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalTransitionalShare",
            label: "Total Transitional Revenue",
            description: "",
            unit: "",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
  {
    name: "capex",
    label: "CapEx",
    color: "yellow",
    showIf: (): boolean => true,
    subcategories: [
      {
        name: "capex",
        label: "CapEx",
        fields: [
          {
            name: "totalAmount",
            label: "Total CapEx",
            description:
              "Total CapEx for the financial year. A capital expenditure (CapEx) is a payment for goods or services recorded, or capitalized, on the balance sheet instead of expensed on the income statement",
            unit: "",
            component: "DataPointFormField",
            evidenceDesired: true,
            options: getDataset(DropdownDatasetIdentifier.CurrencyCodes),
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalEligibleShare",
            label: "Total Eligible CapEx",
            description:
              "Absolute value and share of the CapEx that is part of a plan to meet taxonomy criteria for substantial contribution to either climate change mitigation or climate change adaptation",
            unit: "",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalAlignedShare",
            label: "Total Aligned CapEx",
            description:
              "Absolute value and share of the CapEx that is either already taxonomy-aligned or is part of a credible plan to extend or reach taxonomy alignment, i.e., an eligible economic activity that is making a substantial contribution to at least one of the climate and environmental objectives, while also doing no significant harm to the remaining objectives and meeting minimum standards on human rights and labour standards",
            unit: "",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "climateMitigation",
            label: "Substantial Contribution to Climate Change Mitigation",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "climateAdaptation",
            label: "Substantial Contribution to Climate Change Adaption",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "water",
            label: "Substantial Contribution to Sustainable Use and Protection of Water and Marine Resources",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "circularEconomy",
            label: "Substantial Contribution to Transition to a Circular Economy",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "pollutionPrevention",
            label: "Substantial Contribution to Pollution Prevention and Control",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "biodiversity",
            label: "Substantial Contribution to Protection and Restoration of Biodiversity and Ecosystems",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "alignedActivities",
            label: "Aligned CapEx per Activity",
            description: "",
            unit: "",
            component: "AlignedActivitiesFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalNonAlignedShare",
            label: "Total Non-Aligned CapEx",
            description: "Absolute value and share",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "nonAlignedActivities",
            label: "Non-Aligned CapEx per Activity",
            description: "",
            unit: "",
            component: "NonAlignedActivitiesFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalNonEligibleShare",
            label: "Total Non-Eligible CapEx",
            description: "Absolute value and share",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalEnablingShare",
            label: "Total Enabling CapEx",
            description: "",
            unit: "",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalTransitionalShare",
            label: "Total Transitional CapEx",
            description: "",
            unit: "",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
  {
    name: "opex",
    label: "OpEx",
    color: "blue",
    showIf: (): boolean => true,
    subcategories: [
      {
        name: "opex",
        label: "OpEx",
        fields: [
          {
            name: "totalAmount",
            label: "Total OpEx",
            description:
              "Total OpEx for the financial year. Operating expenses (OpEx) are shorter term expenses required to meet the ongoing operational costs of running a business",
            unit: "",
            component: "DataPointFormField",
            evidenceDesired: true,
            options: getDataset(DropdownDatasetIdentifier.CurrencyCodes),
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalEligibleShare",
            label: "Total Eligible OpEx",
            description:
              "Absolute value and share of the OpEx that is part of a plan to meet the taxonomy criteria for substantial contribution to climate change adaptation and relevant DNSH criteria",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalAlignedShare",
            label: "Total Aligned OpEx",
            description:
              "Absolute value and share of the OpEx that is associated with taxonomy-aligned activities. i.e., for an eligible economic activity that is making a substantial contribution to at least one of the climate and environmental objectives, while also doing no significant harm to the remaining objectives and meeting minimum standards on human rights and labour standards",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "climateMitigation",
            label: "Substantial Contribution to Climate Change Mitigation",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "climateAdaptation",
            label: "Substantial Contribution to Climate Change Adaption",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "water",
            label: "Substantial Contribution to Sustainable Use and Protection of Water and Marine Resources",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "circularEconomy",
            label: "Substantial Contribution to Transition to a Circular Economy",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "pollutionPrevention",
            label: "Substantial Contribution to Pollution Prevention and Control",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "biodiversity",
            label: "Substantial Contribution to Protection and Restoration of Biodiversity and Ecosystems",
            description: "",
            unit: "Percentage",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "alignedActivities",
            label: "Aligned OpEx per Activity",
            description: "",
            unit: "",
            component: "AlignedActivitiesFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalNonAlignedShare",
            label: "Total Non-Aligned OpEx",
            description: "Absolute value and share",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "nonAlignedActivities",
            label: "Non-Aligned OpEx per Activity",
            description: "",
            unit: "",
            component: "NonAlignedActivitiesFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalNonEligibleShare",
            label: "Total Non-Eligible OpEx",
            description: "Absolute value and share",
            unit: "(Percentage)",
            component: "FinancialShareFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalEnablingShare",
            label: "Total Enabling OpEx",
            description: "",
            unit: "",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: "totalTransitionalShare",
            label: "Total Transitional OpEx",
            description: "",
            unit: "",
            component: "PercentageFormField",
            evidenceDesired: false,
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
] as Array<Category>;
