import { type PathwaysToParisData, P2pSector } from '@clients/backend';
import { type Category } from '@/utils/GenericFrameworkTypes';

export const p2pDataModel = [
  {
    name: 'general',
    label: 'General',
    color: 'orange',
    showIf: (): boolean => true,
    subcategories: [
      {
        name: 'general',
        label: 'General',
        fields: [
          {
            name: 'dataDate',
            label: 'Data Date',
            description: 'The date until when the information collected is valid',
            unit: '',
            component: 'DateFormField',
            required: true,
            showIf: (): boolean => true,
            validation: 'required',
          },
          {
            name: 'sectors',
            label: 'Sectors',
            description: 'To which sectors does the company belong?',
            unit: '',
            component: 'MultiSelectFormField',
            options: [
              {
                label: 'Ammonia',
                value: 'Ammonia',
              },
              {
                label: 'Automotive',
                value: 'Automotive',
              },
              {
                label: 'HVC Plastics',
                value: 'HVCPlastics',
              },
              {
                label: 'Commercial Real Estate',
                value: 'CommercialRealEstate',
              },
              {
                label: 'Residential Real Estate',
                value: 'ResidentialRealEstate',
              },
              {
                label: 'Steel',
                value: 'Steel',
              },
              {
                label: 'Freight Transport by Road',
                value: 'FreightTransportByRoad',
              },
              {
                label: 'Electricity Generation',
                value: 'ElectricityGeneration',
              },
              {
                label: 'Livestock Farming',
                value: 'LivestockFarming',
              },
              {
                label: 'Cement',
                value: 'Cement',
              },
              {
                label: 'Other',
                value: 'Other',
              },
            ],
            required: true,
            showIf: (): boolean => true,
            validation: 'required|length:1',
            placeholder: 'Select Sectors',
          },
        ],
      },
      {
        name: 'governance',
        label: 'Governance',
        fields: [
          {
            name: 'organisationalResponsibilityForParisCompatibility',
            label: 'Organisational responsibility for Paris compatibility',
            description:
              'Whether or not the organisational responsibility for Paris compatibility in the company lies with the Executive Board/Management',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'parisCompatibilityInExecutiveRemunerationInPercent',
            label: 'Paris compatibility in executive remuneration',
            description:
              'Share of executive managers with variable pay for meeting climate targets and transformation plans',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'parisCompatibilityInAverageRemunerationInPercent',
            label: 'Paris compatibility in average remuneration',
            description: 'Average share of variable pay linked to climate targets in the remuneration system',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'shareOfEmployeesTrainedOnParisCompatibilityInPercent',
            label: 'Share of employees trained on Paris compatibility',
            description:
              'Share of employees who have been trained at least once, on how to integrate a Paris-compatible strategy into everyday work processes',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'qualificationRequirementsOnParisCompatibility',
            label: 'Qualification requirements on Paris compatibility',
            description:
              'Qualification requirements and/or mandatory Paris-compatibility training for top management and employees established',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'mobilityAndTravelPolicy',
            label: 'Mobility and travel policy',
            description: 'Existence of a Paris-compatible mobility and travel policy',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'upstreamSupplierEngagementStrategy',
            label: 'Upstream supplier engagement strategy',
            description:
              'Existence of a fit-for-purpose engagement strategy with relevant processes for the upstream supply chain',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'upstreamSupplierProcurementPolicy',
            label: 'Upstream supplier procurement policy',
            description: 'Existence of a Paris-compatible procurement policy. If yes, please share the policy with us.',
            unit: '',
            component: 'YesNoBaseDataPointFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'downstreamCustomerEngagement',
            label: 'Downstream customer engagement',
            description: 'Existence of a fit-for-purpose engagement strategy with relevant processes for customers',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'policymakerEngagement',
            label: 'Policymaker engagement',
            description:
              'Lobbying/advocacy: support for Paris-compatible lobbying activities in industry and business associations',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'climateTargets',
        label: 'Climate Targets',
        fields: [
          {
            name: 'shortTermScienceBasedClimateTarget',
            label: 'Short-term science-based climate target',
            description: 'Existence of a science-based Paris-compatible climate target (short-term target: 5-10 years)',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'longTermScienceBasedClimateTarget',
            label: 'Long-term science-based climate target',
            description: 'Existence of a science-based Paris-compatible climate target (long-term target: > 10 years)',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'emissionsPlanning',
        label: 'Emissions planning',
        fields: [
          {
            name: 'absoluteEmissionsInTonnesCO2e',
            label: 'Absolute emissions',
            description:
              'Transparent accounting & disclosure of all greenhouse gas emissions (Scope 1, Scope 2, Scope 3) along the following metric: absolute emissions (t CO2e)',
            unit: 'tonnes CO2e',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'relativeEmissionsInPercent',
            label: 'Relative emissions',
            description:
              'Transparent accounting & disclosure of all greenhouse gas emissions (Scope 1, Scope 2, Scope 3) along the following metric: relative emissions (if applicable) (t CO2e / output unit)',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'reductionOfAbsoluteEmissionsInTonnesCO2e',
            label: 'Reduction of absolute emissions',
            description:
              'Use of a science-based, sector-specific Paris-compatible GHG emission reduction trajectory (Scopes 1-3) to meet climate targets and net-zero commitments represented in absolute emissions (t CO2e)',
            unit: 'tonnes CO2e',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'reductionOfRelativeEmissionsInPercent',
            label: 'Reduction of relative emissions',
            description:
              'Use of a science-based, sector-specific Paris-compatible GHG emission reduction trajectory (Scopes 1-3) to meet climate targets and net-zero commitments represented in relative emissions (if applicable) (t CO2e / output unit)',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'climateActionPlan',
            label: 'Climate action plan',
            description:
              'Existence of a transition plan to meet climate targets and net-zero commitments. Plausible emission reduction measures to achieve these GHG reduction targets (the sectoral indicators, among others, are used for Scopes 1 and 2); Ideally: Min. every 5 years, external validation of the progress achieved compared to the selected Paris-compatible transformation pathway to achieve set climate targets (ideally SBT -1.5 °C).',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'useOfInternalCarbonPrice',
            label: 'Use of internal carbon price',
            description:
              'The internal/imputed/shadow carbon price and its dynamic structure is derived from science-based models and scenarios that are consistent with the Paris targets.',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'investmentPlanning',
        label: 'Investment planning',
        fields: [
          {
            name: 'investmentPlanForClimateTargets',
            label: 'Investment plan for climate targets',
            description: 'Investment planning consistently reflects emissions and GHG-reduction measures planning',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'capexShareInNetZeroSolutionsInPercent',
            label: 'CapEx share in net-zero solutions',
            description: 'Share of CapEx in net-zero solutions over the next 10 years of total CapEx',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'capexShareInGhgIntensivePlantsInPercent',
            label: 'CapEx share in GHG-intensive plants',
            description: 'Share of CapEx on GHG-intensive production plants over the next 10 years of total CapEx',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'researchAndDevelopmentExpenditureForNetZeroSolutionsInPercent',
            label: 'Research and development expenditure for net-zero solutions',
            description: 'Share of CapEx on research & development activities for net-zero solutions of total CapEx',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'ammonia',
    label: 'Ammonia',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.Ammonia) ?? false,
    subcategories: [
      {
        name: 'decarbonisation',
        label: 'Decarbonisation',
        fields: [
          {
            name: 'energyMixInPercent',
            label: 'Energy mix',
            description: 'Share of renewable energy in total electricity consumption',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'ccsTechnologyAdoptionInPercent',
            label: 'CCS technology adoption',
            description: 'Share of emissions accounted for by captured emissions in total emissions',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'electrificationInPercent',
            label: 'Electrification',
            description: 'Degree of electrification of the ammonia production plant(s)',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'defossilisation',
        label: 'Defossilisation',
        fields: [
          {
            name: 'useOfRenewableFeedstocksInPercent',
            label: 'Use of renewable feedstocks',
            description: 'Share of alternative, renewable feedstocks in total raw material use',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'automotive',
    label: 'Automotive',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.Automotive) ?? false,
    subcategories: [
      {
        name: 'energy',
        label: 'Energy',
        fields: [
          {
            name: 'productionSiteEnergyConsumptionInMWh',
            label: 'Production site energy consumption',
            description: "Absolute total energy consumption of the company's production sites (MWh)",
            unit: 'MWh',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'energyMixInPercent',
            label: 'Energy mix',
            description: 'Share of renewable energy in total electricity consumption',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'technologyValueCreation',
        label: 'Technology/value creation',
        fields: [
          {
            name: 'driveMixInPercent',
            label: 'Drive mix',
            description:
              'For manufacturers: Share of zero emission vehicles in new vehicles registered. For suppliers: Target use of the drive-relevant technologies',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'icAndHybridEnginePhaseOutDate',
            label: 'IC & hybrid engine phase-out date',
            description: 'Phase-out date of internal combustion engine and hybrid engine (end or exit date)',
            unit: '',
            component: 'DateFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'futureValueCreationStrategy',
            label: 'Future value creation strategy',
            description: 'Strategy for generating future value creation in the changing marketplace',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'materials',
        label: 'Materials',
        fields: [
          {
            name: 'materialUseManagementInPercent',
            label: 'Material use management',
            description: 'Share of CO2-free or low-carbon metals in total material use',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'useOfSecondaryMaterialsInPercent',
            label: 'Use of secondary materials',
            description: 'Share of secondary materials in total material use',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'hvcPlastics',
    label: 'HVC Plastics',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.HvcPlastics) ?? false,
    subcategories: [
      {
        name: 'decarbonisation',
        label: 'Decarbonisation',
        fields: [
          {
            name: 'energyMixInPercent',
            label: 'Energy mix',
            description: 'Share of renewable energy in total electricity consumption',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'electrificationInPercent',
            label: 'Electrification',
            description: 'Share of electricity-based production',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'defossilisation',
        label: 'Defossilisation',
        fields: [
          {
            name: 'useOfRenewableFeedstocksInPercent',
            label: 'Use of renewable feedstocks',
            description: 'Share of alternative, renewable feedstocks in total feedstock use',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'useOfBioplasticsInPercent',
            label: 'Use of bioplastics',
            description: 'Share of bioplastics in total feedstock use',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'useOfCo2FromCarbonCaptureAndReUseTechnologiesInPercent',
            label: 'Use of CO2 from Carbon capture and re-use technologies',
            description: 'Share of CO2 as feedstock from non-fossil sources',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'carbonCaptureAndUseStorageTechnologies',
            label: 'Carbon capture and use/storage technologies',
            description: 'Set up / use of own CO2 capture plants',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'recycling',
        label: 'Recycling',
        fields: [
          {
            name: 'contributionToCircularEconomy',
            label: 'Contribution to circular economy',
            description:
              'Circular economy, which includes avoidance, reduction and reuse as well as recycling, is strategically anchored in the company through, for example, plans for the use of recycled materials in production or adjustments to the product design to enable reprocessing.',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'materialRecyclingInPercent',
            label: 'Material recycling',
            description: 'Share of recyclates in total feedstock use',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'chemicalRecyclingInPercent',
            label: 'Chemical recycling',
            description: 'Share of materials from chemical recycling in total feedstock use',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'commercialRealEstate',
    label: 'Commercial Real Estate',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.CommercialRealEstate) ?? false,
    subcategories: [
      {
        name: 'buildingEfficiency',
        label: 'Building efficiency',
        fields: [
          {
            name: 'buildingSpecificRefurbishmentRoadmapInPercent',
            label: 'Building-specific refurbishment roadmap',
            description:
              'Share of buildings with a building-specific refurbishment roadmap that corresponds to the GHG emission reduction trajectory in total commercial buildings portfolio',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'zeroEmissionBuildingShareInPercent',
            label: 'Zero-emission building share',
            description: 'Share of zero-emission buildings in the total commercial building portfolio',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'buildingEnergyEfficiencyInCorrespondingUnit',
            label: 'Building energy efficiency',
            description: 'Average energy requirement in kWh/m²a',
            unit: 'kWh/m²a',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'energySource',
        label: 'Energy source',
        fields: [
          {
            name: 'renewableHeatingInPercent',
            label: 'Renewable heating',
            description: 'Share of heat from renewable sources of total heat supply',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'technology',
        label: 'Technology',
        fields: [
          {
            name: 'useOfDistrictHeatingNetworksInPercent',
            label: 'Use of (district) heating networks',
            description: 'Share of heat from (district) heating networks',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'heatPumpUsageInPercent',
            label: 'Heat pump usage',
            description: 'Share of heat from heat pumps (installed or implementation planned)',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'residentialRealEstate',
    label: 'Residential Real Estate',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.ResidentialRealEstate) ?? false,
    subcategories: [
      {
        name: 'buildingEfficiency',
        label: 'Building efficiency',
        fields: [
          {
            name: 'buildingSpecificRefurbishmentRoadmapInPercent',
            label: 'Building-specific refurbishment roadmap',
            description:
              'Share of buildings with a building-specific refurbishment roadmap that corresponds to the GHG emission reduction trajectory in total residential buildings portfolio',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'zeroEmissionBuildingShareInPercent',
            label: 'Zero-emission building share',
            description: 'Share of zero-emission buildings in the total residential building portfolio',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'buildingEnergyEfficiencyInCorrespondingUnit',
            label: 'Building energy efficiency',
            description: 'Average energy requirement in kWh/m²a',
            unit: 'kWh/m²a',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'energySource',
        label: 'Energy source',
        fields: [
          {
            name: 'renewableHeatingInPercent',
            label: 'Renewable heating',
            description: 'Share of heat from renewable sources of total heat supply',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'technology',
        label: 'Technology',
        fields: [
          {
            name: 'useOfDistrictHeatingNetworksInPercent',
            label: 'Use of (district) heating networks',
            description: 'Share of heat from (district) heating networks',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'heatPumpUsageInPercent',
            label: 'Heat pump usage',
            description: 'Share of heat from heat pumps (installed or implementation planned)',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'steel',
    label: 'Steel',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.Steel) ?? false,
    subcategories: [
      {
        name: 'energy',
        label: 'Energy',
        fields: [
          {
            name: 'emissionIntensityOfElectricityInCorrespondingUnit',
            label: 'Emission intensity of electricity',
            description: 'Applies especially for use of electric arc furnace (EAF) (gCO2e/kWh)',
            unit: 'gCO2e/kWh',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'greenHydrogenUsage',
            label: 'Green hydrogen usage',
            description:
              'Use of green hydrogen according to the EU Taxonomy (only for hydrogen-based steel production)',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'technology',
        label: 'Technology',
        fields: [
          {
            name: 'blastFurnacePhaseOutInPercent',
            label: 'Blast furnace phase-out',
            description:
              'Phase-out pathway: Share of steel produced without CCS in steel production of the blast furnace route',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'lowCarbonSteelScaleUpInPercent',
            label: 'Low carbon steel scale-up',
            description: 'Scale-up pathway: share of no /low carbon steel in total steel production',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'freightTransportByRoad',
    label: 'Freight transport by road',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.FreightTransportByRoad) ?? false,
    subcategories: [
      {
        name: 'technology',
        label: 'Technology',
        fields: [
          {
            name: 'driveMixPerFleetSegment',
            label: 'Drive mix per fleet segment',
            description: 'Share of alternative drive types per fleet segment',
            unit: '',
            component: 'DriveMixFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'icePhaseOut',
            label: 'ICE phase-out',
            description: 'Internal combustion engine phase-out',
            unit: '',
            component: 'DateFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
      {
        name: 'energy',
        label: 'Energy',
        fields: [
          {
            name: 'fuelMixInPercent',
            label: 'Fuel mix',
            description: 'Share of biofuels blended into Diesel',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'electricityGeneration',
    label: 'Electricity generation',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.ElectricityGeneration) ?? false,
    subcategories: [
      {
        name: 'technology',
        label: 'Technology',
        fields: [
          {
            name: 'electricityMixEmissionsInCorrespondingUnit',
            label: 'Electricity mix emissions',
            description: 'Emission intensity of the created electricity mix (t CO2e /MWh)',
            unit: 'tCO2e/MWh',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'shareOfRenewableElectricityInPercent',
            label: 'Share of renewable electricity',
            description: 'Share of electricity produced from renewables in total electricity production',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'naturalGasPhaseOut',
            label: 'Natural gas phase-out',
            description: 'Phase-out plan, including year',
            unit: '',
            component: 'DateFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'coalPhaseOut',
            label: 'Coal phase-out',
            description: 'Phase-out plan, including year',
            unit: '',
            component: 'DateFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'storageCapacityExpansionInPercent',
            label: 'Storage capacity expansion',
            description: 'Share of storage of average daily production in total electricity production',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'livestockFarming',
    label: 'Livestock farming',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.LivestockFarming) ?? false,
    subcategories: [
      {
        name: 'emissionsFromManureAndFertiliserAndLivestock',
        label: 'Emissions from manure and fertiliser and livestock',
        fields: [
          {
            name: 'compostedFermentedManureInPercent',
            label: 'Composted/fermented manure',
            description:
              'Share of composted or fermented manure in the total amount of manure produced in indoor livestock systems',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'emissionProofFertiliserStorageInPercent',
            label: 'Emission-proof fertiliser storage',
            description:
              'Share of emission-proof storage of fertilizer in the total amount of fertilizer from indoor livestock systems',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'animalWelfare',
        label: 'Animal welfare',
        fields: [
          {
            name: 'mortalityRateInPercent',
            label: 'Mortality rate',
            description: 'Annual rate',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'animalFeed',
        label: 'Animal feed',
        fields: [
          {
            name: 'ownFeedInPercent',
            label: 'Own feed percentage',
            description: 'Share of own feed in total feed quantity',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'externalFeedCertification',
            label: 'External feed certification',
            description:
              'E.g. deforestation-free feed, feed production in compliance with minimum social standards (e.g. ILO labour standards, exclusion of displacement of indigenous people). If yes, please share the document(s) with us.',
            unit: '',
            component: 'YesNoBaseDataPointFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'originOfExternalFeed',
            label: 'Origin of external feed',
            description:
              'Qualitative assessment of regional risks of origin (e.g. deforestation of rainforest, displacement of indigenous peoples for feed production) and the transport route.',
            unit: '',
            component: 'InputTextFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'excessNitrogenInKilogramsPerHectare',
            label: 'Excess nitrogen',
            description: 'Excess nitrogen in kg/ha',
            unit: 'kg/ha',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'cropRotation',
            label: 'Crop rotation',
            description: 'Number of crops in rotation',
            unit: '',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'climateFriendlyProteinProductionInPercent',
            label: 'Climate-friendly protein production',
            description:
              'Share of climate-friendly proteins farmed in the total amount of protein in the concentrated feed used',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'greenFodderInPercent',
            label: 'Green fodder percentage',
            description: 'Share of green fodder in the total feed quantity',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'energy',
        label: 'Energy',
        fields: [
          {
            name: 'renewableElectricityInPercent',
            label: 'Renewable electricity percentage',
            description: 'Share of electricity from renewables in total electricity consumption',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'renewableHeatingInPercent',
            label: 'Renewable heating percentage',
            description: 'Share of heating from renewables in total heat supply',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'electricGasPoweredMachineryVehicleInPercent',
            label: 'Electric/gas-powered machinery/vehicle percentage',
            description: 'Share of electric/gas-powered machines/vehicles in total machinery/vehicle fleet',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
    ],
  },
  {
    name: 'cement',
    label: 'Cement',
    color: 'green',
    showIf: (dataModel: PathwaysToParisData): boolean =>
      dataModel.general?.general?.sectors.some((p2pSector) => p2pSector === P2pSector.Cement) ?? false,
    subcategories: [
      {
        name: 'energy',
        label: 'Energy',
        fields: [
          {
            name: 'energyMixInPercent',
            label: 'Energy mix',
            description: 'Share of renewable energy in total electricity consumption',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'fuelMixInPercent',
            label: 'Fuel mix',
            description: 'Share of biogenic fuels in the total mix',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'thermalEnergyEfficiencyInPercent',
            label: 'Thermal energy efficiency',
            description: 'Heat recovery rate in the process of clinker production',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'compositionOfThermalInputInPercent',
            label: 'Composition of thermal input',
            description: 'Share of (green) hydrogen in thermal input',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'technology',
        label: 'Technology',
        fields: [
          {
            name: 'carbonCaptureAndUseTechnologyUsage',
            label: 'Carbon capture and use technology usage',
            description: '(Planned) use of carbon capture and use technologies (CCCS/CU)',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'electrificationOfProcessHeatInPercent',
            label: 'Electrification of process heat',
            description: 'Degree of electrification of production and processes',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
        ],
      },
      {
        name: 'material',
        label: 'Material',
        fields: [
          {
            name: 'clinkerFactorReduction',
            label: 'Clinker factor reduction',
            description: 'Clinker/cement ratio',
            unit: '',
            component: 'NumberFormField',
            required: false,
            showIf: (): boolean => true,
          },
          {
            name: 'preCalcinedClayUsageInPercent',
            label: 'Pre-calcined clay usage',
            description: 'Share of pre-calcined clays in the material mix',
            unit: '%',
            component: 'PercentageFormField',
            required: false,
            showIf: (): boolean => true,
            validation: 'between:0,100',
          },
          {
            name: 'circularEconomyContribution',
            label: 'Circular economy contribution',
            description: 'Use of industrial by-products/co-products',
            unit: '',
            component: 'YesNoFormField',
            required: false,
            showIf: (): boolean => true,
          },
        ],
      },
    ],
  },
] as Array<Category>;
