dataland:
  qa-service:
    preapproval:
      exempt-fields:
        sfdr:
          - extendedIntegerCasesOfInsufficientActionAgainstBriberyAndCorruption
          - extendedEnumYesNoPrimaryForestAndWoodedLandOfNativeSpeciesExposure
          - extendedDecimalScope3UpstreamGhgEmissionsInTonnes
          - extendedDecimalScope3DownstreamGhgEmissionsInTonnes
          - extendedDecimalRateOfAccidents
          - extendedDecimalEmissionsOfAirPollutantsInTonnes
          - extendedEnumYesNoLandDegradationDesertificationSoilSealingExposure
          - extendedDecimalWaterConsumptionInCubicMeters
          - extendedDecimalEmissionsOfInorganicPollutantsInTonnes
          - extendedDecimalWorkdaysLostInDays
          - extendedEnumYesNoThreatenedSpeciesExposure
          - extendedEnumYesNoUnGlobalCompactPrinciplesCompliancePolicy
          - extendedEnumYesNoProtectedAreasExposure
          - extendedDecimalEmissionsToWaterInTonnes
          - extendedEnumYesNoFossilFuelSectorExposure
          - extendedEnumYesNoViolationOfTaxRulesAndRegulation
          - extendedEnumYesNoGrievanceHandlingMechanism
          - extendedCurrencyTotalAmountOfReportedFinesOfBriberyAndCorruption
          - extendedEnumYesNoIloCoreLabourStandards
          - extendedEnumYesNoControversialWeaponsExposure
          - extendedDecimalEmissionsOfOzoneDepletionSubstancesInTonnes
          - extendedEnumYesNoHumanRightsLegalProceedings
          - extendedEnumYesNoManufactureOfAgrochemicalPesticidesProducts
          - extendedIntegerNumberOfReportedIncidentsOfHumanRightsViolations
          - extendedEnumYesNoRareOrEndangeredEcosystemsExposure
          - extendedEnumYesNoSupplierCodeOfConduct
          - extendedEnumYesNoBiodiversityProtectionPolicy
          - extendedEnumYesNoHumanRightsDueDiligencePolicy
          - extendedEnumYesNoOecdGuidelinesForMultinationalEnterprisesGrievanceHandling
          - extendedDecimalTotalRevenueInEUR
          - extendedDecimalRenewableEnergyProductionInGWh
          - extendedIntegerMaleBoardMembersBoardOfDirectors
          - extendedDecimalUnadjustedGenderPayGapInPercent
          - extendedIntegerFemaleBoardMembersSupervisoryBoard
          - extendedIntegerMaleBoardMembersSupervisoryBoard
          - extendedDecimalNonRenewableEnergyConsumptionInGWh
          - extendedIntegerFemaleBoardMembersBoardOfDirectors
          - extendedDecimalHazardousAndRadioactiveWasteInTonnes
          - extendedDecimalTotalHighImpactClimateSectorEnergyConsumptionInGWh


