describe('Login Section', () => {
    it('Check if App is present', () => {
        cy.visit("/")
        cy.get('#app').should('exist')
    })
    it('Logo and welcome message are present', () => {
        cy.get('h1').should("contain.text","CREATE A DATASET")
        cy.get('img[alt="Dataland logo"]')
            .should('be.visible')
            .should('have.attr', 'src')
            .should('include','vision')
    })
    it('Login and Join buttons are present', () => {
        cy.get('button[name=join_dataland_button]')
            .should('be.visible')
            .should("contain.text","Join")
        cy.get('button[name="join_dataland_button"]').click()
        cy.get('h1').should("contain.text","Search EU Taxonomy data")
        cy.visit("/")
        cy.get('button[name=login_dataland_button]')
            .should('be.visible')
            .should("contain.text","Login")
        cy.get('button[name="login_dataland_button"]').click()
        cy.get('h1').should("contain.text","Search EU Taxonomy data")
        cy.visit("/")
    })
    it('Company logos are present', () => {
        cy.get('img[alt="pwc"]')
            .should('be.visible')
            .should('have.attr', 'src')
        cy.get('img[alt="d-fine GmbH"]')
            .should('be.visible')
            .should('have.attr', 'src')
    })
    it('Register text and button are present', () => {
        cy.get('h2').should("contain.text","Join Dataland")
        cy.get('button[name=get_started_button]')
            .should('be.visible')
            .should("contain.text","Get Started")
        cy.get('input[name=email_input_landing]').type("Mustermann@muster.de", {force: true})
            .should('have.value', "Mustermann@muster.de")
    })

})
describe('Sample Section', () => {
    it('Check that the sample section works properly', () => {
        cy.visit("/")
        cy.get('h2').should("contain.text","Explore Dataland")
        cy.get('button[name=eu_taxonomy_sample_button]')
            .should('be.visible')
            .should("contain.text","EU Taxonomy")
            .click({force:true})
            .url().should('include', '/taxonomysample')
        cy.get('h2').contains('EU Taxonomy Data')
        cy.get('.p-button.p-button-rounded')
            .should("contain.text","COMPANY DATA SAMPLE")
        cy.get('body').should('contain.text', 'Join Dataland with other')
        cy.get('[title=back_button').should('be.visible').click({force:true})
        cy.get('h1').should("contain.text","CREATE A DATASET")
    })
})

describe('Marketing Section', () => {
    it('Checks that the marketing section works properly', () => {
        cy.visit("/")
        cy.get("h2").should("contain.text", "Learn about our vision")
        cy.get('img[alt="Showcase Video"]')
            .should('be.visible')
            .should('have.attr', 'src')
        cy.get('img[alt="Flow Diagramm"]')
            .should('be.visible')
            .should('have.attr', 'src')
        cy.get('h3').contains('Bring together who')
        cy.get('img[alt="Data Workflow"]')
            .should('be.visible')
            .should('have.attr', 'src')
        cy.get('h3').contains('Maximize data coverage')
    })

})

describe('Footer Section', () => {
    it('Checks that the footer section works properly', () => {
        cy.visit("/")
        cy.get('img[alt="Dataland logo"]')
            .should('be.visible')
            .should('have.attr', 'src')
            .should('include','vision')
    })
})