// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.soziales.einbindungDerBeschaeftigten

import java.util.EnumSet

/**
 * The data-model for the EinbindungDerBeschaeftigten section
 */
data class EsgDatenkatalogSozialesEinbindungDerBeschaeftigten(
    val einbindungVonBeschaeftigtenInEntscheidungen:
        EsgDatenkatalogSozialesEinbindungderbeschaeftigtenEinbindungVonBeschaeftigtenInEntscheidungenOptions? = null,
    val einbindungVonBeschaeftigtenInGremien: EnumSet<EinbindungVonBeschaeftigtenInGremienOptions>? = null,
    val einbindungVonBeschaeftigtenLaenderspezifischeErlaeuterungen: String? = null,
)
