// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.heimathafen.model.sdg

import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.bezahlbareUndSaubereEnergie.HeimathafenSdgBezahlbareUndSaubereEnergie
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.friedenGerechtigkeitUndStarkeInstitutionen.HeimathafenSdgFriedenGerechtigkeitUndStarkeInstitutionen
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.geschlechtergleichheit.HeimathafenSdgGeschlechtergleichheit
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.gesundheitUndWohlergehen.HeimathafenSdgGesundheitUndWohlergehen
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.hochwertigeBildung.HeimathafenSdgHochwertigeBildung
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.industrieInnovationUndInfrastruktur.HeimathafenSdgIndustrieInnovationUndInfrastruktur
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.keinHunger.HeimathafenSdgKeinHunger
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.keineArmut.HeimathafenSdgKeineArmut
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.lebenAnLand.HeimathafenSdgLebenAnLand
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.lebenUnterWasser.HeimathafenSdgLebenUnterWasser
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.massnahmenZumKlimaschutz.HeimathafenSdgMassnahmenZumKlimaschutz
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.menschenwuerdigeArbeitUndWirtschaftswachstum.HeimathafenSdgMenschenwuerdigeArbeitUndWirtschaftswachstum
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.nachhaligerKonsumUndProduktion.HeimathafenSdgNachhaligerKonsumUndProduktion
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.nachhaltigeStaedteUndGemeinden.HeimathafenSdgNachhaltigeStaedteUndGemeinden
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.partnerschaftenZurErreichungDerZiele.HeimathafenSdgPartnerschaftenZurErreichungDerZiele
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.sauberesWasserUndSanitaereEinrichtungen.HeimathafenSdgSauberesWasserUndSanitaereEinrichtungen
import org.dataland.datalandbackend.frameworks.heimathafen.model.sdg.wenigerUngleichheiten.HeimathafenSdgWenigerUngleichheiten

/**
 * The data-model for the Sdg section
 */
data class HeimathafenSdg(
    val keineArmut: HeimathafenSdgKeineArmut? = null,
    val keinHunger: HeimathafenSdgKeinHunger? = null,
    val gesundheitUndWohlergehen: HeimathafenSdgGesundheitUndWohlergehen? = null,
    val hochwertigeBildung: HeimathafenSdgHochwertigeBildung? = null,
    val geschlechtergleichheit: HeimathafenSdgGeschlechtergleichheit? = null,
    val sauberesWasserUndSanitaereEinrichtungen: HeimathafenSdgSauberesWasserUndSanitaereEinrichtungen? = null,
    val bezahlbareUndSaubereEnergie: HeimathafenSdgBezahlbareUndSaubereEnergie? = null,
    val menschenwuerdigeArbeitUndWirtschaftswachstum:
    HeimathafenSdgMenschenwuerdigeArbeitUndWirtschaftswachstum? = null,
    val industrieInnovationUndInfrastruktur: HeimathafenSdgIndustrieInnovationUndInfrastruktur? = null,
    val wenigerUngleichheiten: HeimathafenSdgWenigerUngleichheiten? = null,
    val nachhaltigeStaedteUndGemeinden: HeimathafenSdgNachhaltigeStaedteUndGemeinden? = null,
    val nachhaligerKonsumUndProduktion: HeimathafenSdgNachhaligerKonsumUndProduktion? = null,
    val massnahmenZumKlimaschutz: HeimathafenSdgMassnahmenZumKlimaschutz? = null,
    val lebenUnterWasser: HeimathafenSdgLebenUnterWasser? = null,
    val lebenAnLand: HeimathafenSdgLebenAnLand? = null,
    val friedenGerechtigkeitUndStarkeInstitutionen: HeimathafenSdgFriedenGerechtigkeitUndStarkeInstitutionen? = null,
    val partnerschaftenZurErreichungDerZiele: HeimathafenSdgPartnerschaftenZurErreichungDerZiele? = null,
)
