// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.investmentFirms.otherServicesTurnoverBased

import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.CurrencyDataPoint
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import org.dataland.datalandbackend.validator.MinimumValue
import java.math.BigDecimal

/**
 * The data-model for the OtherServicesTurnoverBased section
 */
@Suppress("MaxLineLength")
data class EutaxonomyFinancialsInvestmentfirmsOtherServicesTurnoverBased(
    @field:MinimumValue(minimumValue = 0)
    @field:Valid()
    val turnoverBasedTotalRevenueFromInvestmentsAndServicesAndActivitiesOtherThanDealingOnOwnAccount:
    CurrencyDataPoint? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToClimateChangeMitigationEligible:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToClimateChangeMitigationAligned:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToClimateChangeMitigationOfWhichTransitional:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToClimateChangeMitigationOfWhichEnabling:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToClimateChangeAdaptationEligible:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToClimateChangeAdaptationAligned:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToClimateChangeAdaptationOfWhichEnabling:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToSustainableUseAndProtectionOfWaterAndMarineResourcesEligible:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToSustainableUseAndProtectionOfWaterAndMarineResourcesAligned:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToSustainableUseAndProtectionOfWaterAndMarineResourcesOfWhichEnabling:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToCircularEconomyEligible:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToCircularEconomyAligned:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToCircularEconomyOfWhichEnabling:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToPollutionPreventionAndControlEligible:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToPollutionPreventionAndControlAligned:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToPollutionPreventionAndControlOfWhichEnabling:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToProtectionAndRestorationOfBiodiversityAndEcosystemsEligible:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToProtectionAndRestorationOfBiodiversityAndEcosystemsAligned:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToProtectionAndRestorationOfBiodiversityAndEcosystemsOfWhichEnabling:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToAnyOfTheSixEnvironmentalObjectivesEligible:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToAnyOfTheSixEnvironmentalObjectivesAligned:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToAnyOfTheSixEnvironmentalObjectivesOfWhichTransitional:
    ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val turnoverBasedProportionOfRevenueSubstantiallyContributingToAnyOfTheSixEnvironmentalObjectivesOfWhichEnabling:
    ExtendedDataPoint<BigDecimal?>? = null,

)
