// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.heimathafen.model.environmental.nachhaltigskeitsrisiken

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.BaseDataPoint
import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the Nachhaltigskeitsrisiken section
 */
@Suppress("MaxLineLength")
data class HeimathafenEnvironmentalNachhaltigskeitsrisiken(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Werden Nachhaltigkeitsrisiken bezogen auf den Bereich Umwelt in der Methodik abgebildet?
Nachhaltigkeitsrisiken können einen wesentlichen negativen Einfluss auf die Performance eines Unternehmens haben.""",
        example = """ "Yes"  """,
    )
    val methodikFuerOekologischeNachhaltigkeitsrisiken: YesNo? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """null""",
        example = """ "This is some free text"  """,
    )
    val wennNeinBitteBegruenden: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Nachhaltigkeitsrisiken im Bereich Umwelt werden abgebildet?
Aufführung der Nachhaltigkeitsrisiken, die abgebildet werden können. (z.B. Klimarisiken, Risiken bzgl. Biodiversität, Risiken bzgl. Wasser)""",
        example = """ "This is some free text"  """,
    )
    val kartierteRisikenFuerDieOekologischeNachhaltigkeit: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Wie werden wesentliche Nachhaltigkeitsrisiken eines Unternehmens im Bereich Umwelt identifiziert und in der Methodik berücksichtigt?
Angaben zur Wesentlichkeitsanalyse bei der Einstufung der Wesentlichkeit eines Risikos bezogen auf ein Unternehmen. Sowie Angaben dazu, wie sich die unterschiedliche Risikoeinstufung in der Methodik widerspiegelt.""",
        example = """ "This is some free text"  """,
    )
    val identifizierungDerWesentlichenRisikenFuerDieOekologischeNachhaltigkeitUndDerKonstruktionsmethodik: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Wie werden Nachhaltigkeitsrisiken in der Bewertung bezogen auf den Bereich Umwelt berücksichtigt?
Angaben dazu, ob Nachhaltigkeitsrisiken aus dem Bereich Umwelt in die Erstellung des Ratings miteinbezogen werden und wenn ja wie.""",
        example = """ "This is some free text"  """,
    )
    val umweltbewertungUnterBeruecksichtigungVonNachhaltigkeitsrisiken: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Wie wird die Überwachung von Nachhaltigkeitsrisiken im Bereich Umwelt sichergestellt?""",
        example = """ "This is some free text"  """,
    )
    val risikenFuerDieOekologischeNachhaltigkeitAbsichern: String? = null,
    @field:Valid()
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Quellen werden für die Erfassung von Nachhaltigkeitsrisiken im Bereich Umwelt verwendet?
Angabe von Quellen, zum Beispiel Geschäftsberichte von Unternehmen, Daten von NGOs etc.""",
        example = """[
						{
							"value": "lifetime value",
							"dataSource": {
								"fileName": "Certification",
								"fileReference": "1902e40099c913ecf3715388cb2d9f7f84e6f02a19563db6930adb7b6cf22868"
							}
						},
						{
							"value": "technologies",
							"dataSource": {
								"fileName": "Policy",
								"fileReference": "04c4e6cd07eeae270635dd909f58b09b2104ea5e92ec22a80b6e7ba1d0b75dd0"
							}
						}
					] """,
    )
    val quellen: List<BaseDataPoint<String>>? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Ist eine Vier-Augen-Verifizierung vorhanden?""",
        example = """ "Yes"  """,
    )
    val vierAugenPruefung: YesNo? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """null""",
        example = """ "This is some free text"  """,
    )
    val wennKeineVierAugenPruefungBitteBegruenden: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Wie erfolgt die Vier-Augen-Verifizierung?""",
        example = """ "This is some free text"  """,
    )
    val beschreibungDerVierAugenPruefung: String? = null,
)
