// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgquestionnaire.model.umwelt.fossileBrennstoffe

import org.dataland.datalandbackend.frameworks.esgquestionnaire.custom.YearlyTimeseriesData
import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the FossileBrennstoffe section
 */
data class EsgQuestionnaireUmweltFossileBrennstoffe(
    val einnahmenAusFossilenBrennstoffen: YesNo? = null,
    val berichterstattungEinnahmenAusFossilenBrennstoffen:
        YearlyTimeseriesData<BerichterstattungEinnahmenAusFossilenBrennstoffenValues?>? = null,
)
