// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type AxiosPromise, type AxiosRequestConfig, type AxiosInstance } from 'axios';
import { type CompanyAssociatedData } from '@/api-models/CompanyAssociatedData';
import {
  IntegrationtestingDataControllerApi,
  type IntegrationtestingData,
  type Configuration,
  type DataMetaInformation,
  type ExportFileType,
  type ExportJobInfo,
} from '@clients/backend';
import { type PublicFrameworkDataApi } from '@/utils/api/UnifiedFrameworkDataApi';
import { type DataAndMetaInformation } from '@/api-models/DataAndMetaInformation';

export class IntegrationtestingApiClient implements PublicFrameworkDataApi<IntegrationtestingData> {
  private readonly openApiDataController: IntegrationtestingDataControllerApi;

  constructor(configuration: Configuration | undefined, axiosInstance: AxiosInstance | undefined) {
    this.openApiDataController = new IntegrationtestingDataControllerApi(configuration, undefined, axiosInstance);
  }

  getAllCompanyData(
    companyId: string,
    showOnlyActive?: boolean,
    reportingPeriod?: string,
    options?: AxiosRequestConfig
  ): AxiosPromise<DataAndMetaInformation<IntegrationtestingData>[]> {
    return this.openApiDataController.getAllCompanyIntegrationtestingData(
      companyId,
      showOnlyActive,
      reportingPeriod,
      options
    );
  }

  getFrameworkData(
    dataId: string,
    options?: AxiosRequestConfig
  ): AxiosPromise<CompanyAssociatedData<IntegrationtestingData>> {
    return this.openApiDataController.getCompanyAssociatedIntegrationtestingData(dataId, options);
  }

  postFrameworkData(
    data: CompanyAssociatedData<IntegrationtestingData>,
    bypassQa?: boolean,
    options?: AxiosRequestConfig
  ): AxiosPromise<DataMetaInformation> {
    return this.openApiDataController.postCompanyAssociatedIntegrationtestingData(data, bypassQa, options);
  }

  postExportJobCompanyAssociatedDataByDimensions(
    reportingPeriods: string[],
    companyIds: string[],
    fileFormat: ExportFileType,
    keepValueFieldsOnly?: boolean,
    includeAliases?: boolean,
    options?: AxiosRequestConfig
  ): AxiosPromise<ExportJobInfo> {
    return this.openApiDataController.postExportJobCompanyAssociatedIntegrationtestingDataByDimensions(
      { reportingPeriods, companyIds, fileFormat },
      keepValueFieldsOnly,
      includeAliases,
      options
    );
  }

  postExportLatestJobCompanyAssociatedDataByDimensions(
    companyIds: string[],
    fileFormat: ExportFileType,
    keepValueFieldsOnly?: boolean,
    includeAliases?: boolean,
    options?: AxiosRequestConfig
  ): AxiosPromise<ExportJobInfo> {
    return this.openApiDataController.postExportLatestJobCompanyAssociatedIntegrationtestingDataByDimensions(
      { companyIds, fileFormat },
      keepValueFieldsOnly,
      includeAliases,
      options
    );
  }

  getCompanyAssociatedDataByDimensions(
    reportingPeriod: string,
    companyId: string,
    options?: AxiosRequestConfig
  ): AxiosPromise<CompanyAssociatedData<IntegrationtestingData>> {
    return this.openApiDataController.getCompanyAssociatedIntegrationtestingDataByDimensions(
      reportingPeriod,
      companyId,
      options
    );
  }
}
