// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type BasePublicFrameworkDefinition } from '@/frameworks/BasePublicFrameworkDefinition';
import { type Configuration, type IntegrationtestingData } from '@clients/backend';
import { type AxiosInstance } from 'axios';
import { type PublicFrameworkDataApi } from '@/utils/api/UnifiedFrameworkDataApi';
import { IntegrationtestingApiClient } from '@/frameworks/integrationTesting/ApiClient';

export class BaseIntegrationtestingFrameworkDefinition
  implements BasePublicFrameworkDefinition<IntegrationtestingData>
{
  readonly identifier = 'integrationTesting';
  readonly explanation = 'This framework is used for testing the framework-toolbox';
  readonly label = 'Integration Testing';
  getPublicFrameworkApiClient(
    configuration?: Configuration,
    axiosInstance?: AxiosInstance
  ): PublicFrameworkDataApi<IntegrationtestingData> {
    return new IntegrationtestingApiClient(configuration, axiosInstance);
  }
}

export default new BaseIntegrationtestingFrameworkDefinition();
