// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
import { type BaseFrameworkDefinition } from "@/frameworks/FrameworkDefinition";
import { type Configuration, type EutaxonomynonfinancialsData } from "@clients/backend";
import { type AxiosInstance } from "axios";
import { type FrameworkDataApi } from "@/utils/api/UnifiedFrameworkDataApi";
import { EutaxonomynonfinancialsApiClient } from "@/frameworks/euTaxonomyNonFinancials/ApiClient";

export class BaseEutaxonomynonfinancialsFrameworkDefinition
  implements BaseFrameworkDefinition<EutaxonomynonfinancialsData>
{
  readonly identifier = "euTaxonomyNonFinancials";
  readonly explanation = "Das Eu Taxonomy Non-Financials Framework";
  readonly label = "EU Taxonomy Non-Financials";
  getFrameworkApiClient(
    configuration?: Configuration,
    axiosInstance?: AxiosInstance,
  ): FrameworkDataApi<EutaxonomynonfinancialsData> {
    return new EutaxonomynonfinancialsApiClient(configuration, axiosInstance);
  }
}

export default new BaseEutaxonomynonfinancialsFrameworkDefinition();
