// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.heimathafen.model.governance.goodGovernanceUngc

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.BaseDataPoint
import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the GoodGovernanceUngc section
 */
@Suppress("MaxLineLength")
data class HeimathafenGovernanceGoodGovernanceUngc(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Werden die UNGC in der Analyse berücksichtigt?""",
        example = """ "Yes"  """,
    )
    val beruecksichtigungDesUngc: YesNo? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """null""",
        example = """ "This is some free text"  """,
    )
    val wennNeinBitteBegruenden: String? = null,
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Wie erfolgt die Berücksichtigung der UNGC?
Wenn eine Berücksichtigung der UNGC erfolgt Angaben darüber, wie die Berücksichtigung abgebildet wird.""",
        example = """ "This is some free text"  """,
    )
    val beruecksichtigungDerUngcBeschreibung: String? = null,
    @field:Valid()
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Welche Quellen werden verwendet?
Angabe von Quellen, zum Beispiel UNGC, Nachhaltigkeitsberichte""",
        example = """[
      {
        "value": "lifetime value",
        "dataSource": {
          "fileName": "Certification",
          "fileReference": "1902e40099c913ecf3715388cb2d9f7f84e6f02a19563db6930adb7b6cf22868"
        }
      },
      {
        "value": "technologies",
        "dataSource": {
          "fileName": "Policy",
          "fileReference": "04c4e6cd07eeae270635dd909f58b09b2104ea5e92ec22a80b6e7ba1d0b75dd0"
        }
      }
    ] """,
    )
    val verwendeteQuellen: List<BaseDataPoint<String>>? = null,
)
