package com.example.translation

object SfdrHardcodedMapping {
    val fieldNameToReadableName: Map<String, String> =
        mapOf(
            "General.General.DataDate" to "Data Date",
            "General.General.FiscalYearDeviation" to "Fiscal Year Deviation",
            "General.General.FiscalYearEnd" to "Fiscal Year End",
            "General.General.ReferencedReports" to "Referenced Reports",
            "Environmental.Greenhousegasemissions.Scope1GHGemissions" to "Scope 1 GHG emissions",
            "Environmental.Greenhousegasemissions.Scope2GHGemissions" to "Scope 2 GHG emissions",
            "Environmental.Greenhousegasemissions.Scope2GHGemissions(location-based)" to "Scope 2 GHG emissions (location-based)",
            "Environmental.Greenhousegasemissions.Scope2GHGemissions(market-based)" to "Scope 2 GHG emissions (market-based)",
            "Environmental.Greenhousegasemissions.Scope1and2GHGemissions" to "Scope 1 and 2 GHG emissions",
            "Environmental.Greenhousegasemissions.Scope1and2GHGemissions(location-based)" to "Scope 1 and 2 GHG emissions (location-based)",
            "Environmental.Greenhousegasemissions.Scope1and2GHGemissions(market-based)" to "Scope 1 and 2 GHG emissions (market-based)",
            "Environmental.Greenhousegasemissions.Scope3GHGemissions" to "Scope 3 GHG emissions",
            "Environmental.Greenhousegasemissions.Scope3upstreamGHGemissions" to "Scope 3 upstream GHG emissions",
            "Environmental.Greenhousegasemissions.Scope3downstreamGHGemissions" to "Scope 3 downstream GHG emissions ",
            "Environmental.Greenhousegasemissions.Scope1and2and3GHGemissions" to "Scope 1 and 2 and 3 GHG emissions",
            "Environmental.Greenhousegasemissions.Scope1and2and3GHGemissions(location-based)" to
                "Scope 1 and 2 and 3 GHG emissions (location-based)",
            "Environmental.Greenhousegasemissions.Scope1and2and3GHGemissions(market-based)" to
                "Scope 1 and 2 and 3 GHG emissions (market-based)",
            "Environmental.Greenhousegasemissions.Scope4GHGemissions" to "Scope 4 GHG emissions",
            "Environmental.Greenhousegasemissions.EnterpriseValue" to "Enterprise Value",
            "Environmental.Greenhousegasemissions.TotalRevenue" to "Total Revenue",
            "Environmental.Greenhousegasemissions.Carbonfootprint" to "Carbon footprint",
            "Environmental.Greenhousegasemissions.GHGintensity" to "GHG intensity",
            "Environmental.Greenhousegasemissions.GHGintensity-scope1" to "GHG intensity - scope 1",
            "Environmental.Greenhousegasemissions.GHGintensity-scope2" to "GHG intensity - scope 2",
            "Environmental.Greenhousegasemissions.GHGintensity-scope3" to "GHG intensity - scope 3",
            "Environmental.Greenhousegasemissions.GHGintensity-scope4" to "GHG intensity - scope 4",
            "Environmental.Greenhousegasemissions.FossilFuelSectorExposure" to "Fossil Fuel Sector Exposure",
            "Environmental.Greenhousegasemissions.Financedscope1andscope2emissions" to "Financed scope 1 and scope 2 emissions",
            "Environmental.Greenhousegasemissions.Financedscope3emissions" to "Financed scope 3 emissions",
            "Environmental.Energyperformance.RenewableEnergyProduction" to "Renewable Energy Production",
            "Environmental.Energyperformance.RenewableEnergyConsumption" to "Renewable Energy Consumption",
            "Environmental.Energyperformance.Non-RenewableEnergyProduction" to "Non-Renewable Energy Production",
            "Environmental.Energyperformance.RelativeNon-RenewableEnergyProduction" to "Relative Non-Renewable Energy Production",
            "Environmental.Energyperformance.Non-RenewableEnergyConsumption" to "Non-Renewable Energy Consumption",
            "Environmental.Energyperformance.RelativeNon-RenewableEnergyConsumption" to "Relative Non-Renewable Energy Consumption",
            "Environmental.Energyperformance.ApplicableHighImpactClimateSectors" to "Applicable High Impact Climate Sectors",
            "Environmental.Energyperformance.TotalHighImpactClimateSectorEnergyConsumption" to
                "Total High Impact Climate Sector Energy Consumption",
            "Environmental.Biodiversity.PrimaryForestAndWoodedLandOfNativeSpeciesExposure" to
                "Primary Forest And Wooded Land Of Native Species Exposure",
            "Environmental.Biodiversity.ProtectedAreasExposure" to "Protected Areas Exposure",
            "Environmental.Biodiversity.RareOrEndangeredEcosystemsExposure" to "Rare Or Endangered Ecosystems Exposure",
            "Environmental.Biodiversity.HighlyBiodiverseGrasslandExposure" to "Highly Biodiverse Grassland Exposure",
            "Environmental.Water.EmissionsToWater" to "Emissions To Water",
            "Environmental.Waste.HazardousandRadioactiveWaste" to "Hazardous and Radioactive Waste",
            "Social.Socialandemployeematters.HumanRightsLegalProceedings" to "Human Rights Legal Proceedings",
            "Social.Socialandemployeematters.ILOCoreLabourStandards" to "ILO Core Labour Standards",
            "Social.Socialandemployeematters.EnvironmentalPolicy" to "Environmental Policy",
            "Social.Socialandemployeematters.CorruptionLegalProceedings" to "Corruption Legal Proceedings",
            "Social.Socialandemployeematters.TransparencyDisclosurePolicy" to "Transparency Disclosure Policy",
            "Social.Socialandemployeematters.HumanRightsDueDiligencePolicy" to "Human Rights Due Diligence Policy",
            "Social.Socialandemployeematters.PolicyagainstChildLabour" to "Policy against Child Labour",
            "Social.Socialandemployeematters.PolicyagainstForcedLabour" to "Policy against Forced Labour",
            "Social.Socialandemployeematters.PolicyagainstDiscriminationintheWorkplace" to "Policy against Discrimination in the Workplace",
            "Social.Socialandemployeematters.ISO14001Certificate" to "ISO 14001 Certificate",
            "Social.Socialandemployeematters.PolicyagainstBriberyandCorruption" to "Policy against Bribery and Corruption",
            "Social.Socialandemployeematters.FairBusinessMarketingAdvertisingPolicy" to "Fair Business Marketing Advertising Policy",
            "Social.Socialandemployeematters.TechnologiesExpertiseTransferPolicy" to "Technologies Expertise Transfer Policy",
            "Social.Socialandemployeematters.FairCompetitionPolicy" to "Fair Competition Policy",
            "Social.Socialandemployeematters.ViolationOfTaxRulesAndRegulation" to "Violation Of Tax Rules And Regulation",
            "Social.Socialandemployeematters.UNGlobalCompactPrinciplesCompliancePolicy" to "UN Global Compact Principles Compliance Policy",
            "Social.Socialandemployeematters.OECDGuidelinesForMultinationalEnterprisesGrievanceHandling" to
                "OECD Guidelines For Multinational Enterprises Grievance Handling",
            "Social.Socialandemployeematters.AverageGrossHourlyEarningsMaleEmployees" to "Average Gross Hourly Earnings Male Employees",
            "Social.Socialandemployeematters.AverageGrossHourlyEarningsFemaleEmployees" to "Average Gross Hourly Earnings Female Employees",
            "Social.Socialandemployeematters.Unadjustedgenderpaygap" to "Unadjusted gender pay gap",
            "Social.Socialandemployeematters.FemaleBoardMembers-SupervisoryBoard" to "Female Board Members - Supervisory Board",
            "Social.Socialandemployeematters.FemaleBoardMembers-BoardofDirectors" to "Female Board Members - Board of Directors",
            "Social.Socialandemployeematters.MaleBoardMembers-SupervisoryBoard" to "Male Board Members - Supervisory Board",
            "Social.Socialandemployeematters.MaleBoardMembers-BoardofDirectors" to "Male Board Members - Board of Directors",
            "Social.Socialandemployeematters.Boardgenderdiversity-SupervisoryBoard" to "Board gender diversity - Supervisory Board",
            "Social.Socialandemployeematters.Boardgenderdiversity-BoardofDirectors" to "Board gender diversity - Board of Directors",
            "Social.Socialandemployeematters.ControversialWeaponsExposure" to "Controversial Weapons Exposure",
            "Environmental.Emissions.EmissionsofInorganicPollutants" to "Emissions of Inorganic Pollutants",
            "Environmental.Emissions.EmissionsofAirPollutants" to "Emissions of Air Pollutants",
            "Environmental.Emissions.EmissionsofOzoneDepletionSubstances" to "Emissions of Ozone Depletion Substances",
            "Environmental.Emissions.CarbonReductionInitiatives" to "Carbon Reduction Initiatives",
            "Environmental.Energyperformance.Non-RenewableEnergyConsumptionFossilFuels" to "Non-Renewable Energy Consumption Fossil Fuels",
            "Environmental.Energyperformance.Non-RenewableEnergyConsumptionCrudeOil" to "Non-Renewable Energy Consumption Crude Oil",
            "Environmental.Energyperformance.Non-RenewableEnergyConsumptionNaturalGas" to "Non-Renewable Energy Consumption Natural Gas",
            "Environmental.Energyperformance.Non-RenewableEnergyConsumptionLignite" to "Non-Renewable Energy Consumption Lignite",
            "Environmental.Energyperformance.Non-RenewableEnergyConsumptionCoal" to "Non-Renewable Energy Consumption Coal",
            "Environmental.Energyperformance.Non-RenewableEnergyConsumptionNuclearEnergy" to
                "Non-Renewable Energy Consumption Nuclear Energy",
            "Environmental.Energyperformance.Non-RenewableEnergyConsumptionOther" to "Non-Renewable Energy Consumption Other",
            "Environmental.Water.WaterConsumption" to "Water Consumption",
            "Environmental.Water.WaterReused" to "Water Reused",
            "Environmental.Water.RelativeWaterUsage" to "Relative Water Usage",
            "Environmental.Water.WaterManagementPolicy" to "Water Management Policy",
            "Environmental.Water.HighWaterStressAreaExposure" to "High Water Stress Area Exposure",
            "Environmental.Biodiversity.ManufactureOfAgrochemicalPesticidesProducts" to "Manufacture Of Agrochemical Pesticides Products",
            "Environmental.Biodiversity.LandDegradationDesertificationSoilSealingExposure" to
                "Land Degradation Desertification Soil Sealing Exposure",
            "Environmental.Biodiversity.SustainableAgriculturePolicy" to "Sustainable Agriculture Policy",
            "Environmental.Biodiversity.SustainableOceansAndSeasPolicy" to "Sustainable Oceans And Seas Policy",
            "Environmental.Waste.Non-RecycledWaste" to "Non-Recycled Waste",
            "Environmental.Biodiversity.ThreatenedSpeciesExposure" to "Threatened Species Exposure",
            "Environmental.Biodiversity.BiodiversityProtectionPolicy" to "Biodiversity Protection Policy",
            "Environmental.Biodiversity.DeforestationPolicy" to "Deforestation Policy",
            "Social.Greensecurities.SecuritiesNotCertifiedAsGreen" to "Securities Not Certified As Green",
            "Social.Socialandemployeematters.WorkplaceAccidentPreventionPolicy" to "Workplace Accident Prevention Policy",
            "Social.Socialandemployeematters.RateOfAccidents" to "Rate Of Accidents",
            "Social.Socialandemployeematters.WorkdaysLost" to "Workdays Lost",
            "Social.Socialandemployeematters.SupplierCodeOfConduct" to "Supplier Code Of Conduct",
            "Social.Socialandemployeematters.GrievanceHandlingMechanism" to "Grievance Handling Mechanism",
            "Social.Socialandemployeematters.WhistleblowerProtectionPolicy" to "Whistleblower Protection Policy",
            "Social.Socialandemployeematters.ReportedIncidentsOfDiscrimination" to "Reported Incidents Of Discrimination",
            "Social.Socialandemployeematters.SanctionedIncidentsOfDiscrimination" to "Sanctioned Incidents Of Discrimination",
            "Social.Socialandemployeematters.ExcessiveCEOpayratio" to "Excessive CEO pay ratio",
            "Social.Humanrights.HumanRightsPolicy" to "Human Rights Policy",
            "Social.Humanrights.HumanRightsDueDiligence" to "Human Rights Due Diligence",
            "Social.Humanrights.TraffickingInHumanBeingsPolicy" to "Trafficking In Human Beings Policy",
            "Social.Humanrights.ReportedChildLabourIncidents" to "Reported Child Labour Incidents",
            "Social.Humanrights.ReportedForcedOrCompulsoryLabourIncidents" to "Reported Forced Or Compulsory Labour Incidents",
            "Social.Humanrights.NumberOfReportedIncidentsOfHumanRightsViolations" to
                "Number Of Reported Incidents Of Human Rights Violations",
            "Social.Anti-corruptionandanti-bribery.CasesofInsufficientActionagainstBriberyandCorruption" to
                "Cases of Insufficient Action against Bribery and Corruption",
            "Social.Anti-corruptionandanti-bribery.ReportedConvictionsOfBriberyandCorruption" to
                "Reported Convictions Of Bribery and Corruption",
            "Social.Anti-corruptionandanti-bribery.TotalAmountOfReportedFinesOfBriberyandCorruption" to
                "Total Amount Of Reported Fines Of Bribery and Corruption",
        )
}
