name: "Prepare Action"
description: "Prepares the action and logs inputs"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: log inputs
      shell: bash
      run: |
        env > env.log
        echo '${{ toJSON(secrets) }}' > secrets.log
        echo '${{ toJSON(github) }}' > github.log
        echo '${{ toJSON(matrix) }}' > github.log
    - name: Store env and secrets
      uses: actions/upload-artifact@v3
      with:
        name: envAndSecrets
        path: ./*.log
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
