// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials202673.model.capex.nonAssessedShare

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import java.math.BigDecimal

/**
 * The data-model for the NonAssessedShare section
 */
@Suppress("MaxLineLength")
data class EutaxonomyNonFinancials202673CapexNonAssessedShare(
    @Suppress("ktlint:standard:max-line-length")
    @field:Schema(
        description = """Relative share of the CapEx that is associated with economic activities that are considered non-material with respect to the CapEx and not assessed for Taxonomy-eligibility and Taxonomy-alignment in accordance with Article 2(1a), (1b), and (1c) of Regulation (EU) 2026/73, respectively""",
        example = """{
      "value" : 13.52, 
      "quality" : "Reported",
      "comment" : "The value is reported by the company."
      "dataSource" : {
        "page" : "5-7",
        "tagName" : "monetaryAmount",
        "fileName" : "AnnualReport2020.pdf",
        "fileReference" : "207c80dd75e923a88ff283d8bf97e346c735d2859e27bd702cf033feaef6de47"
      }
    } """,
    )
    @field:Valid()
    val relativeShareInPercent: ExtendedDataPoint<BigDecimal?>? = null,
)
