// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.revenue

import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.revenue.revenue.EutaxonomyNonFinancialsRevenueRevenue

/**
 * The data-model for the Revenue section
 */
data class EutaxonomyNonFinancialsRevenue(
    @field:Valid()
    val revenue: EutaxonomyNonFinancialsRevenueRevenue? = null,

)
