// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.sfdr.model.environmental.energyPerformance

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.sfdr.custom.HighImpactClimateSector
import org.dataland.datalandbackend.frameworks.sfdr.custom.SfdrHighImpactClimateSectorEnergyConsumption
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import org.dataland.datalandbackend.utils.JsonExampleFormattingConstants
import java.math.BigDecimal

/**
 * The data-model for the EnergyPerformance section
 */
data class SfdrEnvironmentalEnergyPerformance(
    @field:Valid()
    val renewableEnergyProductionInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val renewableEnergyConsumptionInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyProductionInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val relativeNonRenewableEnergyProductionInPercent: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val relativeNonRenewableEnergyConsumptionInPercent: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Schema(example = JsonExampleFormattingConstants.HIGH_IMPACT_CLIMATE_SECTORS_DEFAULT_VALUE)
    val applicableHighImpactClimateSectors:
    Map<HighImpactClimateSector, SfdrHighImpactClimateSectorEnergyConsumption>? = null,

    @field:Valid()
    val totalHighImpactClimateSectorEnergyConsumptionInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionFossilFuelsInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionCrudeOilInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionNaturalGasInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionLigniteInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionCoalInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionNuclearEnergyInGWh: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionOtherInGWh: ExtendedDataPoint<BigDecimal?>? = null,

)
