// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.sfdr.model.environmental.energyPerformance

import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import java.math.BigDecimal

/**
 * The data-model for the EnergyPerformance section
 */
data class SfdrEnvironmentalEnergyPerformance(
    @field:Valid()
    val renewableEnergyProduction: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val renewableEnergyConsumption: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyProduction: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val relativeNonRenewableEnergyProduction: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumption: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val relativeNonRenewableEnergyConsumption: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val totalHighImpactClimateSectorEnergyConsumption: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionFossilFuels: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionCrudeOil: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionNaturalGas: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionLignite: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionCoal: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionNuclearEnergy: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val nonRenewableEnergyConsumptionOther: ExtendedDataPoint<BigDecimal?>? = null,

)
