// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.lksg.model.general.productionSpecific

import io.swagger.v3.oas.annotations.media.Schema

/**
 * Enum class for the multi-select-field specificProcurement
 */
@Schema(
    enumAsRef = true,
)
enum class SpecificProcurementOptions {
    ShortLivedAndChangingBusinessRelationships,
    HighPricePressure,
    TightlyTimedOrShortTermAdjustedDeliveryDeadlinesAndConditionsWithSuppliers,
    NoneOfTheAbove,
}
