// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.assetManagement

import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.assetManagement.capexBasedKpi
    .EuTaxonomyFinancialsAssetmanagementCapexBasedKpi
import org.dataland.datalandbackend.frameworks.eutaxonomyfinancials.model.assetManagement.turnoverBasedKpi
    .EuTaxonomyFinancialsAssetmanagementTurnoverBasedKpi

/**
 * The data-model for the AssetManagement section
 */
data class EuTaxonomyFinancialsAssetManagement(
    @field:Valid()
    val turnoverBasedKpi: EuTaxonomyFinancialsAssetmanagementTurnoverBasedKpi? = null,

    @field:Valid()
    val capexBasedKpi: EuTaxonomyFinancialsAssetmanagementCapexBasedKpi? = null,

)
