// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgdatenkatalog.model

import jakarta.validation.Valid
import org.dataland.datalandbackend.annotations.DataType
import org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.allgemein.EsgDatenkatalogAllgemein
import org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.general.EsgDatenkatalogGeneral
import org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.governance.EsgDatenkatalogGovernance
import org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.soziales.EsgDatenkatalogSoziales
import org.dataland.datalandbackend.frameworks.esgdatenkatalog.model.umwelt.EsgDatenkatalogUmwelt

/**
 * The root data-model for the Esg-datenkatalog Framework
 */
@Suppress("MagicNumber")
@DataType("esg-datenkatalog", 7)
data class EsgDatenkatalogData(
    @field:Valid()
    val general: EsgDatenkatalogGeneral,
    @field:Valid()
    val allgemein: EsgDatenkatalogAllgemein? = null,
    @field:Valid()
    val umwelt: EsgDatenkatalogUmwelt? = null,
    @field:Valid()
    val soziales: EsgDatenkatalogSoziales? = null,
    @field:Valid()
    val governance: EsgDatenkatalogGovernance? = null,
)
