// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.esgquestionnaire.model.allgemein.sonstige

import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the Sonstige section
 */
data class EsgQuestionnaireAllgemeinSonstige(
    val ausrichtungAufDieUnSdgsUndAktivesVerfolgen: String? = null,
    val ausschlusslistenAufBasisVonEsgKriterien: YesNo? = null,
    val ausschlusslisten: String? = null,
)
