// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.sfdr.model.environmental.waste

import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import java.math.BigDecimal
import org.dataland.datalandbackend.validator.MinimumValue
import jakarta.validation.Valid

/**
 * The data-model for the Waste section
 */
data class SfdrEnvironmentalWaste(
@field:MinimumValue(minimumValue = 0)
@field:Valid()
    val hazardousAndRadioactiveWasteInTonnes: ExtendedDataPoint<BigDecimal?>? = null,

@field:MinimumValue(minimumValue = 0)
@field:Valid()
    val nonRecycledWasteInTonnes: ExtendedDataPoint<BigDecimal?>? = null,

)
