// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.opex.alignedShare

import jakarta.validation.Valid
import org.dataland.datalandbackend.model.datapoints.CurrencyDataPoint
import org.dataland.datalandbackend.model.datapoints.ExtendedDataPoint
import java.math.BigDecimal

/**
 * The data-model for the AlignedShare section
 */
data class EutaxonomyNonFinancialsOpexAlignedShare(
    @field:Valid()
    val relativeShareInPercent: ExtendedDataPoint<BigDecimal?>? = null,

    @field:Valid()
    val absoluteShare: CurrencyDataPoint? = null,

)
