// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.opex.alignedShare

import java.math.BigDecimal

/**
 * The data-model for the AlignedShare section
 */
data class EutaxonomyNonFinancialsOpexAlignedShare(
    val relativeShareInPercent: BigDecimal? = null,

)
