name: CI
env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - '**'

jobs:
  log-everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/workflows/logObjects
        name: log everything
        with:
          task: "log-everything"
          github: ${{ toJSON(github) }}
          env: ${{ toJSON(env) }}
          job: ${{ toJSON(job) }}
          steps: ${{ toJSON(steps) }}
          runner: ${{ toJSON(runner) }}
          strategy: ${{ toJSON(strategy) }}
          matrix: ${{ toJSON(matrix) }}
          needs: ${{ toJSON(needs) }}
          inputs: ${{ toJSON(inputs) }}
          vars: ${{ toJSON(vars) }}
  rebuild-docker-images:
    uses: ./.github/workflows/RebuildDockerImages.yaml
  e2e-tests:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    needs:
      - rebuild-docker-images
    strategy:
      fail-fast: false
      matrix:
        run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/workflows/downloadImageVersions
      - uses: ./.github/workflows/logObjects
        name: log job contexts
        with:
          task: e2e-tests-cypress-1-run-${{ matrix.run }}
          env: ${{ toJSON(env) }}
          job: ${{ toJSON(job) }}
          steps: ${{ toJSON(steps) }}
          strategy: ${{ toJSON(strategy) }}
          matrix: ${{ toJSON(matrix) }}
          needs: ${{ toJSON(needs) }}
          inputs: ${{ toJSON(inputs) }}
          vars: ${{ toJSON(vars) }}
      - name: Retrieve SSL certificates for local-dev.dataland.com
        run: ./testing/retrieve_ssl_certs.sh
        env:
          TARGETSERVER_HOST_KEYS: ${{ vars.TARGETSERVER_HOST_KEYS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Execute E2E Tests
        run: ./testing/e2e_test_launcher.sh
        env:
          KEYCLOAK_FRONTEND_URL: "https://local-dev.dataland.com/keycloak"
          KEYCLOAK_DB_PASSWORD: "password"
          BACKEND_DB_PASSWORD: "password"
          API_KEY_MANAGER_DB_PASSWORD: "password"
          ACCOUNTING_SERVICE_DB_PASSWORD: "password"
          DATA_SOURCING_SERVICE_DB_PASSWORD: "password"
          INTERNAL_STORAGE_DB_PASSWORD: "password"
          DOCUMENT_MANAGER_DB_PASSWORD: "password"
          QA_SERVICE_DB_PASSWORD: "password"
          COMMUNITY_MANAGER_DB_PASSWORD: "password"
          EMAIL_SERVICE_DB_PASSWORD: "password"
          USER_SERVICE_DB_PASSWORD: "password"
          PGADMIN_PASSWORD: "password"
          KEYCLOAK_DATALAND_ADMIN_VALUE: "Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA=="
          KEYCLOAK_DATALAND_ADMIN_SALT: "K9nzg086pCNjq8dxl84GZg=="
          KEYCLOAK_DATALAND_ADMIN_PASSWORD: "password"
          DATALAND_QA_SERVICE_CLIENT_SECRET: "password"
          DATALAND_BATCH_MANAGER_CLIENT_SECRET: "password"
          DATALAND_COMMUNITY_MANAGER_CLIENT_SECRET: "password"
          DATALAND_EMAIL_SERVICE_CLIENT_SECRET: "password"
          DATALAND_API_KEY_MANAGER_CLIENT_SECRET: "password"
          DATALAND_ACCOUNTING_SERVICE_CLIENT_SECRET: "password"
          DATALAND_DATA_SOURCING_SERVICE_CLIENT_SECRET: "password"
          DATALAND_USER_SERVICE_CLIENT_SECRET: "password"
          DATALAND_DOCUMENT_MANAGER_CLIENT_SECRET: "password"
          DATALAND_BACKEND_CLIENT_SECRET: "password"
          DATALAND_DATA_EXPORTER_CLIENT_SECRET: "password"
          KEYCLOAK_READER_VALUE: "Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA=="
          KEYCLOAK_READER_SALT: "K9nzg086pCNjq8dxl84GZg=="
          KEYCLOAK_READER_PASSWORD: "password"
          KEYCLOAK_UPLOADER_VALUE: "Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA=="
          KEYCLOAK_UPLOADER_SALT: "K9nzg086pCNjq8dxl84GZg=="
          KEYCLOAK_UPLOADER_PASSWORD: "password"
          KEYCLOAK_REVIEWER_VALUE: "Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA=="
          KEYCLOAK_REVIEWER_SALT: "K9nzg086pCNjq8dxl84GZg=="
          KEYCLOAK_REVIEWER_PASSWORD: "password"
          KEYCLOAK_JUDGE_VALUE: "a+lk/Ddwa5wWL9T6BTZMhdNGEBiX6dzngWr5ic4Yt44="
          KEYCLOAK_JUDGE_SALT: "z7iDkOaNQfeUQEV3IBpEFQ=="
          KEYCLOAK_JUDGE_PASSWORD: "password"
          KEYCLOAK_PREMIUM_USER_VALUE: "Dic1AEUG0nKnZ8me/3GMxgfyUmbwmJwDWNXkC7arLcij2BDB0xeOgk8ZpfZPKmFNikr9Is5I4+Nyk3MB9zs7mA=="
          KEYCLOAK_PREMIUM_USER_SALT: "K9nzg086pCNjq8dxl84GZg=="
          KEYCLOAK_PREMIUM_USER_PASSWORD: "password"
          KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
          KC_BOOTSTRAP_ADMIN_PASSWORD: "password"
          KEYCLOAK_GOOGLE_ID: "irrelevant_in_ci"
          KEYCLOAK_GOOGLE_SECRET: "irrelevant_in_ci"
          PROXY_PRIMARY_URL: local-dev.dataland.com
          PROXY_LETSENCRYPT_PATH: /etc/letsencrypt/local-dev.dataland.com
          PROXY_IMAGE: ghcr.io/d-fine/dataland/dataland_inbound_proxy:${{ env.DATALAND_INBOUND_PROXY_VERSION }}
          CYPRESS_EXECUTION_ENVIRONMENT: "ci"
          CYPRESS_TEST_GROUP: 1
          CYPRESS_IGNORE_EXTERNAL_STORAGE: "false"
          TEST_EXECUTOR: "CYPRESS"
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          MAILJET_API_ID: ${{ secrets.MAILJET_API_ID }}
          MAILJET_API_SECRET: ${{ secrets.MAILJET_API_SECRET }}
          NOTIFICATION_INTERNAL_RECEIVERS: "anotherDummyCI@example.com"
          NOTIFICATION_INTERNAL_CC: "anotherDummyCI2@example.com"
          RABBITMQ_USER: "admin"
          RABBITMQ_PASS: "dataland"
          RABBITMQ_PASS_HASH: "1s3+3kZqRTAgidTV6NE+adO3ja5NFNQZHa9MBwhJ0Kx7Fw6F"
          FRONTEND_LOCATION_CONFIG: "Test"
          INTERNAL_EURODATCLIENT_URL: "http://dummy-eurodat-client:8080"
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          IGNORE_EXTERNAL_STORAGE_ERROR: "false"
          DATA_EXPORTER_OUTPUT_DIRECTORY: "/tmp"
          LOGGING_OPTIONS_MAX_SIZE: "1G"
          LOGGING_OPTIONS_MAX_FILE: 1
          GRAFANA_ADMIN: "admin"
          GRAFANA_PASSWORD: "password"
          LOKI_VOLUME: "./dataland-loki/data"
          SLACK_ALERT_URL: "irrelevant_in_ci"
          SLACK_CRITICAL_ALERT_URL: "irrelevant_in_ci"
      - name: Upload JaCoCo Exec Results
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: JaCoCoResultsE2ETest-cypress-1-run-${{ matrix.run }}
          path: ./*.exec
      - name: Upload lcov Exec Results
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: lcovResults-cypress-1-run-${{ matrix.run }}
          path: ./*.info
      - name: Upload E2E Test and Cypress Reports
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: e2eTestReports-cypress-1-run-${{ matrix.run }}
          path: |
            ./cypress
            ./coverage
            ./reports
      - name: Upload database dumps
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: e2eTestDatabaseDumps-cypress-1-run-${{ matrix.run }}
          path: ./dbdumps/
      - uses: ./.github/workflows/dockerLogs
        if: always()
        with:
          subfolder: 'e2etests_cypress_1_run_${{ matrix.run }}'
  manual-maintenance-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - name: "Check if manual maintenance was executed recently"
        run: git log --since $(date -d "- 35 days" "+%x") | grep -ie "manual.maintenance" || ( echo "Last Manual Maintenance is too old. Do it now!"; exit 1)
