name: CI
env:
  DATALAND_SKYMINDERCLIENT_TOKEN: ${{ secrets.DATALAND_SKYMINDERCLIENT_TOKEN }}
  DATALAND_SKYMINDERCLIENT_USER: ${{ secrets.DATALAND_SKYMINDERCLIENT_USER }}
  DATALAND_EDC_TOKEN: ${{ secrets.DATALAND_EDC_TOKEN }}
  DATALAND_EDC_USER: ${{ secrets.DATALAND_EDC_USER }}
  SKYMINDER_URL: ${{ secrets.SKYMINDER_URL }}
  SKYMINDER_PW: ${{ secrets.SKYMINDER_PW }}
  SKYMINDER_USER: ${{ secrets.SKYMINDER_USER }}

on:
  push:
    branches:
      - '**'

jobs:
  e2e-matrix:
    strategy:
      matrix:
        test: ["low", "dev", "other"]
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DATALAND_SKYMINDERCLIENT_USER }}
          password: ${{ secrets.DATALAND_SKYMINDERCLIENT_TOKEN }}
      - name: Retrieve SSL certificates for dataland-local.duckdns.org
        run: ./testing/retrieve_ssl_certs.sh
        env:
          DATALAND_LETSENCRYPT_HOST_KEYS: ${{ secrets.DATALAND_LETSENCRYPT_HOST_KEYS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Execute E2E Tests
        run: ./testing/execute_e2e_tests.sh
        env:
          SKYMINDER_URL: "http://skyminder-dummyserver:8080"
          KEYCLOAK_FRONTEND_URL: "https://dataland-local.duckdns.org/keycloak"
          KEYCLOAK_DB_PASSWORD: "password"
          KEYCLOAK_READER_VALUE: "qT0vhQ7bQA0OuAlJslpDr421pJQjZWIHxXZYePO9IOVVfZUX+85SwuwVrLgL/9xiW5hjyxlhKqQzUl7xUh+hVQ=="
          KEYCLOAK_READER_SALT: "6ZN+5rRT/wQcQqvNhXIsfA=="
          KEYCLOAK_READER_PASSWORD: "test"
          KEYCLOAK_UPLOADER_VALUE: "qT0vhQ7bQA0OuAlJslpDr421pJQjZWIHxXZYePO9IOVVfZUX+85SwuwVrLgL/9xiW5hjyxlhKqQzUl7xUh+hVQ=="
          KEYCLOAK_UPLOADER_SALT: "6ZN+5rRT/wQcQqvNhXIsfA=="
          KEYCLOAK_UPLOADER_PASSWORD: "test"
          KEYCLOAK_GOOGLE_ID: ${{ secrets.KEYCLOAK_GOOGLE_ID }}
          KEYCLOAK_GOOGLE_SECRET: ${{ secrets.KEYCLOAK_GOOGLE_SECRET }}
          PROXY_NGINX_URLS: dataland-local.duckdns.org
          PROXY_LETSENCRYPT_PATH: /etc/letsencrypt/dataland-local.duckdns.org
          PROXY_ENVIRONMENT: production
          ENVIRONMENT: ${{ matrix.test }}
      - name: Upload FE E2E Cypress Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          path: ./cypress
      - name: Upload E2E Test Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: e2eTestReports
          path: ./reports
      - name: Upload docker log files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: e2eTestDockerLogs
          path: ./dockerLogs
