name: Deploy to preview2

on:
  #TODO: Remove this trigger!
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/download-artifact@v2
        with:
          name: BootJar
          path: .
      - name: Deploy to Server
        run: |
          ls -R
          chmod +x ./deployment/deploy_to_preview.sh
          ./deployment/deploy_to_preview.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}