name: Deploy to preview

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Deploy to Server
        run: |
          chmod +x ./deployment/deploy_to_preview.sh
          ./deployment/deploy_to_preview.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}