name: Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Deploy to preview'
        default: 'World'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"