name: FE

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd dataland-frontend
          npm install
          ./node_modules/.bin/vue-cli-service test:unit
#      - name: Upload Test Reports
#        uses: actions/upload-artifact@v2
#        with:
#          name: TestReport
#          path: reports/
  frontend-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run E2E tests
        run: |
          cd dataland-frontend
          npm install
          ./node_modules/.bin/vue-cli-service test:E2E --headless