name: FE

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd dataland-frontend
          npm install
          ./node_modules/.bin/vue-cli-service test:unit