name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Execute formatting check
        run: |
          chmod +x ./gradlew
          ./gradlew ktlintcheck
      - name: Upload formatting log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: FormattingReport
          path: ./build/reports/ktlint
      - name: Execute tests
        if: always()
        run: ./gradlew test
      - name: Upload testing log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestReport
          path: ./build/reports/tests