// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.additionalcompanyinformation.model.general

import jakarta.validation.Valid
import org.dataland.datalandbackend.frameworks.additionalcompanyinformation.model.general.financialInformation
    .AdditionalCompanyInformationGeneralFinancialInformation
import org.dataland.datalandbackend.frameworks.additionalcompanyinformation.model.general.general
    .AdditionalCompanyInformationGeneralGeneral

/**
 * The data-model for the General section
 */
data class AdditionalCompanyInformationGeneral(
    @field:Valid()
    val general: AdditionalCompanyInformationGeneralGeneral? = null,
    @field:Valid()
    val financialInformation: AdditionalCompanyInformationGeneralFinancialInformation? = null,
)
