package org.dataland.datalandbackend.services.exportAliasesNonAssembledData

object SfdrExportAliasMapping : ExportAliasMapping {
    override val fieldNameToReadableName: Map<String, String> =
        mapOf(
            "general.general.dataDate" to "Data Date",
            "general.general.fiscalYearDeviation" to "Fiscal Year Deviation",
            "general.general.fiscalYearEnd" to "Fiscal Year End",
            "environmental.greenhouseGasEmissions.scope1GhgEmissionsInTonnes" to "Scope 1 GHG emissions",
            "environmental.greenhouseGasEmissions.scope2GhgEmissionsInTonnes" to "Scope 2 GHG emissions",
            "environmental.greenhouseGasEmissions.scope2GhgEmissionsLocationBasedInTonnes" to "Scope 2 GHG emissions (location-based)",
            "environmental.greenhouseGasEmissions.scope2GhgEmissionsMarketBasedInTonnes" to "Scope 2 GHG emissions (market-based)",
            "environmental.greenhouseGasEmissions.scope1And2GhgEmissionsInTonnes" to "Scope 1 and 2 GHG emissions",
            "environmental.greenhouseGasEmissions.scope1And2GhgEmissionsLocationBasedInTonnes"
                to "Scope 1 and 2 GHG emissions (location-based)",
            "environmental.greenhouseGasEmissions.scope1And2GhgEmissionsMarketBasedInTonnes"
                to "Scope 1 and 2 GHG emissions (market-based)",
            "environmental.greenhouseGasEmissions.scope3GhgEmissionsInTonnes" to "Scope 3 GHG emissions",
            "environmental.greenhouseGasEmissions.scope3UpstreamGhgEmissionsInTonnes" to "Scope 3 upstream GHG emissions",
            "environmental.greenhouseGasEmissions.scope3DownstreamGhgEmissionsInTonnes" to "Scope 3 downstream GHG emissions ",
            "environmental.greenhouseGasEmissions.scope1And2And3GhgEmissionsInTonnes" to "Scope 1 and 2 and 3 GHG emissions",
            "environmental.greenhouseGasEmissions.scope1And2And3GhgEmissionsLocationBasedInTonnes" to
                "Scope 1 and 2 and 3 GHG emissions (location-based)",
            "environmental.greenhouseGasEmissions.scope1And2And3GhgEmissionsMarketBasedInTonnes" to
                "Scope 1 and 2 and 3 GHG emissions (market-based)",
            "environmental.greenhouseGasEmissions.scope4GhgEmissionsInTonnes" to "Scope 4 GHG emissions",
            "environmental.greenhouseGasEmissions.enterpriseValueInEUR" to "Enterprise Value",
            "environmental.greenhouseGasEmissions.totalRevenueInEUR" to "Total Revenue",
            "environmental.greenhouseGasEmissions.carbonFootprintInTonnesPerMillionEUREnterpriseValue" to "Carbon footprint",
            "environmental.greenhouseGasEmissions.ghgIntensityInTonnesPerMillionEURRevenue" to "GHG intensity",
            "environmental.greenhouseGasEmissions.ghgIntensityScope1InTonnesPerMillionEURRevenue" to "GHG intensity - scope 1",
            "environmental.greenhouseGasEmissions.ghgIntensityScope2InTonnesPerMillionEURRevenue" to "GHG intensity - scope 2",
            "environmental.greenhouseGasEmissions.ghgIntensityScope3InTonnesPerMillionEURRevenue" to "GHG intensity - scope 3",
            "environmental.greenhouseGasEmissions.ghgIntensityScope4InTonnesPerMillionEURRevenue" to "GHG intensity - scope 4",
            "environmental.greenhouseGasEmissions.fossilFuelSectorExposure" to "Fossil Fuel Sector Exposure",
            "environmental.greenhouseGasEmissions.financedScope1AndScope2Emissions" to "Financed scope 1 and scope 2 emissions",
            "environmental.greenhouseGasEmissions.financedScope3Emissions" to "Financed scope 3 emissions",
            "environmental.energyPerformance.renewableEnergyProductionInGWh" to "Renewable Energy Production",
            "environmental.energyPerformance.RenewableEnergyConsumption" to "Renewable Energy Consumption",
            "environmental.energyPerformance.Non-RenewableEnergyProduction" to "Non-Renewable Energy Production",
            "environmental.energyPerformance.RelativeNon-RenewableEnergyProduction" to "Relative Non-Renewable Energy Production",
            "environmental.energyPerformance.Non-RenewableEnergyConsumption" to "Non-Renewable Energy Consumption",
            "environmental.energyPerformance.RelativeNon-RenewableEnergyConsumption" to "Relative Non-Renewable Energy Consumption",
            "environmental.energyPerformance.ApplicableHighImpactClimateSectors" to "Applicable High Impact Climate Sectors",
            "environmental.energyPerformance.TotalHighImpactClimateSectorEnergyConsumption" to
                "Total High Impact Climate Sector Energy Consumption",
            "environmental.biodiversity.PrimaryForestAndWoodedLandOfNativeSpeciesExposure" to
                "Primary Forest And Wooded Land Of Native Species Exposure",
            "environmental.biodiversity.ProtectedAreasExposure" to "Protected Areas Exposure",
            "environmental.biodiversity.RareOrEndangeredEcosystemsExposure" to "Rare Or Endangered Ecosystems Exposure",
            "environmental.biodiversity.HighlyBiodiverseGrasslandExposure" to "Highly Biodiverse Grassland Exposure",
            "environmental.water.EmissionsToWater" to "Emissions To Water",
            "environmental.Waste.HazardousandRadioactiveWaste" to "Hazardous and Radioactive Waste",
            "social.socialAndEmployeematters.HumanRightsLegalProceedings" to "Human Rights Legal Proceedings",
            "social.socialAndEmployeematters.ILOCoreLabourStandards" to "ILO Core Labour Standards",
            "social.socialAndEmployeematters.environmentalPolicy" to "Environmental Policy",
            "social.socialAndEmployeematters.CorruptionLegalProceedings" to "Corruption Legal Proceedings",
            "social.socialAndEmployeematters.TransparencyDisclosurePolicy" to "Transparency Disclosure Policy",
            "social.socialAndEmployeematters.HumanRightsDueDiligencePolicy" to "Human Rights Due Diligence Policy",
            "social.socialAndEmployeematters.PolicyagainstChildLabour" to "Policy against Child Labour",
            "social.socialAndEmployeematters.PolicyagainstForcedLabour" to "Policy against Forced Labour",
            "social.socialAndEmployeematters.PolicyagainstDiscriminationintheWorkplace" to "Policy against Discrimination in the Workplace",
            "social.socialAndEmployeematters.ISO14001Certificate" to "ISO 14001 Certificate",
            "social.socialAndEmployeematters.PolicyagainstBriberyandCorruption" to "Policy against Bribery and Corruption",
            "social.socialAndEmployeematters.FairBusinessMarketingAdvertisingPolicy" to "Fair Business Marketing Advertising Policy",
            "social.socialAndEmployeematters.TechnologiesExpertiseTransferPolicy" to "Technologies Expertise Transfer Policy",
            "social.socialAndEmployeematters.FairCompetitionPolicy" to "Fair Competition Policy",
            "social.socialAndEmployeematters.ViolationOfTaxRulesAndRegulation" to "Violation Of Tax Rules And Regulation",
            "social.socialAndEmployeematters.UNGlobalCompactPrinciplesCompliancePolicy" to "UN Global Compact Principles Compliance Policy",
            "social.socialAndEmployeematters.OECDGuidelinesForMultinationalEnterprisesGrievanceHandling" to
                "OECD Guidelines For Multinational Enterprises Grievance Handling",
            "social.socialAndEmployeematters.AverageGrossHourlyEarningsMaleEmployees" to "Average Gross Hourly Earnings Male Employees",
            "social.socialAndEmployeematters.AverageGrossHourlyEarningsFemaleEmployees" to "Average Gross Hourly Earnings Female Employees",
            "social.socialAndEmployeematters.Unadjustedgenderpaygap" to "Unadjusted gender pay gap",
            "social.socialAndEmployeematters.FemaleBoardMembers-SupervisoryBoard" to "Female Board Members - Supervisory Board",
            "social.socialAndEmployeematters.FemaleBoardMembers-BoardofDirectors" to "Female Board Members - Board of Directors",
            "social.socialAndEmployeematters.MaleBoardMembers-SupervisoryBoard" to "Male Board Members - Supervisory Board",
            "social.socialAndEmployeematters.MaleBoardMembers-BoardofDirectors" to "Male Board Members - Board of Directors",
            "social.socialAndEmployeematters.Boardgenderdiversity-SupervisoryBoard" to "Board gender diversity - Supervisory Board",
            "social.socialAndEmployeematters.Boardgenderdiversity-BoardofDirectors" to "Board gender diversity - Board of Directors",
            "social.socialAndEmployeematters.ControversialWeaponsExposure" to "Controversial Weapons Exposure",
            "environmental.Emissions.EmissionsofInorganicPollutants" to "Emissions of Inorganic Pollutants",
            "environmental.Emissions.EmissionsofAirPollutants" to "Emissions of Air Pollutants",
            "environmental.Emissions.EmissionsofOzoneDepletionSubstances" to "Emissions of Ozone Depletion Substances",
            "environmental.Emissions.CarbonReductionInitiatives" to "Carbon Reduction Initiatives",
            "environmental.energyPerformance.Non-RenewableEnergyConsumptionFossilFuels" to "Non-Renewable Energy Consumption Fossil Fuels",
            "environmental.energyPerformance.Non-RenewableEnergyConsumptionCrudeOil" to "Non-Renewable Energy Consumption Crude Oil",
            "environmental.energyPerformance.Non-RenewableEnergyConsumptionNaturalGas" to "Non-Renewable Energy Consumption Natural Gas",
            "environmental.energyPerformance.Non-RenewableEnergyConsumptionLignite" to "Non-Renewable Energy Consumption Lignite",
            "environmental.energyPerformance.Non-RenewableEnergyConsumptionCoal" to "Non-Renewable Energy Consumption Coal",
            "environmental.energyPerformance.Non-RenewableEnergyConsumptionNuclearEnergy" to
                "Non-Renewable Energy Consumption Nuclear Energy",
            "environmental.energyPerformance.Non-RenewableEnergyConsumptionOther" to "Non-Renewable Energy Consumption Other",
            "environmental.water.WaterConsumption" to "Water Consumption",
            "environmental.water.WaterReused" to "Water Reused",
            "environmental.water.RelativeWaterUsage" to "Relative Water Usage",
            "environmental.water.WaterManagementPolicy" to "Water Management Policy",
            "environmental.water.HighWaterStressAreaExposure" to "High Water Stress Area Exposure",
            "environmental.biodiversity.ManufactureOfAgrochemicalPesticidesProducts" to "Manufacture Of Agrochemical Pesticides Products",
            "environmental.biodiversity.LandDegradationDesertificationSoilSealingExposure" to
                "Land Degradation Desertification Soil Sealing Exposure",
            "environmental.biodiversity.SustainableAgriculturePolicy" to "Sustainable Agriculture Policy",
            "environmental.biodiversity.SustainableOceansAndSeasPolicy" to "Sustainable Oceans And Seas Policy",
            "environmental.waste.nonRecycledWasteInTonnes" to "Non-Recycled Waste",
            "environmental.biodiversity.ThreatenedSpeciesExposure" to "Threatened Species Exposure",
            "environmental.biodiversity.BiodiversityProtectionPolicy" to "Biodiversity Protection Policy",
            "environmental.biodiversity.DeforestationPolicy" to "Deforestation Policy",
            "social.Greensecurities.SecuritiesNotCertifiedAsGreen" to "Securities Not Certified As Green",
            "social.socialAndEmployeematters.WorkplaceAccidentPreventionPolicy" to "Workplace Accident Prevention Policy",
            "social.socialAndEmployeematters.RateOfAccidents" to "Rate Of Accidents",
            "social.socialAndEmployeematters.WorkdaysLost" to "Workdays Lost",
            "social.socialAndEmployeematters.SupplierCodeOfConduct" to "Supplier Code Of Conduct",
            "social.socialAndEmployeematters.GrievanceHandlingMechanism" to "Grievance Handling Mechanism",
            "social.socialAndEmployeematters.WhistleblowerProtectionPolicy" to "Whistleblower Protection Policy",
            "social.socialAndEmployeematters.ReportedIncidentsOfDiscrimination" to "Reported Incidents Of Discrimination",
            "social.socialAndEmployeematters.SanctionedIncidentsOfDiscrimination" to "Sanctioned Incidents Of Discrimination",
            "social.socialAndEmployeematters.ExcessiveCEOpayratio" to "Excessive CEO pay ratio",
            "social.Humanrights.HumanRightsPolicy" to "Human Rights Policy",
            "social.Humanrights.HumanRightsDueDiligence" to "Human Rights Due Diligence",
            "social.Humanrights.TraffickingInHumanBeingsPolicy" to "Trafficking In Human Beings Policy",
            "social.Humanrights.ReportedChildLabourIncidents" to "Reported Child Labour Incidents",
            "social.Humanrights.ReportedForcedOrCompulsoryLabourIncidents" to "Reported Forced Or Compulsory Labour Incidents",
            "social.Humanrights.NumberOfReportedIncidentsOfHumanRightsViolations" to
                "Number Of Reported Incidents Of Human Rights Violations",
            "social.Anti-corruptionandanti-bribery.CasesofInsufficientActionagainstBriberyandCorruption" to
                "Cases of Insufficient Action against Bribery and Corruption",
            "social.Anti-corruptionandanti-bribery.ReportedConvictionsOfBriberyandCorruption" to
                "Reported Convictions Of Bribery and Corruption",
            "social.Anti-corruptionandanti-bribery.TotalAmountOfReportedFinesOfBriberyandCorruption" to
                "Total Amount Of Reported Fines Of Bribery and Corruption",
        )
}
