// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.eutaxonomynonfinancials.model.revenue.nonEligibleShare

import org.dataland.datalandbackend.model.generics.AmountWithCurrency
import java.math.BigDecimal

/**
 * The data-model for the NonEligibleShare section
 */
data class EutaxonomyNonFinancialsRevenueNonEligibleShare(
    val relativeShareInPercent: BigDecimal? = null,

    val absoluteShare: AmountWithCurrency? = null,

)
