// <--WARNING--> THIS FILE IS AUTO-GENERATED BY THE FRAMEWORK-TOOLBOX AND WILL BE OVERWRITTEN
package org.dataland.datalandbackend.frameworks.gdv.model.allgemein.rechtsstreitigkeiten

import org.dataland.datalandbackend.model.enums.commons.YesNo

/**
 * The data-model for the Rechtsstreitigkeiten section
 */
data class GdvAllgemeinRechtsstreitigkeiten(
    val esgBezogeneRechtsstreitigkeiten: YesNo? = null,

    val rechtsstreitigkeitenMitBezugZuE: YesNo? = null,

    val statusZuE: StatusZuEOptions? = null,

    val einzelheitenZuDenRechtsstreitigkeitenZuE: String? = null,

    val rechtsstreitigkeitenMitBezugZuS: YesNo? = null,

    val statusZuS: StatusZuSOptions? = null,

    val einzelheitenZuDenRechtsstreitigkeitenZuS: String? = null,

    val rechtsstreitigkeitenMitBezugZuG: YesNo? = null,

    val statusZuG: StatusZuGOptions? = null,

    val einzelheitenZuDenRechtsstreitigkeitenZuG: String? = null,

)
